"""Dashboard section helpers: generated by refactor split."""
import json
from datetime import date as _date

def _charts_js(p):
    nsk = p['nine_star_ki']
    rok = p['rokusei']
    cycle9 = nsk.get('nine_year_cycle', [])
    combined = rok.get('reigou_combined', [])
    cycle12 = rok.get('twelve_year_cycle', [])

    # Overlay data — single chart with all lines
    nine_by_year = {c['year']: c['energy'] for c in cycle9}
    twelve_by_year = {c['year']: c['energy'] for c in cycle12}
    comb_by_year = {c['year']: c['score'] for c in combined}
    years = sorted(set(list(nine_by_year) + list(twelve_by_year) + list(comb_by_year)))
    overlay_labels = json.dumps([str(y) for y in years])
    nine_data = json.dumps([nine_by_year.get(y) for y in years])
    twelve_data = json.dumps([twelve_by_year.get(y) for y in years])
    comb_data = json.dumps([comb_by_year.get(y) for y in years])

    return f'''<script>
new Chart(document.getElementById('chartOverlay'),{{
  type:'line',
  data:{{labels:{overlay_labels},datasets:[
    {{label:'九星気学',data:{nine_data},borderColor:'#6366f1',fill:false,tension:0.4,borderWidth:2,pointRadius:4,pointBackgroundColor:'#6366f1'}},
    {{label:'六星占術',data:{twelve_data},borderColor:'var(--accent-green)',fill:false,tension:0.4,borderWidth:2,pointRadius:4,pointBackgroundColor:'var(--accent-green)'}},
    {{label:'霊合合成',data:{comb_data},borderColor:'#eab308',fill:false,tension:0.4,borderWidth:2,borderDash:[6,3],pointRadius:4,pointBackgroundColor:'#eab308'}}
  ]}},
  options:{{responsive:true,maintainAspectRatio:false,animation:{{duration:1500,easing:'easeOutQuart'}},interaction:{{mode:'index',intersect:false}},
    plugins:{{legend:{{display:false}}}},
    scales:{{x:{{ticks:{{color:'#7c8293',font:{{family:"'JetBrains Mono',monospace",size:11}}}},grid:{{color:'rgba(255,255,255,0.05)'}}}},
      y:{{min:0,max:110,ticks:{{display:false}},grid:{{color:'rgba(255,255,255,0.05)'}}}}}}
  }}
}});
const fadeObserver=new IntersectionObserver((entries)=>{{entries.forEach(e=>{{if(e.isIntersecting){{e.target.classList.add('visible');fadeObserver.unobserve(e.target);}}}});}},{{threshold:0.1,rootMargin:'0px 0px -40px 0px'}});
document.querySelectorAll('.section').forEach(s=>fadeObserver.observe(s));
function toggleAccordion(el){{el.classList.toggle('open');const body=el.nextElementSibling;if(body)body.classList.toggle('open');}}
</script>'''
