"""Dashboard section helpers: generated by refactor split."""
import json
from datetime import date as _date

def _get_archetype(p):
    """Generate archetype name from profile data."""
    dm = p['four_pillars']['day_master']
    sf_top5 = p.get('strengths_finder', {}).get('top5', [])

    # Map day master element to archetype prefix
    dm_archetypes = {
        '丁': 'Silent Flame', '丙': 'Radiant Sun',
        '甲': 'Ancient Oak', '乙': 'Wild Flower',
        '戊': 'Mountain', '己': 'Fertile Earth',
        '庚': 'Steel Edge', '辛': 'Hidden Gem',
        '壬': 'Deep Current', '癸': 'Morning Dew',
    }

    # Map top SF to archetype suffix
    sf_suffixes = {
        'Empathy': 'の共鳴者', 'Intellection': 'の探求者',
        'Deliberative': 'の賢者', 'Connectedness': 'の紡ぎ手',
        'Maximizer': 'の錬金術師', 'Futuristic': 'の予言者',
        'Relator': 'の絆の人', 'Activator': 'の点火者',
        'Command': 'の指揮官', 'Learner': 'の学究者',
        'Strategic': 'の戦略家', 'Achiever': 'の達成者',
        'Positivity': 'の太陽', 'Adaptability': 'の水の人',
    }

    prefix_en = dm_archetypes.get(dm.get('char', ''), 'The Seeker')
    prefix_ja_map = {
        'Silent Flame': '静かな炎', 'Radiant Sun': '輝く太陽',
        'Ancient Oak': '古の大樹', 'Wild Flower': '野の花',
        'Mountain': '不動の山', 'Fertile Earth': '豊穣の大地',
        'Steel Edge': '鋼の刃', 'Hidden Gem': '隠された宝石',
        'Deep Current': '深い流れ', 'Morning Dew': '朝露',
    }
    prefix_ja = prefix_ja_map.get(prefix_en, '探求者')

    if sf_top5:
        suffix = sf_suffixes.get(sf_top5[0]['name'], 'の探求者')
    else:
        suffix = 'の求道者'

    archetype_ja = f'{prefix_ja}{suffix}'
    return {'en': f'The {prefix_en}', 'ja': archetype_ja}

def _get_archetype_tagline(p):
    """Generate tagline from profile data."""
    interp = p.get('interpretations', {})
    hero = interp.get('hero', {})
    tagline = hero.get('tagline', '')
    if tagline:
        return tagline

    dm = p['four_pillars']['day_master']
    dm_char = dm.get('char', '')
    sf_top5 = p.get('strengths_finder', {}).get('top5', [])
    if sf_top5:
        top_ja = SF_JA.get(sf_top5[0]['name'], sf_top5[0]['name'])
        return f'深い{top_ja}で、本質を見抜く人'

    # Profile-aware fallback taglines by day master character
    reigou = p['rokusei'].get('reigou', False)
    age = p.get('identity', {}).get('age', 0)
    dm_taglines = {
        '壬': '大海のように。静かに、深く、すべてを受け止めて' if age >= 60 else '流れを読む目。深みが、あなたの答えを知っている',
        '癸': '静かな雨のように。気づけばあなたの言葉が、誰かの土壌に根を張っている',
        '丁': '消えない炎。あなたが照らす場所に、人は安心して集まる',
        '丙': '太陽のように。あなたがいるだけで、場が明るくなる',
        '甲': '真っ直ぐに、上へ。あなたの成長は、周囲の森になる',
        '乙':'しなやかに、遠くまで。あなたの柔軟さが、最終的に勝つ',
        '戊': '矛盾の中にこそ、あなたの力がある' if reigou else '山のように揺るぎなく。その深さが、人を支える',
        '己': '静かに育てる人。あなたの器に、何人もの人が実った',
        '庚': '迷わず、決める。その切れ味が、道を開く',
        '辛': '磨けば磨くほど、輝きが増す。あなたは本物の宝石',
    }
    return dm_taglines.get(dm_char, '静かに燃える、唯一の存在')

def _get_share_tagline(p: dict) -> str:
    """Generate a standalone hook line for the free share card.

    Unlike _get_archetype_tagline (read in-context inside the dashboard),
    this must land on its own — no surrounding page, no explanation.
    Format: a slightly exposing observation, then a reframe as strength.
    """
    dm = p['four_pillars']['day_master']
    dm_char = dm.get('char', '')
    share_taglines = {
        '壬': '表面は静か。でも中では、誰よりも多くを感じ、考えている。',
        '癸': '気づかれないくらい静かに、一番深いところまで届く人。',
        '丁': '大声を出さなくても、その場の空気を変えてしまう人。',
        '丙': 'いるだけで場が明るくなるのに、本人はそれに気づいていない。',
        '甲': '曲がらない人、というより、曲がる必要がなかった人。',
        '乙': '折れそうで折れない。そのしなやかさに、みんな救われている。',
        '戊': '動かないんじゃない。動く必要がないほど、すでに強い。',
        '己': '誰かの成長を、自分の手柄にしない人。',
        '庚': '優しさより先に、正しさを選んでしまう人。',
        '辛': '磨かれるほど輝くタイプ。まだ本気を出していない。',
    }
    return share_taglines.get(dm_char, '静かに燃える、唯一の存在。')

def _get_essence_sub(dm, ys):
    """Generate Core Essence sub-description from day master + year star."""
    dm_subs = {
        '丁': '静かな炎',
        '丙': '太陽の輝き',
        '甲': '大木の力',
        '乙': '草花のしなやかさ',
        '戊': '大地の安定',
        '己': '大地の柔軟さ',
        '庚': '鋼の意志',
        '辛': '宝石の繊細さ',
        '壬': '大河の流れ',
        '癸': '雨露の慈しみ',
    }
    ys_subs = {
        '七赤金星': '言葉の力',
        '五黄土星': '中央の統率力',
        '一白水星': '知恵と柔軟性',
        '二黒土星': '母なる支える力',
        '三碧木星': '行動と成長',
        '四緑木星': '信用と調和',
        '六白金星': '権威と正義',
        '八白土星': '改革と蓄積',
        '九紫火星': '華やかさと直感',
    }
    dm_sub = dm_subs.get(dm.get('char', ''), '')
    ys_sub = ys_subs.get(ys.get('name', ''), '')
    if dm_sub and ys_sub:
        return f'{dm_sub} × {ys_sub}'
    return dm_sub or ys_sub or ''

def _get_duality_value(bt, ennea, rok):
    """Generate duality value from blood type + personality."""
    bt_traits = {
        'AB': '合理 × 感性',
        'A': '誠実 × 繊細',
        'B': '自由 × 情熱',
        'O': '大胆 × 包容',
    }
    return bt_traits.get(bt.get('type', ''), '独自の二面性')

def _get_missing_sub(missing):
    """Generate sub-description for missing elements."""
    elem_meanings = {
        '金': '決断力・収穫',
        '水': '柔軟性・知恵',
        '木': '成長力・発展',
        '火': '情熱・行動力',
        '土': '安定・信頼',
    }
    parts = []
    for m in missing[:2]:
        meaning = elem_meanings.get(str(m), '')
        if meaning:
            parts.append(meaning)
    if parts:
        return f'{" × ".join(parts)}を意識的に補う'
    return ''

DM_NARRATIVE_LONG = {
    '甲': '大樹のように真っ直ぐ上へと伸びてゆく、力強い成長の気をお持ちです。何もないところから形を作っていく、開拓者の資質を生まれながらに授かっています。',
    '乙': '柔らかくしなる蔓のような、しなやかな粘りをお持ちの方です。周囲と調和しながら、気づけば遠くまで広がっているような生き方が、あなたには自然と馴染みます。',
    '丙': '太陽のような明朗で温かな発信の力を授かっています。場を明るくし、人を照らす天性のリーダー性を、控えめながらも内に秘めていらっしゃいます。',
    '丁': 'ロウソクの炎のように、必要な方だけを静かに照らす繊細な光をお持ちです。激しくはないけれど、消えることのない火。そんな深い温もりをあなたは宿していらっしゃいます。',
    '戊': '動じない山のような、どっしりとした安定感をお持ちです。しかしあなたの山の地下深くには、豊かな水脈が静かに流れています。表の安定の裏に繊細な感受性と柔軟な適応力——それがあなたの真骨頂です。周囲が揺れても芯はぶれず、自然と人から頼られながら、内側では誰よりも深く感じていらっしゃいます。',
    '己': '田畑のように、人や物を育てる豊かな器をお持ちです。ご自身が目立つことよりも、誰かを実らせることに静かな喜びを見出されるお方です。',
    '庚': '鋼の刃のような決断力と切れ味を授かっています。不要なものを見極めて切り捨て、真っ直ぐに前へ進む凛とした意志をお持ちです。',
    '辛': '磨き上げられた宝石のような、繊細な美意識をお持ちです。細部への目と品位の高さが、あなたの魅力そのものとなっていらっしゃいます。',
    '壬': '大海のような、広く深い包容力と知恵をお持ちの方です。年を重ねるごとに深みが増す命式で、若い頃の苦労や迷いがすべて滋養となって今のあなたを形作っています。人の痛みをわかる器と、静かに流れを読む眼は、人生の積み重ねから生まれた本物の宝でございます。',
    '癸': '雨露のように繊細に、静かに浸透していく力をお持ちです。目立たずとも、確実に周囲に良い影響を及ぼされるお方です。',
}

NS_NARRATIVE = {
    '一白水星': '「水」の星をお持ちです。静かに浸透していく知恵と、場を柔らかく整える柔軟性が、あなたの表の顔となっていらっしゃいます。',
    '二黒土星': '「大地」の星をお持ちです。派手さよりも堅実さを大切にされ、誰かを支える側に回ることに深い喜びを見出されるお方です。',
    '三碧木星': '「雷」の星をお持ちです。発信力と推進力を授かり、動きながら道を切り拓いていくのが自然な生き方でいらっしゃいます。',
    '四緑木星': '「風」の星をお持ちです。人と人のご縁を繋ぎ、信用を育てていく役目を担っていらっしゃいます。目立たずとも影響力の大きいお方です。',
    '五黄土星': '「帝王」の星をお持ちです。中心に立ち、場を掌握する強い存在感を、生まれながらに授かっていらっしゃいます。',
    '六白金星': '「天」の星をお持ちです。公正な判断と理想を追い求める、凛とした精神性がお有りです。',
    '七赤金星': '「沢」の星をお持ちです。社交と言葉の力で場を華やかに楽しませる、天性の社交家でいらっしゃいます。',
    '八白土星': '「山」の星をお持ちです。変化を乗り越える粘り強さと、じっくり蓄えていく力を授かっています。',
    '九紫火星': '「火」の星をお持ちです。知性と美意識、そして物事を明らかにする鋭い洞察力が、あなたの持ち味でいらっしゃいます。',
}

ROKUSEI_NARRATIVE = {
    '木星人': '伸び広がる木星人でいらっしゃいます。成長・拡張・挑戦が、あなたを健やかに保つエネルギー源となっています。',
    '火星人': '燃え立つ火星人でいらっしゃいます。情熱と行動力の塊。じっとしていらっしゃると不調に傾きやすい、動いて整う方です。',
    '土星人': '動かない土星人でいらっしゃいます。どっしりと構え、長距離走で最終的に勝つタイプの方です。',
    '金星人': '磨かれた金星人でいらっしゃいます。洗練・美・優雅を重んじる、品位あるお方です。',
    '水星人': '流れる水星人でいらっしゃいます。知恵と柔軟性で環境を読み解いていく才をお持ちです。',
    '天王星人': '自由な天王星人でいらっしゃいます。型にはまらない独自路線を、生まれながらに選ばれる方です。',
}

CORE_IDENTITY_TAGLINES = {
    ('壬', '二黒土星'): '大地に宿る、深く静かな水',
    ('壬', '一白水星'): '深海のように、すべてを映し出す知恵',
    ('壬', '三碧木星'): '大河の水が、木々を押し広げてゆく力',
    ('壬', '四緑木星'): '水が縁を結び、流れてゆく信頼の人',
    ('壬', '五黄土星'): '大海の底に、帝王の静けさが宿る',
    ('壬', '六白金星'): '天の高みと深海の底、両方を知る者',
    ('壬', '七赤金星'): '流れる水が、言葉に変わる瞬間',
    ('壬', '八白土星'): '山を越えてきた大河のような、深い底力',
    ('壬', '九紫火星'): '水と火が溶け合う、炎のような知性',
    ('戊', '四緑木星'): '山が風を受けとめ、縁を育む大地',
    ('戊', '一白水星'): '山の地下を流れる、静かな知恵',
    ('戊', '二黒土星'): '大地が大地を抱く、揺るぎない支え',
    ('戊', '三碧木星'): '山肌を拓いてゆく、行動する大地',
    ('戊', '五黄土星'): '天下無双の山、静かに中央に立つ',
    ('戊', '六白金星'): '山の頂に宿る、公正な意志',
    ('戊', '七赤金星'): '山から生まれる清流のような、温かな言葉',
    ('戊', '八白土星'): '重なる山のような、長く深い底力',
    ('戊', '九紫火星'): '火山のように、内に知性の熱を秘める',
    ('甲', '一白水星'): '水辺に根を張る大樹のような、揺るぎない知恵',
    ('甲', '二黒土星'): '豊かな大地に立つ一本樹、支えと成長の象徴',
    ('甲', '三碧木星'): '稲妻を受けてなお伸びる、開拓者の大木',
    ('甲', '四緑木星'): '縁を結びながら天へ伸びる、信頼の大樹',
    ('甲', '五黄土星'): '大地を割って立つ、圧倒的な生命力',
    ('甲', '六白金星'): '天に向かって一直線、正義の大樹',
    ('甲', '七赤金星'): '言葉で人を引きつける、明るい大木',
    ('甲', '八白土星'): '岩山に根を張る、一本の強い樹',
    ('甲', '九紫火星'): '火に照らされ輝く、知性と成長の象徴',
    ('乙', '一白水星'): '水に沿ってしなやかに広がる、柔の知恵',
    ('乙', '二黒土星'): '大地にそっと根を張る、静かな粘り強さ',
    ('乙', '三碧木星'): '嵐の中でもたわんで折れない、しなやかな力',
    ('乙', '四緑木星'): '柔らかく絡まりながら、遠くへ伸びてゆく縁',
    ('丙', '一白水星'): '水面に映る太陽、知恵を照らす温もり',
    ('丙', '二黒土星'): '大地を温める陽光、支える者を照らす',
    ('丁', '一白水星'): 'ろうそくの炎が、静かな水面を照らす夜',
    ('丁', '二黒土星'): '大地の上で静かに燃える、消えない炎',
    ('庚', '一白水星'): '清流に研がれた刃のような、明晰な意志',
    ('庚', '二黒土星'): '大地から鍛えられた鋼のような、決断力',
    ('辛', '一白水星'): '水晶のように澄んだ、繊細な美意識',
    ('辛', '二黒土星'): '大地の宝石、静かな輝きを放つ内面',
    ('己', '一白水星'): '水を含んだ豊かな田、知恵が実を結ぶ',
    ('己', '二黒土星'): '二重の大地の豊かさ、育てることの喜び',
    ('癸', '一白水星'): '雨露と泉水が溶け合う、深い静けさ',
    ('癸', '二黒土星'): '大地に染み入る雨、じわりと広がる優しさ',
}

def _get_core_tagline(dm, ys):
    key = (dm.get('char', ''), ys.get('name', ''))
    tagline = CORE_IDENTITY_TAGLINES.get(key)
    if tagline:
        return tagline
    return _get_essence_sub(dm, ys)

WESTERN_NARRATIVE = {
    'Aries':   '牡羊座（火・活動宮）— 先陣を切る開拓者',
    'Taurus':  '牡牛座（土・不動宮）— 五感と安定を愛する人',
    'Gemini':  '双子座（風・柔軟宮）— 情報と言葉の達人',
    'Cancer':  '蟹座（水・活動宮）— 情と家族を大切にする包容力',
    'Leo':     '獅子座（火・不動宮）— 中心に立つ華やかさ',
    'Virgo':   '乙女座（土・柔軟宮）— 細部を整える職人肌',
    'Libra':   '天秤座（風・活動宮）— バランスと美を重んじる調停者',
    'Scorpio': '蠍座（水・不動宮）— 本質に迫る深掘り型',
    'Sagittarius': '射手座（火・柔軟宮）— 自由と哲学を求める冒険家',
    'Capricorn':   '山羊座（土・活動宮）— 長期戦で実績を積む人',
    'Aquarius':    '水瓶座（風・不動宮）— 独自視点の革新者',
    'Pisces':      '魚座（水・柔軟宮）— 感受性豊かな夢想家',
}

BT_NARRATIVE_LONG = {
    'A':  '真面目・几帳面・計画的で、信頼をコツコツ積み上げていかれるタイプの方です（日本人の約 38%）',
    'B':  '自由・独立心・独自路線を愛し、枠にはめられることを好まれないタイプの方です（日本人の約 22%）',
    'O':  '人間好き・現実主義で大らか、場を温めるムードメーカーでいらっしゃるタイプの方です（日本人の約 31%）',
    'AB': '合理と感性の両立。状況に応じて最適なモードを切り替えられる、適応力の高いタイプの方です（日本人の約 9%）',
}

def _auto_integrated_insight(p):
    """narratives.yaml が無いユーザー向けに、4〜5段落の統合インサイトを自動生成。"""
    try:
        dm = p['four_pillars']['day_master']
        dm_char = dm.get('char', '')
        dm_element = dm.get('element', '')
        dm_yy = dm.get('yin_yang', '')
        ns = p['nine_star_ki']['year_star']
        ns_name = ns.get('name', '')
        rok = p['rokusei']['main_star']
        rok_name = rok.get('name', '')
        reigou = p['rokusei'].get('reigou', False)
        sun_sign = p['western_astrology']['sun_sign'].get('sign', '')
        animal = p['four_pillars']['year_pillar']['branch'].get('animal', '')
        animal_ja = {'Rat':'子','Ox':'丑','Tiger':'寅','Rabbit':'卯','Dragon':'辰','Snake':'巳',
                     'Horse':'午','Goat':'未','Monkey':'申','Rooster':'酉','Dog':'戌','Pig':'亥'}.get(animal, animal)
        bt = p.get('blood_type', {}).get('type', '')
        missing = p['four_pillars'].get('missing_elements', [])
        name = p.get('identity', {}).get('name', 'あなた')
        age = p.get('identity', {}).get('age', 0)
        sex = p.get('identity', {}).get('sex', '')

        dm_story = DM_NARRATIVE_LONG.get(dm_char, '')
        ns_story = NS_NARRATIVE.get(ns_name, '')
        rok_story = ROKUSEI_NARRATIVE.get(rok_name, '')
        sun_story = WESTERN_NARRATIVE.get(sun_sign, '')
        bt_story = BT_NARRATIVE_LONG.get(bt, '')
        eto_story = ETO_GIST.get(animal, '')

        # 年齢層別の開口一番 (p0) — 70歳以上は人生集大成、40-60代は転換期
        p0 = None
        if age >= 70:
            cur9 = next((c for c in p['nine_star_ki'].get('nine_year_cycle', []) if c.get('current')), None)
            cur12 = next((c for c in p['rokusei'].get('twelve_year_cycle', []) if c.get('current')), None)
            if cur9 and cur12 and cur9['energy'] >= 80 and cur12['energy'] >= 80:
                p0 = (f'{name}さん、{age}年という人生のすべてが、今このダッシュボードの言葉に凝縮されています。'
                      f'占いは「未来を当てるもの」ではなく、<strong>「あなたが歩んできた道を肯定するもの」</strong>でもあります。'
                      f'今年は九星気学で<strong>{cur9["palace"]}（{cur9["theme"]}）</strong>、六星占術で<strong>{cur12["phase"]}</strong>——'
                      f'複数の体系が口を揃えて「今年が実りの時」と告げています。'
                      f'これまでの努力と選択は、正しかったのです。')
            else:
                p0 = (f'{name}さん、{age}年という人生の積み重ねが、あなたの命式の深みとなって輝いています。'
                      f'占いの言葉は、あなたが経験してきたことをただ映し出す鏡です。'
                      f'ここに書かれている強みも、気を付けるべき点も、すべて<strong>あなたが既に知っていること</strong>のはずです。')
        elif 40 <= age < 60:
            cur9 = next((c for c in p['nine_star_ki'].get('nine_year_cycle', []) if c.get('current')), None)
            cur_comb = next((c for c in p['rokusei'].get('reigou_combined', []) if c.get('year') == 2026), None)
            if reigou and cur_comb and cur_comb['score'] < 50:
                # 霊合矛盾期の特別メッセージ
                p0 = (f'{name}さん、今あなたの中に「なぜこんなに頑張っているのにうまくいかない」という感覚はありませんか。'
                      f'それは気のせいでも、あなたの責任でもありません。'
                      f'霊合星人のあなたは今年、<strong>2つの運命星が正反対のことを言っている時期</strong>に入っています。'
                      f'主星は「達成せよ」と言い、副星は「立ち止まれ」と言う——その矛盾が、あなたの疲れの根本にあります。'
                      f'矛盾を感じているなら、それはあなたのセンサーが正常に機能している証拠です。')
            elif cur9 and cur9['energy'] <= 40:
                p0 = (f'{name}さん、{age}歳というのは、「これまでの自分」と「これからの自分」が静かに入れ替わる時期です。'
                      f'今年は九星気学で<strong>{cur9["palace"]}（{cur9["theme"]}）</strong>に位置し、外へ向かうエネルギーより、'
                      f'<strong>内側を見直すエネルギー</strong>の方が大きい時期にあたります。'
                      f'停滞に感じるものは、実は次のフェーズへの準備です。')

        # 段1: 日主 + 本命星 + 血液型
        p1 = f'''{name}さんを一言で言い表すなら、四柱推命の日主が示す「<strong>{dm_char}日主</strong>」——{dm_story} そして、九星気学の本命星から見える社会に出た時のお顔は「<strong>{ns_name}</strong>」——{ns_story} 血液型は「<strong>{bt}型</strong>」で、{bt_story}。生年月日という揺るぎない事実だけから、{name}さんの核はこのように浮かび上がります。'''

        # 段2: 西洋占星術 + 干支
        p2 = f'''視点を変えて西洋占星術で見ると、あなたは <strong>{sun_story}</strong>。東洋の干支に目を向けると <strong>{animal_ja}年（{eto_story}）</strong>でいらっしゃいます。起源の全く違う 2 つの体系が、あなたの気質を別々の角度から描き出しているのです。東洋と西洋の読みが重なり合う場所に、<strong>「本当に変わらないあなたの軸」</strong>が静かに見えてまいります。'''

        # 段3: 六星占術 (+ 霊合)
        if reigou:
            sub_star = p['rokusei'].get('sub_star', {})
            sub_name = sub_star.get('name', '') if sub_star else ''
            if sub_name:
                p3 = (f'さらに六星占術の視点を加えますと、あなたは <strong>{rok_name}（霊合星人）</strong>でいらっしゃいます。{rok_story} '
                      f'霊合星人は日本人口のわずか 15% しかいない希少な体質で、あなたの場合は <strong>{rok_name}</strong> と <strong>{sub_name}</strong> の2つの運命星を同時に宿しています。'
                      f'<strong>運気の振れ幅が一般の 2 倍</strong>——好調の時期は抜きん出て輝き、不調の時期は深く沈む。'
                      f'それはあなたが「普通の人生」ではなく、<strong>ドラマのある人生を生きている証</strong>でもあります。')
            else:
                p3 = f'''さらに六星占術の視点を加えますと、あなたは <strong>{rok_name}（霊合星人）</strong>でいらっしゃいます。{rok_story} 霊合星人は日本人口のわずか 15% しかいない希少な体質で、2 つの運命星を同時に宿すため <strong>運気の振れ幅が一般の 2 倍</strong>と言われております。好調の時期は抜きん出て、不調の時期は深く沈む——そんなダイナミックなリズムが、あなたの人生を形作っていらっしゃるのです。'''
        else:
            p3 = f'''六星占術の視点を加えると、あなたは <strong>{rok_name}</strong>でいらっしゃいます。{rok_story} 12 年周期で運気が巡るため、「今の時期になさるべきこと・お控えになるべきこと」が明確に見えてくるのが、この体系ならではの強みでございます。'''

        # 段4: 欠けている五行 + 運用アドバイス
        if missing:
            miss_str = '・'.join(missing)
            miss_action = {
                '木':'挑戦や拡張の行動',
                '火':'情熱を込めた発信・人前に出る場面',
                '土':'腰を据えた継続・コツコツ積み上げる時間',
                '金':'決断と手放すこと・期限を設けること',
                '水':'流動性・休息・柔軟にお受けになる姿勢',
            }
            miss_meaning = {
                '木':'成長力・拡張・新しいスタート',
                '火':'情熱・行動力・人前に出る力',
                '土':'継続力・安定・地道な積み上げ',
                '金':'決断力・収穫・区切りをつける力',
                '水':'知恵・柔軟性・流れに乗る力',
            }
            actions = '、'.join(miss_action.get(m, '') for m in missing if m in miss_action)
            meanings = '、'.join(f'「{miss_meaning.get(m, m)}」' for m in missing if m in miss_meaning)
            p4 = (f'最後に、お気を付けいただきたい点を一つ。あなたの命式で欠けている五行は「<strong>{miss_str}</strong>」でいらっしゃいます。'
                  f'これは {meanings} のエネルギーが命式から出づらい構造であることを示しています。'
                  f'「弱点」ではなく、「<strong>意識的に補うと、全体のバランスが整う方向</strong>」とお考えください。'
                  f'自然体では{actions}が後回しになりがちですので、'
                  f'予定や環境を整える形で仕組みになさると、あなたの本来の強みが最大限に活きてまいります。')
        else:
            p4 = f'''五行の分布は美しくバランスが取れています。特定の要素が突出することも、欠けることもない整った命式でいらっしゃいます。言い換えますと、<strong>「どの方向にも振れる柔軟性」</strong>をお持ちで、状況に応じて様々なモードを自然に使い分けていかれるタイプの方です。'''

        paragraphs = [p1, p2, p3, p4]
        if p0:
            paragraphs = [p0] + paragraphs
        return paragraphs
    except Exception as e:
        return [f'統合インサイトの自動生成に失敗: {e}']

def _core_identity(p):
    dm = p['four_pillars']['day_master']
    ys = p['nine_star_ki']['year_star']
    missing = p['four_pillars'].get('missing_elements', [])
    interp = p.get('interpretations', {})

    # Integrated insight box — first paragraph visible, rest collapsed
    insight_paras = interp.get('integrated_insight', [])
    # narratives.yaml が無いユーザー向けのフォールバック: プロファイルから自動生成
    if not insight_paras:
        insight_paras = _auto_integrated_insight(p)
    insight_html = ''
    if insight_paras:
        first_p = f'<p style="line-height:1.9;font-size:14px;">{insight_paras[0]}</p>'
        if len(insight_paras) > 1:
            rest_ps = ''.join(f'<p style="line-height:1.9;font-size:14px;margin-top:12px;">{para}</p>'
                              for para in insight_paras[1:])
            insight_html = f'''<div class="insight-box" style="border-left-color:#4F46E5">
    <div class="insight-title" style="font-size:15px;">統合インサイト</div>
    {first_p}
    <div class="collapsible-content" style="display:none">{rest_ps}</div>
    <button class="collapse-toggle" onclick="this.previousElementSibling.style.display=this.previousElementSibling.style.display==='none'?'block':'none';this.textContent=this.previousElementSibling.style.display==='none'?'続きを読む':'閉じる'">続きを読む</button>
  </div>'''
        else:
            insight_html = f'''<div class="insight-box" style="border-left-color:#4F46E5">
    <div class="insight-title" style="font-size:15px;">統合インサイト</div>
    {first_p}
  </div>'''

    # Dynamic summary cards
    dm_desc = dm.get('description', '')
    # Core Essence
    yin_yang_ja = {'Yin':'陰','Yang':'陽'}.get(dm.get('yin_yang',''), '')
    elem_ja = {'Fire':'火','Wood':'木','Earth':'土','Metal':'金','Water':'水'}.get(dm.get('element',''), '')
    essence_value = f'{dm["char"]}{elem_ja} × {ys["name"]}'
    essence_sub = _get_essence_sub(dm, ys)

    # Strongest Axis
    sf_top5 = p.get('strengths_finder', {}).get('top5', [])
    if sf_top5 and len(sf_top5) >= 2:
        t1_ja = SF_JA.get(sf_top5[0]['name'], sf_top5[0]['name'])
        t2_ja = SF_JA.get(sf_top5[1]['name'], sf_top5[1]['name'])
        axis_value = f'{t1_ja} × {t2_ja}'
        axis_sub = f'{sf_top5[0]["name"]}（{t1_ja}）+ {sf_top5[1]["name"]}（{t2_ja}）'
    else:
        # Fallback: 干支の気質 × 日主の本質
        animal_local = p['four_pillars']['year_pillar']['branch'].get('animal', '')
        eto_gist_local = ETO_GIST.get(animal_local, '')
        dm_char_local = dm.get('char', '')
        dm_gist_local = DM_GIST.get(dm_char_local, '')
        if eto_gist_local and dm_gist_local:
            axis_value = f'{eto_gist_local} × {dm_char_local}の本質'
            axis_sub = f'干支が示す気質 + 日主が示す判断軸'
        else:
            axis_value = '詳細は Tier 2 で'
            axis_sub = '性格アンケートで明確化'

    # Duality
    bt = p['blood_type']
    ennea = p.get('personality', {}).get('enneagram', {})
    rok = p['rokusei']
    etype = ennea.get('type', None)
    reigou = rok.get('reigou', False)
    # Tier 1 (エニアグラム未取得) は、霊合星人の有無で表現を変える
    if etype:
        if reigou:
            dual_sub = f'{bt["type"]}型 × 霊合星人 × エニアグラム Type {etype}'
        else:
            dual_sub = f'{bt["type"]}型 × エニアグラム Type {etype}'
    else:
        if reigou:
            dual_sub = f'{bt["type"]}型 × 霊合星人（二つの運命星）'
        else:
            dual_sub = f'{bt["type"]}型 × 陰陽のバランス'
    dual_value = _get_duality_value(bt, ennea, rok)

    # Watch Out
    if missing:
        missing_str = "・".join(str(m) for m in missing)
        watch_value = f'{missing_str}の欠如'
        watch_sub = _get_missing_sub(missing)
    else:
        watch_value = '—'
        watch_sub = ''

    tagline = _get_core_tagline(dm, ys)
    quote_html = f'<div class="section-quote">"あなたを一言で表すなら——{tagline}"</div>'

    dm_char = dm.get('char', '')
    ys_name = ys.get('name', '')
    rok_type = rok.get('main_star', {}).get('name', '') if 'main_star' in rok else ''
    dm_narr = DM_NARRATIVE_LONG.get(dm_char, '')
    ys_narr = NS_NARRATIVE.get(ys_name, '')
    rok_narr = ROKUSEI_NARRATIVE.get(rok_type, '')

    narr_cards = ''
    if dm_narr:
        narr_cards += f'''<div class="card" style="border-left:3px solid #6366f1">
      <div class="card-label" style="color:#a5b4fc">日主「{dm_char}」</div>
      <div style="font-size:13px;line-height:1.8;color:var(--text-secondary);margin-top:6px">{dm_narr}</div>
    </div>'''
    if ys_narr:
        narr_cards += f'''<div class="card" style="border-left:3px solid var(--accent-green)">
      <div class="card-label" style="color:#86efac">本命星「{ys_name}」</div>
      <div style="font-size:13px;line-height:1.8;color:var(--text-secondary);margin-top:6px">{ys_narr}</div>
    </div>'''
    if rok_narr:
        narr_cards += f'''<div class="card" style="border-left:3px solid #eab308">
      <div class="card-label" style="color:#fde047">六星占術「{rok_type}」</div>
      <div style="font-size:13px;line-height:1.8;color:var(--text-secondary);margin-top:6px">{rok_narr}</div>
    </div>'''
    narr_panel = f'''<div style="margin-top:16px">
    <div class="section-sub-title" style="font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:var(--text-muted);margin-bottom:10px">命式の読み解き</div>
    <div class="grid grid-3">{narr_cards}</div>
  </div>''' if narr_cards else ''

    return f'''<section class="section" id="core-identity">
  {quote_html}
  {narr_panel}
  {insight_html}
  <div class="grid grid-4" style="margin-top:16px">
    <div class="card tc"><div class="card-label">本質</div>
      <div class="card-value">{essence_value}</div>
      <div class="card-sub">{essence_sub}</div></div>
    <div class="card tc"><div class="card-label">最強の軸</div>
      <div class="card-value">{axis_value}</div>
      <div class="card-sub">{axis_sub}</div></div>
    <div class="card tc"><div class="card-label">二面性</div>
      <div class="card-value">{dual_value}</div>
      <div class="card-sub">{dual_sub}</div></div>
    <div class="card tc"><div class="card-label">注意点</div>
      <div class="card-value" style="color:var(--yellow)">{watch_value}</div>
      <div class="card-sub">{watch_sub}</div></div>
  </div>
</section>'''

def _personality_locked():
    """Show locked skeleton + CTA for users without personality data."""
    return '''<section class="section" id="personality">
  <div class="personality-locked">
    <div class="locked-skeleton">
      <div class="locked-row"></div>
      <div class="locked-row short"></div>
      <div class="locked-row"></div>
      <div class="locked-grid">
        <div class="locked-box"></div>
        <div class="locked-box"></div>
        <div class="locked-box"></div>
        <div class="locked-box"></div>
      </div>
    </div>
    <div class="locked-overlay">
      <div class="locked-icon">&#128274;</div>
      <div class="locked-title">あなたの強みと性格タイプが見える</div>
      <div class="locked-desc">10分の質問に答えるだけで、あなたの隠れた才能と性格の核心が明らかになります</div>
      <a href="../form/" class="locked-cta">才能を発見する</a>
    </div>
  </div>
</section>'''

def _personality(p, tier):
    if tier < 2:
        return _personality_locked()
    pers = p.get('personality', {})
    ennea = pers.get('enneagram', {})
    hsp = pers.get('hsp', {})
    adhd = pers.get('adhd', {})
    bt = p['blood_type']
    sf = p.get('strengths_finder', {})
    sf_top5 = sf.get('top5', [])

    domain_colors = {'Relationship Building':'var(--accent-blue)','Strategic Thinking':'var(--accent-green)',
                     'Executing':'var(--accent-purple-dark)','Influencing':'#ff6b35'}
    tag_cls = {'Relationship Building':'tag-rb','Strategic Thinking':'tag-st',
               'Executing':'tag-ex','Influencing':'tag-inf'}
    interp = p.get('interpretations', {})
    sf_descs = interp.get('strengths', {})
    sf_ja = interp.get('strengths_ja', {})
    pers_descs = interp.get('personality', {})

    # Dynamic personality summary
    personality_summary = ''
    if sf_top5 and ennea:
        t1_ja = SF_JA.get(sf_top5[0]['name'], sf_top5[0]['name'])
        t2_ja = SF_JA.get(sf_top5[1]['name'], sf_top5[1]['name']) if len(sf_top5) > 1 else ''
        ename = ENNEA_NAMES.get(ennea.get('type', 0), '')
        summary_text = f'「{t1_ja}」と「{t2_ja}」を軸に、{ename}としての深みを持つ'
        personality_summary = f'<div class="personality-summary">{summary_text}</div>'

    sf_html = ''
    if sf_top5:
        items = ''
        for s in sf_top5:
            tc = tag_cls.get(s.get('domain',''), 'tag-rb')
            ja_name = sf_ja.get(s['name'], '') or SF_JA.get(s['name'], '')
            ja_span = f' <span style="font-size:12px;color:var(--text-secondary);font-weight:400">（{ja_name}）</span>' if ja_name else ''
            desc = sf_descs.get(s['name'], '')
            desc_html = f'<div class="sf-desc-collapsible" style="display:none;font-size:12px;color:var(--text-secondary);line-height:1.6;margin-top:6px">{desc}</div>' if desc else ''
            toggle_attr = ' onclick="var d=this.querySelector(\'.sf-desc-collapsible\');if(d){{d.style.display=d.style.display===\'none\'?\'block\':\'none\'}}" style="cursor:pointer"' if desc else ''
            items += f'''<li class="top5-item"{toggle_attr}><span class="rank">{s["rank"]}</span>
          <div><div class="sf-name">{s["name"]}{ja_span}</div>
          <div class="sf-domain"><span class="tag {tc}">{s["domain"]}</span></div>{desc_html}</div></li>'''
        dom_bars = ''
        sf_domains = sf.get('domain_distribution', {})
        for dname, ranks in sf_domains.items():
            dc = domain_colors.get(dname, '#6366f1')
            top10 = sum(1 for r in ranks if r <= 10)
            dname_ja = DOMAIN_JA.get(dname, '')
            dname_disp = f'{dname}（{dname_ja}）' if dname_ja else dname
            dom_bars += f'''<div class="domain-bar">
          <div class="domain-header"><span>{dname_disp}</span><span style="font-family:var(--font-mono)">{top10} / 10</span></div>
          <div class="domain-track"><div class="domain-fill" style="width:{top10*10}%;background:{dc}"></div></div></div>'''

        etype = ennea.get('type', '?')
        ename = ENNEA_NAMES.get(etype, '')
        hsp_label = HSP_LABELS.get(hsp.get('score', ''), hsp.get('score', ''))
        adhd_label = ADHD_LABELS.get(adhd.get('tendency', ''), adhd.get('tendency', ''))

        sf_html = f'''<div class="grid"><div class="card">
      <div class="card-title"><span class="icon">&#9733;</span> あなたの TOP 5 強み</div>
      <ul class="top5-list">{items}</ul>
      <div style="font-size:11px;color:var(--text-muted);margin-top:12px">主要な強みの分野: {sf.get("lead_domain","")}{" (" + DOMAIN_JA.get(sf.get("lead_domain",""), "") + ")" if DOMAIN_JA.get(sf.get("lead_domain","")) else ""} | 受験日: {sf.get("date_taken","")}</div>
    </div>
    <div class="card">
      <div class="card-title"><span class="icon">&#9632;</span> 強みの傾向</div>
      <div style="margin-top:8px">{dom_bars}</div>
      <div style="margin-top:24px">
        <div class="card-title" style="font-size:13px"><span class="icon">&#9830;</span> あなたの性格タイプ</div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:4px">
          <div class="typo-cell"><div class="typo-label">エニアグラム</div>
            <div class="typo-value">Type {etype}</div><div class="typo-sub">{ename}</div>
            {"<div class='typo-desc'>"+pers_descs['enneagram']+"</div>" if pers_descs.get('enneagram') else ""}</div>
          <div class="typo-cell"><div class="typo-label">血液型</div>
            <div class="typo-value">{bt["type"]}</div><div class="typo-sub">日本人口の{bt["population_pct"]}%</div>
            {"<div class='typo-desc'>"+pers_descs['blood_type']+"</div>" if pers_descs.get('blood_type') else ""}</div>
        </div>
      </div>
      <div style="margin-top:24px">
        <div class="card-title" style="font-size:13px"><span class="icon">&#9830;</span> エネルギー特性</div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:4px">
          <div class="typo-cell"><div class="typo-label">感受性タイプ</div>
            <div class="typo-value" style="color:#facc15">{hsp_label}</div><div class="typo-sub">環境・感情への感度</div>
            {"<div class='typo-desc'>"+pers_descs['sensitivity']+"</div>" if pers_descs.get('sensitivity') else ""}</div>
          <div class="typo-cell"><div class="typo-label">集中スタイル</div>
            <div class="typo-value" style="color:#ff8f6b">{adhd_label}</div><div class="typo-sub">過集中×拡散の波</div>
            {"<div class='typo-desc'>"+pers_descs['focus_pattern']+"</div>" if pers_descs.get('focus_pattern') else ""}</div>
        </div>
      </div>
    </div></div>'''

    return f'''<section class="section" id="personality">
  {_section_quote('personality')}
  {personality_summary}
  {sf_html}
</section>'''

def _western_detail(p):
    wa = p['western_astrology']
    west = wa['sun_sign']
    ruling = wa.get('ruling_planet', '')
    decan = wa.get('decan', {})
    el_traits = wa.get('element_traits', '')
    q_traits = wa.get('quality_traits', '')
    traits = wa.get('traits', '')
    forecast = wa.get('forecast_2026', '')
    west_el_ja = {'Water':'水','Fire':'火','Earth':'地','Air':'風'}.get(west['element'], west['element'])
    west_q_ja = {'Fixed':'不動宮','Cardinal':'活動宮','Mutable':'柔軟宮'}.get(west['quality'], west['quality'])

    cards = f'''<div class="grid grid-3">
    <div class="card"><div class="card-label">太陽星座</div>
      <div class="card-value">{west["symbol"]} {west["sign"]}</div>
      <div class="card-sub">{west_el_ja}（{west["element"]}）/ {west_q_ja}（{west["quality"]}）</div>
      {"<div class='typo-desc' style='margin-top:8px'>"+traits+"</div>" if traits else ""}</div>
    <div class="card"><div class="card-label">支配星</div>
      <div class="card-value">{ruling}</div>
      {"<div class='typo-desc' style='margin-top:8px'>"+el_traits+"</div>" if el_traits else ""}</div>'''
    if decan:
        cards += f'''<div class="card"><div class="card-label">デカン（第{decan.get("number","")}区）</div>
      <div class="card-value">{decan.get("sub_ruler","")}</div>
      {"<div class='typo-desc' style='margin-top:8px'>"+decan.get("traits","")+"</div>" if decan.get("traits") else ""}</div>'''
    cards += '</div>'

    desc_parts = ''
    if q_traits:
        desc_parts += f'<div style="font-size:12px;color:var(--text-secondary);line-height:1.7;margin-top:12px">{q_traits}</div>'
    if forecast:
        desc_parts += f'''<div class="insight-box" style="margin-top:12px;border-left-color:var(--accent-purple-light)">
      <div class="insight-title" style="color:var(--accent-purple-light)">2026年 {west["sign"]}の運勢</div>
      <p style="line-height:1.9;font-size:14px">{forecast}</p></div>'''

    # --- Transits card ---
    transits = wa.get('transits_2026', {})
    if transits:
        aspect_colors = {
            'Trine': 'var(--accent-green-light)', 'Sextile': 'var(--accent-green-light)', 'Semisextile': 'var(--accent-blue-light)',
            'Square': 'var(--accent-red-light)', 'Opposition': 'var(--accent-red-light)', 'Quincunx': '#facc15',
            'Conjunction': 'var(--accent-purple-light)',
        }
        aspect_icons = {
            'Trine': '&#9651;', 'Sextile': '&#9734;', 'Semisextile': '&#8226;',
            'Square': '&#9633;', 'Opposition': '&#9675;', 'Quincunx': '&#8767;',
            'Conjunction': '&#9673;',
        }
        transit_html = '<div style="margin-top:20px"><div class="insight-title" style="color:var(--accent-purple-light);margin-bottom:8px">2026年 惑星の影響</div>'
        transit_html += '<div style="font-size:12px;color:var(--text-muted);margin-bottom:12px;line-height:1.6">木星・土星・冥王星・天王星が今年あなたの太陽星座にどんな影響を与えるか。緑は追い風、黄色は調整期、赤は試練（成長のチャンス）。</div>'
        transit_html += '<div class="grid grid-2">'
        planet_ja = {'jupiter': '木星', 'saturn': '土星', 'pluto': '冥王星', 'uranus': '天王星'}
        sign_ja = {
            'Cancer': '蟹座', 'Aries': '牡羊座', 'Aquarius': '水瓶座', 'Gemini': '双子座',
            'Leo': '獅子座', 'Taurus': '牡牛座', 'Pisces': '魚座', 'Scorpio': '蠍座',
            'Sagittarius': '射手座', 'Capricorn': '山羊座', 'Virgo': '乙女座', 'Libra': '天秤座',
        }
        for planet_key in ['jupiter', 'saturn', 'pluto', 'uranus']:
            t = transits.get(planet_key, {})
            if not t:
                continue
            aspect = t.get('aspect_to_sun', '')
            color = aspect_colors.get(aspect, '#a5b4fc')
            icon = aspect_icons.get(aspect, '&#9679;')
            sign = t.get('sign', '')
            sign_display = sign_ja.get(sign, sign)
            aspect_ja = {'Trine':'追い風','Sextile':'好機','Semisextile':'微調整','Square':'試練','Opposition':'対峙','Quincunx':'調整','Conjunction':'合流'}.get(aspect, aspect)
            transit_html += f'''<div class="card" style="border-left:3px solid {color}">
        <div class="card-label">{planet_ja.get(planet_key, planet_key)} in {sign_display}</div>
        <div class="card-value" style="font-size:16px;color:{color}">{aspect_ja}</div>
        <div class="typo-desc" style="margin-top:6px;font-size:12px">{t.get("influence", "")}</div></div>'''
        transit_html += '</div></div>'
        desc_parts += transit_html

    # --- Mercury Retrograde Timeline ---
    mercury_retro = wa.get('mercury_retrograde_2026', [])
    if mercury_retro:
        retro_html = '<div style="margin-top:20px"><div class="insight-title" style="color:#fb923c;margin-bottom:8px">&#9888; 2026年 水星逆行</div>'
        retro_html += '<div style="font-size:12px;color:var(--text-muted);margin-bottom:12px;line-height:1.6">水星逆行中はコミュニケーションの行き違い、契約トラブル、電子機器の不具合が起きやすい時期。重要な契約や大きな買い物はこの期間を避けるのが無難。</div>'
        retro_html += '<div class="grid grid-3">'
        for i, retro in enumerate(mercury_retro):
            sign = retro.get('sign', '')
            sign_display = sign_ja.get(sign, sign) if transits else sign
            retro_html += f'''<div class="card" style="border-left:3px solid rgba(251,146,60,0.5)">
        <div class="card-label">第{i+1}回</div>
        <div class="card-value" style="font-size:14px">{retro.get("period", "")}</div>
        <div class="card-sub">{sign_display}（{sign}）</div>
        <div class="typo-desc" style="margin-top:6px;font-size:12px">{retro.get("impact", "")}</div></div>'''
        retro_html += '</div></div>'
        desc_parts += retro_html

    # --- Current month western horoscope highlight ---
    monthly_horo = wa.get('monthly_horoscope', [])
    current_month_num = _date.today().month
    cur_west = next((h for h in monthly_horo if h['month'] == current_month_num), None)
    if cur_west:
        west_energy = cur_west.get('energy', 0)
        west_color = energy_color(west_energy)
        desc_parts += f'''<div class="insight-box" style="margin-top:16px;border-left-color:var(--accent-purple-light)">
      <div class="insight-title" style="color:var(--accent-purple-light)">{current_month_num}月の{west["sign"]}ホロスコープ — 「{cur_west["theme"]}」</div>
      <div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
        <div style="font-size:24px;font-weight:700;color:{west_color}">{west_energy}</div>
        <div style="font-size:11px;color:var(--text-muted)">西洋エネルギー /100</div>
      </div>
      <p style="line-height:1.9;font-size:14px">{cur_west["focus"]}</p></div>'''

    return cards + desc_parts

def _rarity_badges(p):
    """Generate rarity badges to make users feel special about their unique traits."""
    badges = []
    rok = p['rokusei']
    fp = p['four_pillars']
    dm = fp['day_master']
    missing = fp.get('missing_elements', [])

    # Reigou rarity
    if rok.get('reigou'):
        badges.append('霊合星人は全人口の約10%。二つの星の影響を受ける稀少な存在です')

    # Day master rarity
    dm_char = dm.get('char', '')
    yin_yang = dm.get('yin_yang', '')
    elem = dm.get('element', '')
    elem_ja = {'Fire':'火','Wood':'木','Earth':'土','Metal':'金','Water':'水'}.get(elem, elem)
    yy_ja = {'Yin':'陰','Yang':'陽'}.get(yin_yang, '')
    if dm_char and yy_ja:
        badges.append(f'日主「{dm_char}」（{yy_ja}{elem_ja}）は十干の一つ。同じ本質を持つ人は約10%')

    # Missing elements rarity
    if len(missing) >= 2:
        missing_str = '・'.join(str(m) for m in missing)
        badges.append(f'五行「{missing_str}」が同時に欠如する命式は稀少。意識的な補完が大きな差を生む')
    elif len(missing) == 1:
        badges.append(f'五行「{missing[0]}」の欠如は、その分他の要素が強い証。個性の源泉')

    if not badges:
        return ''

    html = '<div class="rarity-badges" style="display:flex;flex-wrap:wrap;gap:8px;margin-bottom:16px">'
    for b in badges:
        html += f'<div class="rarity-badge">{b}</div>'
    html += '</div>'
    return html
