"""Dashboard section helpers: generated by refactor split."""
import json
from datetime import date as _date

def _mercury_retro_badge(mercury_retro, month_num):
    """Generate a mercury retrograde warning badge if this month has one."""
    if not mercury_retro:
        return ''
    for retro in mercury_retro:
        period = retro.get('period', '')
        # Parse period like "2/26-3/20" to check if month_num falls in range
        parts = period.split('-')
        if len(parts) == 2:
            start_month = int(parts[0].split('/')[0])
            end_month = int(parts[1].split('/')[0])
            if start_month <= month_num <= end_month or (start_month == month_num or end_month == month_num):
                return (f'<span class="month-tag" style="background:rgba(251,146,60,0.18);color:#fb923c;border:1px solid rgba(251,146,60,0.4)">'
                        f'&#9888; 水星逆行 in {retro["sign"]} ({period})</span>')
    return ''

def _phase_color_py(rtype):
    """Return phase color dict for Python-side rendering."""
    if rtype == 'great':
        return {'bg': 'rgba(34,197,94,0.12)', 'border': 'rgba(34,197,94,0.3)', 'color': 'var(--accent-green-light)'}
    if rtype == 'good':
        return {'bg': 'rgba(59,130,246,0.12)', 'border': 'rgba(59,130,246,0.3)', 'color': 'var(--accent-blue-light)'}
    if rtype == 'caution':
        return {'bg': 'rgba(234,179,8,0.12)', 'border': 'rgba(234,179,8,0.3)', 'color': '#facc15'}
    return {'bg': 'rgba(239,68,68,0.12)', 'border': 'rgba(239,68,68,0.3)', 'color': 'var(--accent-red-light)'}

def _divination(p):
    fp = p['four_pillars']
    pillars = [fp['year_pillar'], fp['month_pillar'], fp['day_pillar']]
    dm = fp['day_master']
    elements = fp['five_elements_balance']
    missing = fp.get('missing_elements', [])
    nsk = p['nine_star_ki']
    ys, ms = nsk['year_star'], nsk['month_star']
    rok = p['rokusei']
    west = p['western_astrology']['sun_sign']

    interp = p.get('interpretations', {})
    fp_interp = interp.get('four_pillars', {})
    nsk_interp = interp.get('nine_star_ki', {})
    rok_interp = interp.get('rokusei', {})

    pillar_labels = ['年柱', '月柱', '日柱']
    pillar_roles = ['社会的顔・祖先運', '仕事・キャリア', '本質的な自己']
    pillar_keys = ['year', 'month', 'day']
    elem_cls = {'Wood':'elem-wood','Fire':'elem-fire','Earth':'elem-earth','Metal':'elem-metal','Water':'elem-water'}
    elem_ja = {'Wood':'木','Fire':'火','Earth':'土','Metal':'金','Water':'水'}
    pcards = ''
    for i, pl in enumerate(pillars):
        ec = elem_cls.get(pl['stem']['element'], '')
        pcards += f'''<div class="pillar"><div class="pillar-label">{pillar_labels[i]}</div>
      <div class="kanji">{pl["full"]}</div>
      <div class="reading">{pl["stem"]["reading"]}・{pl["branch"]["reading"]}</div>
      <div class="element-badge {ec}">{elem_ja.get(pl["stem"]["element"], pl["stem"]["element"])}（{pl["stem"]["element"]}）</div>
      <div style="font-size:10px;color:var(--text-muted);margin-top:6px">{pillar_roles[i]}</div></div>'''
    pcards += '<div class="pillar unknown"><div class="pillar-label">時柱</div><div class="kanji">？？</div><div class="reading">出生時刻不明</div><div class="element-badge" style="background:rgba(255,255,255,0.05);color:var(--text-muted)">未解放</div><div style="font-size:10px;color:var(--text-muted);margin-top:6px">晩年・子孫運</div></div>'

    el_bars = ''
    el_colors = {'木':'var(--accent-green-light)','火':'var(--accent-red-light)','土':'#facc15','金':'#94a3b8','水':'var(--accent-blue-light)'}
    for el_name in ['木','火','土','金','水']:
        info = elements.get(el_name, {})
        pct = info.get('pct', 0)
        el_bars += f'''<div class="element-col">
      <div class="element-pct" style="color:{el_colors[el_name]}">{pct}%</div>
      <div class="element-fill" style="height:{max(pct,2)}%;background:{el_colors[el_name]}"></div>
      <div class="element-name">{el_name}</div></div>'''

    missing_html = ''
    if missing:
        insight = fp.get('element_insight', '')
        missing_html = f'<div style="font-size:12px;color:var(--yellow);margin-top:8px">欠如: {"・".join(str(m) for m in missing)}{" — "+insight if insight else ""}</div>'

    cur9 = next((c for c in nsk.get('nine_year_cycle', []) if c.get('current')), None)
    el5_ja = {'Metal':'金','Fire':'火','Earth':'土','Water':'水','Wood':'木'}
    dir_ja = {'N':'北','S':'南','E':'東','W':'西','NE':'北東','NW':'北西','SE':'南東','SW':'南西','C':'中央'}
    nsk_cards = f'''<div class="grid grid-3">
    <div class="card"><div class="card-label">{_glossary_tooltip('本命星', '本命星（年星）— あなたの根幹')}</div>
      <div class="card-value">{ys["name"]}</div><div class="card-sub">{el5_ja.get(ys["element"],ys["element"])}（{ys["element"]}）/ {dir_ja.get(ys["direction"],ys["direction"])}（{ys["direction"]}）</div></div>
    <div class="card"><div class="card-label">{_glossary_tooltip('月命星', '月命星 — 内面の性格')}</div>
      <div class="card-value">{ms["name"]}</div><div class="card-sub">{el5_ja.get(ms["element"],ms["element"])}（{ms["element"]}）/ {dir_ja.get(ms["direction"],ms["direction"])}（{ms["direction"]}）</div></div>'''
    if cur9:
        nsk_cards += f'''<div class="card"><div class="card-label">2026年 宮位置 — 今年の運気</div>
      <div class="card-value">{cur9["palace"]}</div><div class="card-sub">{cur9["theme"]}（運気 {cur9["energy"]}/100）</div></div>'''
    nsk_cards += '</div>'

    cur12 = next((c for c in rok.get('twelve_year_cycle', []) if c.get('current')), None)
    rok_cards = f'''<div class="grid grid-3">
    <div class="card"><div class="card-label">{_glossary_tooltip('運命星')}</div>
      <div class="card-value">{rok["main_star"]["name"]}({rok["main_star"]["polarity"]})</div>
      <div class="card-sub">{rok["main_star"]["reading"]}</div></div>'''
    if rok.get('reigou') and rok.get('sub_star'):
        rok_cards += f'''<div class="card"><div class="card-label">{_glossary_tooltip('霊合星人', '霊合サブ星')}</div>
      <div class="card-value">{rok["sub_star"]["name"]}({rok["sub_star"]["polarity"]})</div>
      <div class="card-sub">{rok["sub_star"]["reading"]}</div></div>'''
    if cur12:
        phase_label = satsukai_html(cur12.get('殺界')) if cur12.get('殺界') else '好調期'
        rok_cards += f'''<div class="card"><div class="card-label">2026年</div>
      <div class="card-value">{cur12["phase"]}</div>
      <div class="card-sub">{phase_label}（運気 {cur12["energy"]}/100）</div></div>'''
    rok_cards += '</div>'

    cycle12 = rok.get('twelve_year_cycle', [])
    sub_by_year = {c['year']: c for c in rok.get('sub_star_cycle', [])}
    has_sub = rok.get('reigou', False)
    rows = ''
    for c in cycle12:
        cls = ' class="current"' if c.get('current') else ''
        sub_td = f'<td>{sub_by_year[c["year"]]["phase"] if c["year"] in sub_by_year else "—"}</td>' if has_sub else ''
        rows += f'<tr{cls}><td>{c["year"]}</td><td>{c["phase"]}</td>{sub_td}'
        rows += f'<td>{satsukai_html(c.get("殺界"))}</td>'
        rows += f'<td><span style="color:{energy_color(c["energy"])}">{c["energy"]}</span></td></tr>'

    sub_th = '<th>サブ</th>' if has_sub else ''
    table = f'<table class="cycle-table"><thead><tr><th>年</th><th>メイン</th>{sub_th}<th>殺界</th><th>運気</th></tr></thead><tbody>{rows}</tbody></table>'

    # Four Pillars interpretation text
    fp_overview = fp_interp.get('overview', '')
    fp_overview_html = f'<div style="font-size:12px;color:var(--text-secondary);line-height:1.7;margin-bottom:16px">{fp_overview}</div>' if fp_overview else ''
    dm_detail = fp_interp.get('day_master_detail', dm['description'])
    pillar_descs = ''
    for key, label in [('year', '年柱'), ('month', '月柱'), ('day', '日柱')]:
        desc = fp_interp.get(key, '')
        if desc:
            full = fp[f'{key}_pillar']['full']
            pillar_descs += f'<strong style="color:var(--text)">{label}（{full}）</strong>: {desc}<br>'
    pillar_descs_html = f'<div style="margin-top:8px;font-size:12px;color:var(--text-secondary);line-height:1.7">{pillar_descs}</div>' if pillar_descs else ''

    # Nine Star Ki interpretation
    nsk_year_desc = nsk_interp.get('year', '')
    nsk_month_desc = nsk_interp.get('month', '')
    nsk_desc_html = ''
    if nsk_year_desc or nsk_month_desc:
        parts = ''
        if nsk_year_desc:
            parts += f'<div style="font-size:12px;color:var(--text-secondary);line-height:1.7">{nsk_year_desc}</div>'
        if nsk_month_desc:
            parts += f'<div style="font-size:12px;color:var(--text-secondary);line-height:1.7;margin-top:8px">{nsk_month_desc}</div>'
        nsk_desc_html = f'<div class="card" style="margin-top:12px">{parts}</div>'

    # Rokusei interpretation
    rok_main_desc = rok_interp.get('main', '')
    rok_sub_desc = rok_interp.get('sub', '')
    rok_reigou_desc = rok_interp.get('reigou', '')
    rok_desc_html = ''
    if rok_main_desc or rok_sub_desc:
        parts = ''
        if rok_main_desc:
            parts += f'<strong style="color:var(--text)">{rok["main_star"]["name"]}({rok["main_star"]["polarity"]})</strong>: {rok_main_desc}<br>'
        if rok_sub_desc:
            parts += f'<strong style="color:var(--text)">{rok["sub_star"]["name"]}({rok["sub_star"]["polarity"]})</strong>: {rok_sub_desc}'
        rok_desc_html = f'<div style="font-size:12px;color:var(--text-secondary);line-height:1.7;margin-bottom:12px">{parts}</div>'
    reigou_box = ''
    if rok.get('reigou') and rok_reigou_desc:
        reigou_box = f'''<div style="background:rgba(234,179,8,0.08);border:1px solid rgba(234,179,8,0.2);border-radius:var(--r-sm);padding:12px;text-align:center;margin-top:12px">
      <div style="font-size:13px;color:var(--yellow);font-weight:600">霊合星人</div>
      <div style="font-size:12px;color:var(--text-secondary);margin-top:6px;line-height:1.7;text-align:left">{rok_reigou_desc}</div></div>'''

    # Rarity badges
    rarity_html = _rarity_badges(p)

    return f'''<section class="section" id="divination">
  {_section_quote('divination')}
  {rarity_html}

  <div class="accordion-header open" onclick="toggleAccordion(this)"><h3 class="sub-title" style="border-top:none;padding-top:0;margin:0">四柱推命</h3></div>
  <div class="accordion-body open">
  {fp_overview_html}
  <div class="pillar-grid">{pcards}</div>
  <div style="margin-top:16px;font-size:13px;color:var(--text-secondary);line-height:1.7">
    <strong style="color:var(--text)">日主（にっしゅ）: {dm["char"]}火（{dm["yin_yang"]}火 / ひのと）</strong> — あなたの生まれ持った本質。{dm_detail}</div>
  {pillar_descs_html}
  <div class="element-bar" style="margin-top:12px">{el_bars}</div>
  {missing_html}
  </div>

  <div class="accordion-header" onclick="toggleAccordion(this)"><h3 class="sub-title" style="border-top:none;padding-top:0;margin:0">九星気学</h3></div>
  <div class="accordion-body">
  {nsk_cards}
  {nsk_desc_html}
  </div>

  <div class="accordion-header" onclick="toggleAccordion(this)"><h3 class="sub-title" style="border-top:none;padding-top:0;margin:0">六星占術</h3></div>
  <div class="accordion-body">
  {rok_cards}
  {rok_desc_html}
  {reigou_box}
  <div style="margin-top:12px">{table}</div>
  </div>

  <div class="accordion-header" onclick="toggleAccordion(this)"><h3 class="sub-title" style="border-top:none;padding-top:0;margin:0">西洋占星術</h3></div>
  <div class="accordion-body">
  {_western_detail(p)}
  </div>

  <div class="unlock-banner">出生時刻を追加すると、時柱・アセンダント・月星座が解放されます</div>
</section>'''

def _forecast(p):
    nsk = p['nine_star_ki']
    rok = p['rokusei']
    cur9 = next((c for c in nsk.get('nine_year_cycle', []) if c.get('current')), None)
    cur12 = next((c for c in rok.get('twelve_year_cycle', []) if c.get('current')), None)
    cur_sub = next((c for c in rok.get('sub_star_cycle', []) if c.get('current')), None)
    cur_comb = next((c for c in rok.get('reigou_combined', []) if c.get('year') == 2026), None)
    has_reigou = rok.get('reigou', False)

    cards = '<div class="grid grid-4">'
    if cur9:
        cards += f'''<div class="card tc"><div class="card-label">九星気学</div>
      <div class="card-value">{cur9["palace"]}</div><div class="card-sub">{cur9["theme"]}</div></div>'''
    if cur12:
        cards += f'''<div class="card tc"><div class="card-label">六星占術（メイン）</div>
      <div class="card-value">{cur12["phase"]}</div><div class="card-sub">運気 {cur12["energy"]}/100</div></div>'''
    if cur_sub:
        sub_label = satsukai_html(cur_sub.get('殺界')) if cur_sub.get('殺界') else f'運気 {cur_sub["energy"]}/100'
        cards += f'''<div class="card tc"><div class="card-label">六星占術（サブ）</div>
      <div class="card-value">{cur_sub["phase"]}</div><div class="card-sub">{sub_label}</div></div>'''
    if cur_comb:
        cards += f'''<div class="card tc"><div class="card-label">霊合統合スコア</div>
      <div class="card-value" style="color:{energy_color(cur_comb["score"])}">{cur_comb["score"]}</div>
      <div class="card-sub">{cur_comb["label"]}</div></div>'''
    cards += '</div>'

    # Chart legend: explain each line
    legend_items = [
        ('#6366f1', '九星気学', '9年周期。本命星の宮遷移による運気の波。社会的な運勢の流れを示す'),
        ('var(--accent-green)', '六星占術', '12年周期。大殺界を含む運命星の巡り。個人的な運気のバイオリズム'),
    ]
    if has_reigou:
        legend_items.append(('#eab308', '霊合合成', 'メイン星を主・サブ星を従として統合した運気スコア。霊合星人の実効的な運勢を示す'))

    legend_html = '<div class="chart-legend">'
    for color, label, desc in legend_items:
        legend_html += f'''<div class="chart-legend-item">
      <span class="chart-legend-line" style="background:{color}"></span>
      <div><span class="chart-legend-label">{label}</span>
      <span class="chart-legend-desc">{desc}</span></div></div>'''
    legend_html += '</div>'

    # Integrated forecast insight
    insight = _forecast_insight(cur9, cur12, cur_sub, cur_comb, has_reigou, nsk, rok, p=p)

    # Year theme one-liner
    year_theme = _year_theme(cur_comb, cur9, cur12, has_reigou, p)

    # Western astrology transit summary for forecast section
    wa = p.get('western_astrology', {})
    transits = wa.get('transits_2026', {})
    transit_summary = ''
    if transits:
        sign_ja = {
            'Cancer': '蟹座', 'Aries': '牡羊座', 'Aquarius': '水瓶座', 'Gemini': '双子座',
            'Leo': '獅子座', 'Pisces': '魚座', 'Scorpio': '蠍座',
        }
        planet_ja = {'jupiter': '木星', 'saturn': '土星', 'pluto': '冥王星', 'uranus': '天王星'}
        aspect_colors = {
            'Trine': 'var(--accent-green-light)', 'Sextile': 'var(--accent-green-light)', 'Semisextile': 'var(--accent-blue-light)',
            'Square': 'var(--accent-red-light)', 'Opposition': 'var(--accent-red-light)', 'Quincunx': '#facc15',
        }
        transit_items = ''
        for pk in ['jupiter', 'saturn', 'pluto', 'uranus']:
            t = transits.get(pk, {})
            if not t:
                continue
            aspect = t.get('aspect_to_sun', '')
            color = aspect_colors.get(aspect, '#a5b4fc')
            sign_display = sign_ja.get(t.get('sign', ''), t.get('sign', ''))
            transit_items += (f'<span style="display:inline-flex;align-items:center;gap:4px;margin-right:12px;font-size:12px">'
                             f'<span style="color:{color};font-weight:600">{planet_ja.get(pk, pk)}</span>'
                             f'<span style="color:var(--text-muted)">{sign_display} {aspect}</span></span>')
        transit_summary = f'''<div style="margin-top:12px;padding:10px 14px;border-radius:8px;background:rgba(139,92,246,0.06);border:1px solid rgba(139,92,246,0.15)">
      <div style="font-size:11px;color:var(--accent-purple-light);margin-bottom:6px;font-weight:600">惑星トランジット</div>
      <div style="display:flex;flex-wrap:wrap;gap:4px">{transit_items}</div>
    </div>'''

    return f'''<section class="section" id="forecast-2026">
  {_section_quote('forecast')}
  {year_theme}
  {cards}
  {transit_summary}
  <div class="chart-wrap"><canvas id="chartOverlay" height="280"></canvas></div>
  {legend_html}
  {insight}
</section>'''

def _year_theme(cur_comb, cur9, cur12, has_reigou, p):
    """Generate a one-line year theme banner."""
    dm = p['four_pillars']['day_master']
    west = p['western_astrology']
    forecast_west = west.get('forecast_2026', '')

    if cur_comb and has_reigou:
        score = cur_comb['score']
        if score >= 70:
            theme = '攻めの年 — 種を蒔き、未来の収穫を設計する'
            color = 'var(--accent-green-light)'
        elif score >= 50:
            theme = '布石の年 — 足場を固め、次の飛躍を準備する'
            color = 'var(--accent-blue-light)'
        elif score >= 30:
            theme = '守りの年 — 基盤を強化し、内面を充実させる'
            color = '#facc15'
        else:
            theme = '充電の年 — 回復に専念し、嵐が過ぎるのを待つ'
            color = 'var(--accent-red-light)'
    elif cur9:
        if cur9['energy'] >= 70:
            theme = '攻めの年 — 積極的にチャンスを掴みにいく'
            color = 'var(--accent-green-light)'
        elif cur9['energy'] >= 40:
            theme = '布石の年 — 準備と基盤づくりに集中する'
            color = 'var(--accent-blue-light)'
        else:
            theme = '耐える年 — 守りを固め、次の好機を待つ'
            color = '#facc15'
    else:
        theme = '変化の年 — 新しい流れを受け入れる'
        color = '#a5b4fc'

    return f'''<div class="year-theme-banner">
    <div class="year-theme-label">2026年のテーマ</div>
    <div class="year-theme-text" style="color:{color}">{theme}</div>
  </div>'''

def _forecast_insight(cur9, cur12, cur_sub, cur_comb, has_reigou, nsk, rok, p=None):
    """Generate integrated forecast narrative from multiple systems."""
    parts = []

    # Nine Star Ki reading
    if cur9:
        parts.append(f'九星気学では<strong>{cur9["palace"]}</strong>（{cur9["theme"]}）に位置し、エネルギーは<strong>{cur9["energy"]}</strong>。')

    # Rokusei reading
    if cur12:
        satsukai = cur12.get('殺界')
        if satsukai:
            parts.append(f'六星占術のメイン星は<strong>{cur12["phase"]}</strong>（{satsukai}）で要注意期。')
        else:
            parts.append(f'六星占術のメイン星は<strong>{cur12["phase"]}</strong>（Energy {cur12["energy"]}）で好調期。')

    if has_reigou and cur_sub:
        sub_satsukai = cur_sub.get('殺界')
        if sub_satsukai:
            parts.append(f'一方、霊合サブ星は<strong>{cur_sub["phase"]}</strong>（{sub_satsukai}）で逆風。')
        else:
            parts.append(f'霊合サブ星も<strong>{cur_sub["phase"]}</strong>（Energy {cur_sub["energy"]}）で順調。')

    # Synthesis
    if cur_comb and has_reigou:
        score = cur_comb['score']
        label = cur_comb['label']
        # 霊合矛盾期（メイン高×サブ低 or メイン低×サブ高）の特別解説
        main_energy = cur12['energy'] if cur12 else 0
        sub_energy = cur_sub['energy'] if cur_sub else 0
        is_contradiction = abs(main_energy - sub_energy) >= 50
        if is_contradiction and cur12 and cur_sub:
            main_satsukai = cur12.get('殺界', '')
            sub_satsukai = cur_sub.get('殺界', '') if cur_sub else ''
            if main_energy > sub_energy:
                synthesis = (f'統合スコア<strong>{score}</strong>（{label}）。'
                             f'メイン星「{cur12["phase"]}」は好調を示す一方、サブ星「{cur_sub["phase"]}」（{sub_satsukai}）は強いブレーキを踏んでいます。'
                             f'この<strong>内なる矛盾</strong>は今年の特徴です。外から見えるチャンスに飛び込みながら、内側では立ち止まって再考する——'
                             f'その両方を<strong>同時にやること</strong>が今年の霊合星人としての最適解。')
            else:
                synthesis = (f'統合スコア<strong>{score}</strong>（{label}）。'
                             f'サブ星は好調を示しますが、メイン星「{cur12["phase"]}」（{main_satsukai or "要注意"}）が慎重を促しています。'
                             f'内側のエネルギーは動いていますが、表の行動は<strong>慎重な前進</strong>で。')
        elif score >= 70:
            synthesis = f'統合スコア<strong>{score}</strong>（{label}）— 複数の体系が好調を示しており、<strong>攻めの年</strong>。新しい挑戦や投資に適したタイミング。'
        elif score >= 50:
            synthesis = f'統合スコア<strong>{score}</strong>（{label}）— 体系間で評価が分かれており、<strong>慎重な前進</strong>が最適解。大きな決断は十分な分析の上で。'
        elif score >= 30:
            synthesis = f'統合スコア<strong>{score}</strong>（{label}）— 複数の体系で注意信号が出ており、<strong>守りを固める年</strong>。基盤の強化と内面の充実に集中。'
        else:
            synthesis = f'統合スコア<strong>{score}</strong>（{label}）— 全体系で低エネルギー期。<strong>無理をせず回復に専念</strong>する時期。大きな変更は避けるのが吉。'
        parts.append(synthesis)
    elif cur9 and cur12:
        avg = (cur9['energy'] + cur12['energy']) // 2
        # ダブルピーク年（両方80以上）の特別祝辞
        if cur9['energy'] >= 80 and cur12['energy'] >= 80:
            parts.append(f'両体系の平均エネルギーは<strong>{avg}</strong>——九星・六星の両方が「最良の年」を指しています。こうした<strong>ダブルピーク</strong>は稀有です。<strong>積極的に動ける年</strong>。')
        elif avg >= 60:
            parts.append(f'両体系の平均エネルギーは<strong>{avg}</strong>。全体的に好調で、<strong>積極的に動ける年</strong>。')
        else:
            parts.append(f'両体系の平均エネルギーは<strong>{avg}</strong>。<strong>地固めと準備</strong>に適した年。')

    # Peak year
    cycle9 = nsk.get('nine_year_cycle', [])
    combined = rok.get('reigou_combined', [])
    if combined:
        peak = max(combined, key=lambda c: c['score'])
        if peak.get('year') == 2026:
            parts.append(f'今年が<strong>統合スコア最高値</strong>（{peak["score"]}点）の年です。今この瞬間が、あなたの運気の頂点にあります。')
        else:
            parts.append(f'次のピークは<strong>{peak["year"]}年</strong>（統合スコア{peak["score"]}）。そこへ向けた布石を今から打つ。')
    elif cycle9:
        peak = max(cycle9, key=lambda c: c['energy'])
        if peak.get('year') == 2026:
            parts.append(f'今年が九星気学で<strong>最高エネルギー</strong>（{peak["palace"]}、{peak["energy"]}）の年です。')
        else:
            parts.append(f'九星気学のピークは<strong>{peak["year"]}年</strong>（{peak["palace"]}、Energy {peak["energy"]}）。')

    body = ''.join(parts)
    return f'''<div class="insight-box" style="margin-top:16px;border-left-color:var(--yellow)">
    <div class="insight-title" style="color:var(--yellow)">統合フォーキャスト</div>
    <p style="line-height:1.9;font-size:14px">{body}</p>
  </div>'''
