"""Dashboard section helpers: generated by refactor split."""
import json
from datetime import date as _date

ETO_PROFILES = {
    'Rat':     {'jp': '子', 'reading': 'ね',   'emoji': '🐭', 'title': '鼠年 — 観察の達人',
                'traits': ['先読み', '情報通', '倹約と蓄積'],
                'narrative': '場の空気を読む嗅覚と、小さな変化にいち早くお気づきになる力をお持ちです。表には出されませんが、誰よりも情報を集め、静かに先回りなさるタイプの方です。'},
    'Ox':      {'jp': '丑', 'reading': 'うし',  'emoji': '🐂', 'title': '丑年 — 地力の人',
                'traits': ['粘り強さ', '一貫性', '実直'],
                'narrative': '一歩ずつ確実に進まれる底力をお持ちです。派手さはなくとも、最後まで残られるのはあなた。信用が資産になっていく、堅実な生き方の方でいらっしゃいます。'},
    'Tiger':   {'jp': '寅', 'reading': 'とら',  'emoji': '🐅', 'title': '寅年 — 開拓者',
                'traits': ['決断力', '突破力', '情熱'],
                'narrative': '「とりあえずやってみる」の精神で道を開かれる方です。怖がる前に動けるのが、あなたの武器でいらっしゃいます。静かな場所より、未踏の現場で光を放たれます。'},
    'Rabbit':  {'jp': '卯', 'reading': 'う',   'emoji': '🐇', 'title': '卯年 — 調整の名手',
                'traits': ['気配り', '柔軟さ', '美意識'],
                'narrative': '角を立てずに物事を前に進められる、天性の才をお持ちです。敵をお作りにならず、味方をお増やしになります。繊細な感性で場を整えられる方でいらっしゃいます。'},
    'Dragon':  {'jp': '辰', 'reading': 'たつ', 'emoji': '🐉', 'title': '辰年 — 運を呼ぶ人',
                'traits': ['華', 'ビジョン', '瞬発力'],
                'narrative': '12支の中で唯一の架空の動物でいらっしゃいます。理想が高く、周囲を引き上げるお力をお持ちです。大きな夢を語られることが、そのまま仕事になっていかれる方です。'},
    'Snake':   {'jp': '巳', 'reading': 'み',   'emoji': '🐍', 'title': '巳年 — 知恵の人',
                'traits': ['洞察力', '集中力', '再生'],
                'narrative': '静かに本質を見抜く目をお持ちです。お話になりませんが、すべてをお分かりになっていらっしゃいます。脱皮のように、何度でもご自身を作り直せる再生の力も授かっています。'},
    'Horse':   {'jp': '午', 'reading': 'うま', 'emoji': '🐎', 'title': '午年 — 疾走者',
                'traits': ['行動力', '明朗', '独立心'],
                'narrative': '止まると不調になりやすく、動いて整うタイプの方でいらっしゃいます。人付き合いもオープンで、束縛よりも自由を選ばれる凛としたお姿がございます。'},
    'Goat':    {'jp': '未', 'reading': 'ひつじ', 'emoji': '🐐', 'title': '未年 — 共生の人',
                'traits': ['優しさ', '芸術性', '群れの中の個'],
                'narrative': 'お一人よりも、誰かとご一緒のほうがお力が出る方でいらっしゃいます。温かい空気をお作りになる天才で、美しいものへの感受性があなたの武器でございます。'},
    'Monkey':  {'jp': '申', 'reading': 'さる', 'emoji': '🐒', 'title': '申年 — 発想の人',
                'traits': ['機転', '器用', '遊び心'],
                'narrative': '状況が急変しても、即アドリブなさる頭の回転の速さをお持ちです。「楽しい」が基準で、笑いで場の雰囲気を変えていかれるお力がございます。'},
    'Rooster': {'jp': '酉', 'reading': 'とり', 'emoji': '🐓', 'title': '酉年 — 整える人',
                'traits': ['几帳面', '時間感覚', '表現力'],
                'narrative': '細部まできちんとご覧になる目をお持ちです。時間と段取りに強く、言葉やビジュアルでお伝えになる職人肌の方でいらっしゃいます。'},
    'Dog':     {'jp': '戌', 'reading': 'いぬ', 'emoji': '🐕', 'title': '戌年 — 信頼の人',
                'traits': ['誠実', '忠誠心', '責任感'],
                'narrative': '一度お信じになった相手には、最後まで尽くされる誠実さがございます。正義感が強く、筋をお通しになります。「この方なら任せられる」と言われる、信頼のお人柄です。'},
    'Pig':     {'jp': '亥', 'reading': 'い',   'emoji': '🐗', 'title': '亥年 — 直進の人',
                'traits': ['一途', '純粋さ', '推進力'],
                'narrative': '一度お決めになったら、脇目もふらず進まれる方です。裏表のない真っ直ぐさが、周囲からの信頼を呼びます。お好きなものへの集中力は、誰にも負けません。'},
}

def _eto_bt_rarity(animal, blood_type):
    # 日本赤十字社 公表値
    bt_pct = {'A': 38.1, 'B': 21.8, 'O': 30.7, 'AB': 9.4}.get(blood_type, 0)
    # 干支は約8.3%
    combined = round(bt_pct * 8.33 / 100, 1)
    return combined

def _eto_bt_narrative(animal, blood_type):
    """干支×血液型の掛け算で出る性格ナラティブ（24通り想定、代表的な組み合わせ）"""
    tmpl = {
        # 代表的なパターンだけ詳しく、残りは合成
        ('Dragon', 'AB'): '理想家（辰）× 合理と感性の両立（AB）。ビジョンを語りながら冷静に構造設計する稀なタイプ。リーダーとアナリストを同時にこなす。',
        ('Horse',  'A'):  '疾走する行動力（午）× 真面目で計画的（A）。「走りながら計画する」矛盾を両立。勢いと段取りが同居。',
        ('Rooster','AB'): '整える人（酉）× 二面性（AB）。細部への目と大局観を両方持つ。表面的な会話が苦手で、本質を突く言葉を選ぶ職人。',
        ('Rabbit', 'A'):  '調整力（卯）× 真面目（A）。周囲との衝突を避けながら計画を遂行する、「静かな実行者」。',
        ('Tiger',  'B'):  '突破力（寅）× 自由奔放（B）。抑えが効かず、走り出したら止まらない。型を壊して新しい道を作るタイプ。',
        ('Snake',  'AB'): '洞察の人（巳）× 合理×感性（AB）。口数は少ないが、発する一言が核心を突く。静かな戦略家。',
        ('Dog',    'O'):  '信頼の人（戌）× 人間好き（O）。仲間を守るためなら動く。チームの精神的な柱になるタイプ。',
        ('Ox',     'A'):  '地力（丑）× 真面目（A）。目立たないが結果を出す。長期戦で最後に勝つタイプ。',
        ('Monkey', 'B'):  '発想（申）× 自由奔放（B）。ひらめきと行動が直結。ルーティン業務は苦痛、クリエイティブな現場で輝く。',
        ('Goat',   'A'):  '共生（未）× 真面目（A）。人と人の間を繋ぎ、場を和ませながら着実に前進させる。サポート役として一流。',
        ('Pig',    'O'):  '直進（亥）× 人間好き（O）。情に厚く、一度仲間と認めたら裏切らない。シンプルで強い人格。',
        ('Rat',    'AB'): '観察力（子）× 二面性（AB）。人を読み、合理と感性を切り替えながら先手を打つ。情報の扱いが上手い。',
    }
    if (animal, blood_type) in tmpl:
        return tmpl[(animal, blood_type)]
    # 合成ベース: 干支trait + 血液型trait
    eto = ETO_PROFILES.get(animal, {})
    bt_hint = {
        'A':  '真面目さと計画性',
        'B':  '自由な発想と独自路線',
        'O':  '人間好きと現実主義',
        'AB': '合理と感性の両立',
    }.get(blood_type, '')
    traits = '・'.join(eto.get('traits', [])[:2])
    return f'{eto.get("title","").split("—")[-1].strip()}（{traits}）× {bt_hint}。干支と血液型のこの組み合わせ特有の矛盾と強みが、あなたの個性を形作っています。'

def _eto_section(p):
    """干支 × 血液型の Tier 1 カード。 日常語・具体的・シェアしたくなる。"""
    try:
        year_br = p['four_pillars']['year_pillar']['branch']
        animal = year_br.get('animal', '')
        eto = ETO_PROFILES.get(animal, {})
        bt = p.get('blood_type', {}).get('type', '')
        rarity = _eto_bt_rarity(animal, bt)
        narrative = _eto_bt_narrative(animal, bt)
        traits_html = ''.join(
            f'<span class="eto-trait">{t}</span>' for t in eto.get('traits', [])
        )
        return f'''
<div class="eto-hero">
  <div class="eto-emoji">{eto.get("emoji","")}</div>
  <div class="eto-name">
    <div class="eto-title">{eto.get("title","")}</div>
    <div class="eto-reading">{eto.get("jp","")}（{eto.get("reading","")}年）× {bt}型</div>
  </div>
  <div class="eto-rarity">
    <div class="eto-rarity-label">この組み合わせ</div>
    <div class="eto-rarity-value">日本人の約 {rarity}%</div>
  </div>
</div>
<div class="eto-narrative">
  <p>{eto.get("narrative","")}</p>
  <div class="eto-cross">
    <div class="eto-cross-label">干支 × 血液型 の掛け算</div>
    <div class="eto-cross-body">{narrative}</div>
  </div>
</div>
<div class="eto-traits-row">{traits_html}</div>
<div class="confidence-badge">この分析は、生年月日と血液型のみから導き出したものでございます。確度はおよそ 70% 程度。詳しい質問にお答えいただきますと、さらに鮮明に見えてまいります。</div>
'''
    except Exception as e:
        return f'<p style="color:var(--text-muted)">干支セクションの生成に失敗: {e}</p>'

def _integration_map(p):
    """5体系が示す『あなたの軸』を、どの体系がどちらを指すか明記して可視化。"""
    try:
        dm_element = p['four_pillars']['day_master'].get('element', '')
        dm_yy = p['four_pillars']['day_master'].get('yin_yang', '')
        ns_name = p['nine_star_ki']['year_star'].get('name', '')
        rok_name = p['rokusei']['main_star'].get('name', '')
        sun_sign = p['western_astrology']['sun_sign'].get('sign', '')
        sun_element = p['western_astrology']['sun_sign'].get('element', '')
        bt = p.get('blood_type', {}).get('type', '')

        # 体系ごとに「どちらか」を判定
        axes = []

        # 軸1: 内向 ⇄ 外向
        v1 = []
        v1.append(('四柱推命', '日主', '内向' if dm_yy == 'Yin' else '外向'))
        ns_inner = any(k in ns_name for k in ['一白水星', '二黒土星', '八白土星', '九紫火星'])
        v1.append(('九星気学', '本命星', '内向' if ns_inner else '外向'))
        rok_inner = any(k in rok_name for k in ['水星人', '土星人'])
        rok_outer = any(k in rok_name for k in ['火星人', '木星人', '天王星人'])
        if rok_inner or rok_outer:
            v1.append(('六星占術', '運命星', '内向' if rok_inner else '外向'))
        v1.append(('西洋占星術', '太陽星座', '内向' if sun_element in ['Water', 'Earth'] else '外向'))
        v1.append(('血液型', f'{bt}型', '内向' if bt in ['A', 'AB'] else '外向'))
        axes.append({
            'name': '内向 ⇄ 外向',
            'left': '内向',
            'right': '外向',
            'left_desc': '内なる世界で深く処理し、熟考と観察にこそ力をお持ちの御方でいらっしゃいます',
            'right_desc': '外の世界へ発信し、行動と交流の中にこそ力が湧き上がる御方でいらっしゃいます',
            'votes': v1,
        })

        # 軸2: 安定 ⇄ 変化
        v2 = []
        v2.append(('四柱推命', '日主', '安定' if dm_element in ['Earth', 'Metal'] else '変化'))
        ns_stable = any(k in ns_name for k in ['二黒土星', '五黄土星', '八白土星', '六白金星', '七赤金星'])
        v2.append(('九星気学', '本命星', '安定' if ns_stable else '変化'))
        rok_stable = any(k in rok_name for k in ['土星人', '金星人'])
        v2.append(('六星占術', '運命星', '安定' if rok_stable else '変化'))
        v2.append(('西洋占星術', '太陽星座', '安定' if sun_element == 'Earth' else '変化'))
        v2.append(('血液型', f'{bt}型', '安定' if bt == 'A' else '変化'))
        axes.append({
            'name': '安定 ⇄ 変化',
            'left': '安定',
            'right': '変化',
            'left_desc': '同じ場所で積み重ね、継続の中にこそ結果を見出す御方でございます',
            'right_desc': '新しい刺激や移動、挑戦の中でこそエネルギーが満ちてくる御方でございます',
            'votes': v2,
        })

        # 軸3: 思考 ⇄ 情動
        v3 = []
        v3.append(('四柱推命', '日主', '思考' if dm_element in ['Metal', 'Water'] else '情動'))
        ns_think = any(k in ns_name for k in ['一白水星', '六白金星', '七赤金星'])
        v3.append(('九星気学', '本命星', '思考' if ns_think else '情動'))
        rok_think = any(k in rok_name for k in ['水星人', '金星人'])
        v3.append(('六星占術', '運命星', '思考' if rok_think else '情動'))
        v3.append(('西洋占星術', '太陽星座', '思考' if sun_element in ['Air', 'Earth'] else '情動'))
        v3.append(('血液型', f'{bt}型', '思考' if bt == 'AB' else '情動'))
        axes.append({
            'name': '思考 ⇄ 情動',
            'left': '思考',
            'right': '情動',
            'left_desc': '論理と分析、言語化によって物事を明晰に捉えていらっしゃいます',
            'right_desc': '直感と感情、身体の声で物事を深く感じ取っていらっしゃいます',
            'votes': v3,
        })

        # Render
        axes_html = ''
        strong_agreements = []

        for a in axes:
            left_systems = [f'<span class="sys-chip sys-chip-left">{sys_name}（{part}）</span>' for sys_name, part, d in a['votes'] if d == a['left']]
            right_systems = [f'<span class="sys-chip sys-chip-right">{sys_name}（{part}）</span>' for sys_name, part, d in a['votes'] if d == a['right']]
            left_n = len(left_systems)
            right_n = len(right_systems)
            total = left_n + right_n

            if left_n > right_n:
                dominant_dir = a['left']
                dom_n = left_n
                minority_dir = a['right']
                min_n = right_n
                dom_desc = a['left_desc']
            else:
                dominant_dir = a['right']
                dom_n = right_n
                minority_dir = a['left']
                min_n = left_n
                dom_desc = a['right_desc']

            # 一致度ラベル
            if dom_n >= 4:
                verdict_badge = f'<span class="verdict-badge verdict-strong">強い合意: {dom_n}/{total} 体系が「{dominant_dir}」</span>'
                verdict_text = f'<strong>{dom_n} つの体系</strong>が揃って「<strong>{dominant_dir}</strong>」を指していらっしゃいます。{dom_desc}——というのが、あなたの軸でございます。'
                strong_agreements.append(f'「{dominant_dir}」軸で<strong>{dom_n}/{total}</strong>体系が一致')
            elif dom_n == 3:
                verdict_badge = f'<span class="verdict-badge verdict-lean">やや傾向あり: {dom_n}/{total} が「{dominant_dir}」</span>'
                verdict_text = f'<strong>{dom_n} つの体系</strong>が「<strong>{dominant_dir}</strong>」、<strong>{min_n} つ</strong>が「{minority_dir}」を指していらっしゃいます。どちらかと言えば{dominant_dir}寄りですが、場面によっては{minority_dir}のモードも顔をお出しになる、二面性のある方でいらっしゃいます。'
            else:
                verdict_badge = f'<span class="verdict-badge verdict-split">割れている: {left_n} : {right_n}</span>'
                verdict_text = f'<strong>体系間で意見が分かれる</strong>軸でございます。これは「どちらの状況にも対応できる柔軟性」の裏返しであり、あなたならではの固有の揺らぎと申せましょう。'

            outlier_line = ''
            if 1 <= min_n <= total - 1 and dom_n >= 3:
                outlier_systems_list = [f'<strong>{sys_name}</strong>' for sys_name, part, d in a['votes'] if d == minority_dir]
                outlier_line = f'<div class="axis-outlier"><span class="axis-outlier-label">ただし</span>{" と ".join(outlier_systems_list)} だけは「<strong>{minority_dir}</strong>」を指していらっしゃいます——これがあなたの隠れたお顔、固有の揺らぎポイントでございます。</div>'

            axes_html += f'''
<div class="axis-card">
  <div class="axis-card-header">
    <div class="axis-card-name">{a['name']}</div>
    {verdict_badge}
  </div>
  <div class="axis-card-verdict">{verdict_text}</div>
  <div class="axis-card-systems">
    <div class="axis-column axis-column-{('dominant' if left_n >= right_n else 'minority')}">
      <div class="axis-column-title">「{a['left']}」を指す（{left_n}体系）</div>
      <div class="axis-column-chips">{''.join(left_systems) if left_systems else '<span class="axis-empty">なし</span>'}</div>
    </div>
    <div class="axis-column axis-column-{('dominant' if right_n > left_n else 'minority')}">
      <div class="axis-column-title">「{a['right']}」を指す（{right_n}体系）</div>
      <div class="axis-column-chips">{''.join(right_systems) if right_systems else '<span class="axis-empty">なし</span>'}</div>
    </div>
  </div>
  {outlier_line}
</div>
'''

        consensus_html = ''
        if strong_agreements:
            items = ''.join(f'<li>{c}</li>' for c in strong_agreements)
            consensus_html = f'''
<div class="consensus-box">
  <div class="consensus-title">◇ 4つ以上の体系が口を揃えて言うこと</div>
  <ul>{items}</ul>
</div>'''
        else:
            consensus_html = '<div class="consensus-box subtle"><div class="consensus-title">どの軸も強い多数決にはなりませんでした</div><p>あなたは<strong>偏りの少ない「中道型」</strong>でいらっしゃいます。状況に応じて複数モードを自在にお使い分けになる、柔軟性のある方です。</p></div>'

        return f'''
<p class="section-intro">四柱推命・九星気学・六星占術・西洋占星術・血液型——起源の異なる 5 つの体系が、<strong>3 つの軸</strong>から「あなた」を独立に読み解いていらっしゃいます。<strong>多数決で見えてくる合意</strong>は高い確信度を示し、<strong>体系間で割れる軸</strong>はあなたならではの固有の揺らぎを示してまいります。</p>

<div class="axes-stack">{axes_html}</div>

{consensus_html}

<div class="confidence-badge">この分析は、生年月日と血液型のみから導き出しており、確度はおよそ 75% でございます。性格アンケート（Tier 2）にお進みいただくと、心理学データが加わり、各軸の確度が 90% を超えてまいります。</div>
'''
    except Exception as e:
        return f'<p style="color:var(--text-muted)">整合マップの生成に失敗: {e}</p>'

DM_STRENGTHS = {
    # (element, yin_yang): { strengths: [...], shadows: [...] }
    ('Wood', 'Yang'): {'strengths': ['果てなき向上心と成長の意欲', '鳥瞰するような大局観とリーダーシップ', '曲がることを知らない真っ直ぐな意志'],
                       'shadows':   ['視野が狭まり独善に陥りやすい', '急ぎすぎて細部を見落とす', '折れを知らず疲労を溜め込む']},
    ('Wood', 'Yin'):  {'strengths': ['場に溶け込む柔軟な対応力', '縁と調和を丁寧に紡ぐ力', 'しなやかで根気強い粘り'],
                       'shadows':   ['決めきれず優柔不断になりがち', '周囲に合わせすぎて自分を失う', '本音を言えず内に溜め込む']},
    ('Fire', 'Yang'): {'strengths': ['場を照らす明朗な発信力', '燃え盛る情熱と推進力', '人の心を動かす表現の力'],
                       'shadows':   ['炎のように燃え尽きやすい', '衝動で物事を判断してしまう', '自己評価が高くなりすぎる']},
    ('Fire', 'Yin'):  {'strengths': ['相手の心に寄り添う繊細な共感力', '本質を瞬時に見抜く直感', '静かに人を温める優しさ'],
                       'shadows':   ['他人の感情に引きずられやすい', '環境の波に敏感すぎる', '自己主張を控えすぎてしまう']},
    ('Earth', 'Yang'): {'strengths': ['揺るぎないどっしりとした安定感', '人から厚く信頼される実直さ', '大きく包み込む包容力'],
                        'shadows':   ['変化を受け入れるのに時間がかかる', '腰が重く動き出しが遅い', '一度決めたら融通が利かない']},
    ('Earth', 'Yin'):  {'strengths': ['地道に積み重ねる誠実な努力', '目配りが利く細やかな気配り', '人を長く支え続ける継続力'],
                        'shadows':   ['抱え込みすぎて疲弊しやすい', '完璧を求めすぎて動けなくなる', '自己犠牲の沼に入り込みやすい']},
    ('Metal', 'Yang'): {'strengths': ['迷わず切り込む決断力', '公平で揺るぎない判断力', '筋を最後まで通す一貫性'],
                        'shadows':   ['感情を切り捨て冷徹に見える', '情よりも原則を優先しすぎる', '自分の信念を曲げられない頑固さ']},
    ('Metal', 'Yin'):  {'strengths': ['磨かれた美意識と洗練された感覚', '言葉を丁寧に選ぶ繊細さ', '物事を整然と整える段取り力'],
                        'shadows':   ['基準が高く批判的になりやすい', '完璧を求めすぎる傾向', '細部への執着が尾を引く']},
    ('Water', 'Yang'): {'strengths': ['海のような広大な包容力', '状況に応じて変容する流動性', '時代を読む深い洞察と知恵'],
                        'shadows':   ['方向性が定まらず揺れやすい', '境界線が曖昧で流されやすい', '情に引っ張られる']},
    ('Water', 'Yin'):  {'strengths': ['静かに深く考え続ける思慮と忍耐', '表に出ない静かな影響力', '細部まで感じ取る繊細な洞察力'],
                        'shadows':   ['内向きになりすぎてこもりやすい', '秘密主義が強くなりやすい', '気分が沈んで浮上しにくい']},
}

NINE_STAR_BOOSTS = {
    '一白水星': '知恵と柔軟性',
    '二黒土星': '母なる支える力',
    '三碧木星': '行動力と発信力',
    '四緑木星': '縁と信用を育てる力',
    '五黄土星': '中心に立つ王の器',
    '六白金星': '公正な判断と理想',
    '七赤金星': '社交と言葉の力',
    '八白土星': '変化を乗り越える粘り',
    '九紫火星': '知性と美意識',
}

def _strengths_traps_section(p):
    """Gallup CliftonStrengths Shadow Side の構造をTier 1で再現。日主+本命星ベース。"""
    try:
        dm = p['four_pillars']['day_master']
        elem = dm.get('element', '')
        yy = dm.get('yin_yang', '')
        dm_char = dm.get('char', '')
        ns_name = p['nine_star_ki']['year_star'].get('name', '')
        rok_name = p['rokusei']['main_star'].get('name', '')
        reigou = p['rokusei'].get('reigou', False)
        bt = p.get('blood_type', {}).get('type', '')

        data = DM_STRENGTHS.get((elem, yy), {})
        strengths = data.get('strengths', [])
        shadows = data.get('shadows', [])
        ns_boost = NINE_STAR_BOOSTS.get(ns_name, '')

        # 強み/弱みのペアを並列で
        pair_html = ''
        for i, (s, t) in enumerate(zip(strengths, shadows), 1):
            pair_html += f'''
<div class="strength-pair">
  <div class="strength-side">
    <div class="pair-label-pos">強み {i}</div>
    <div class="pair-body">{s}</div>
  </div>
  <div class="pair-connector">⇄</div>
  <div class="shadow-side">
    <div class="pair-label-neg">裏返しの罠</div>
    <div class="pair-body">{t}</div>
  </div>
</div>
'''

        # 本命星ブースト + 霊合星人補足
        extras = f'<p class="strength-extra"><strong>{ns_name}</strong>の「{ns_boost}」が、これらの強みを社会へお出しになる舞台装置となっていらっしゃいます。</p>' if ns_boost else ''
        if reigou:
            extras += '<p class="strength-extra"><strong>霊合星人</strong>という希少体質（人口15%）をお持ちのため、この強みと罠の振れ幅が一般の2倍と言われております。好調時は抜きん出て、不調時は深く沈む——そんな特徴がございます。</p>'
        elif rok_name:
            extras += f'<p class="strength-extra">六星占術の<strong>{rok_name}</strong>が、この強みを人生の時期に合わせて開花させてくださいます。</p>'

        return f'''
<p class="section-intro">「強み」と「罠」は、表裏一体のもの。Gallup CliftonStrengths の Shadow Side 理論を、あなたの<strong>生年月日＋血液型</strong>に適用いたしました。強みが暴走した時の落とし穴を先に知っておかれることが、賢明な自分運用への第一歩でございます。</p>
<div class="strengths-traps-grid">{pair_html}</div>
{extras}
<div class="confidence-badge">この分析は、生年月日と血液型のみから導き出したもので、確度はおよそ 70% でございます。性格アンケート（Tier 2）にお答えいただくと、あなた個人の「強み序列」と「暴走しやすい順」が見えてまいります。</div>
'''
    except Exception as e:
        return f'<p style="color:var(--text-muted)">強み/罠セクションの生成に失敗: {e}</p>'

BT_GIST = {
    'A':  '几帳面と計画性',
    'B':  '自由な発想と独立心',
    'O':  '人間好きと現実主義',
    'AB': '合理と感性の両立',
}

DM_GIST = {
    '甲': '天へ真っ直ぐ伸びる大樹の推進力',
    '乙': '蔓のように絡みつく柔の粘り強さ',
    '丙': '燦々と輝く太陽の明朗な発信力',
    '丁': '揺れるろうそくの炎の繊細な照射力',
    '戊': '泰然とした大山の安定と包容力',
    '己': '実りを育む田畑の深い器',
    '庚': '研ぎ澄まされた鋼刃の決断の切れ味',
    '辛': '磨き上げられた宝玉の美意識と洗練',
    '壬': '万物を抱く大河の包容と流動',
    '癸': '大地に染み渡る雨露の浸透する知恵',
}

ETO_GIST = {
    'Rat':'機を読む観察の達人','Ox':'地道に積む地力の人','Tiger':'無畏の開拓者','Rabbit':'縁を結ぶ調整の名手',
    'Dragon':'天運を呼び込む理想家','Snake':'深謀を秘める知恵者','Horse':'自由に駆ける疾走者','Goat':'和を紡ぐ共生の人',
    'Monkey':'奇才を宿す発想の人','Rooster':'美しく整える人','Dog':'義を貫く信頼の人','Pig':'実直に突き進む人',
}

def _rarity_stats_bar(p):
    """血液型×干支×日主の組み合わせを Aha モーメント化:
    - 全480通り中の事実ベース分類
    - 実生活スケール換算（大学学年・大企業・主要駅・中堅都市）
    - 3体系シンセシス1行"""
    try:
        year_br = p['four_pillars']['year_pillar']['branch']
        animal = year_br.get('animal', '')
        animal_ja = {'Rat':'子','Ox':'丑','Tiger':'寅','Rabbit':'卯','Dragon':'辰','Snake':'巳',
                     'Horse':'午','Goat':'未','Monkey':'申','Rooster':'酉','Dog':'戌','Pig':'亥'}.get(animal, animal)
        bt = p.get('blood_type', {}).get('type', '')
        dm_char = p['four_pillars']['day_master'].get('char', '')
        reigou = p['rokusei'].get('reigou', False)
        sun_sign_en = p['western_astrology']['sun_sign'].get('sign', '')
        sun_symbol = p['western_astrology']['sun_sign'].get('symbol', '')
        sun_sign_ja = {'Aries':'牡羊座','Taurus':'牡牛座','Gemini':'双子座','Cancer':'蟹座',
                       'Leo':'獅子座','Virgo':'乙女座','Libra':'天秤座','Scorpio':'蠍座',
                       'Sagittarius':'射手座','Capricorn':'山羊座','Aquarius':'水瓶座','Pisces':'魚座'}.get(sun_sign_en, sun_sign_en)

        # 4 体系を掛け合わせた総組み合わせ数（血液型 × 干支 × 日主 × 太陽星座）
        bt_kinds, eto_kinds, dm_kinds, sun_kinds = 4, 12, 10, 12
        total_patterns = bt_kinds * eto_kinds * dm_kinds * sun_kinds  # = 5,760

        # 血液型分布: 日本赤十字社 公表値
        # 出典: https://www.jrc.or.jp/donation/about/type/
        bt_pct_jp = {'A': 38.1, 'B': 21.8, 'O': 30.7, 'AB': 9.4}.get(bt, 9.4)
        # 血液型分布: 世界平均 (American Red Cross / Stanford Blood Center 推定)
        # 出典: https://www.redcrossblood.org/donate-blood/blood-types.html
        bt_pct_world = {'A': 31.0, 'B': 16.0, 'O': 46.0, 'AB': 7.0}.get(bt, 7.0)

        jp_fraction = (bt_pct_jp / 100) * (1/12) * (1/10) * (1/12)
        world_fraction = (bt_pct_world / 100) * (1/12) * (1/10) * (1/12)
        if jp_fraction <= 0:
            return '<p style="color:var(--text-muted)">パターン分類の生成に失敗</p>'

        one_in_n = int(round(1 / jp_fraction))
        world_one_in_n = int(round(1 / world_fraction))
        combined_fraction = jp_fraction  # backward-compat for other references below

        # 実生活スケール換算セクションは 2026-04-16 にユーザー判断で削除 (出典不正確・意味不明瞭)
        # 旧: 新宿駅・政令指定都市・東京都などへの人口換算。当時の参考値は過小/不正確だった
        # 代替: Hero の 日本/世界 dual-geo 表示で十分な Aha moment が成立しているため不要

        # 4体系シンセシス1行
        bt_gist = BT_GIST.get(bt, '')
        eto_gist = ETO_GIST.get(animal, '')
        dm_gist = DM_GIST.get(dm_char, '')
        sun_gist_map = {
            'Aries':'先陣を切る開拓者','Taurus':'五感と安定を愛する人','Gemini':'情報と言葉の達人',
            'Cancer':'情と家族の包容力','Leo':'中心に立つ華やかさ','Virgo':'細部を整える職人肌',
            'Libra':'バランスと調和の人','Scorpio':'本質に迫る深掘り型','Sagittarius':'自由と哲学の冒険家',
            'Capricorn':'長期戦の実績家','Aquarius':'独自視点の革新者','Pisces':'感受性豊かな夢想家',
        }
        sun_gist = sun_gist_map.get(sun_sign_en, '')
        synthesis = ''
        if bt_gist and eto_gist and dm_gist and sun_gist:
            dm_term = _glossary_tooltip('日主', f'{dm_char}日主')
            synthesis = f'<strong>{bt_gist}</strong>（{bt}型） × <strong>{eto_gist}</strong>（{animal_ja}年） × <strong>{dm_gist}</strong>（{dm_term}） × <strong>{sun_gist}</strong>（{sun_symbol} {sun_sign_ja}）——この 4 つが重なり合って生まれる、あなたならではの貴重なブレンドでございます。'

        reigou_note = ''
        if reigou:
            reigou_note = '<div class="rarity-item rarity-item-accent"><div class="rarity-value">霊合</div><div class="rarity-label">霊合星人<br>（15%・稀少体質）</div></div>'

        # 日本の総人口: 総務省統計局 人口推計（2026年4月概算値）
        # 出典: https://www.stat.go.jp/data/jinsui/
        JAPAN_POP = 123_480_000
        japan_count = int(round(JAPAN_POP * jp_fraction))
        # 世界総人口: 国連 World Population Prospects 2024 Revision（2026年推計）
        # 出典: https://population.un.org/wpp/
        WORLD_POP = 8_150_000_000
        world_count = int(round(WORLD_POP * world_fraction))

        # 出現率に応じた文脈ラベル
        if one_in_n >= 10000:
            context_label = '極めて稀少な組み合わせ'
        elif one_in_n >= 3000:
            context_label = '珍しい組み合わせ'
        elif one_in_n >= 1000:
            context_label = '少数派の組み合わせ'
        else:
            context_label = '比較的一般的な組み合わせ'

        dm_tip = _glossary_tooltip('日主')
        eto_tip = _glossary_tooltip('干支')
        sun_tip = _glossary_tooltip('太陽星座')

        return f'''
<div class="rarity-bar">
  <span class="rarity-badge-top">組み合わせ分類 × 日本人分布</span>
  <div class="rarity-dual-geo">
    <div class="geo-stat geo-jp">
      <div class="geo-label">🇯🇵 日本</div>
      <div class="geo-main"><span class="geo-n">{one_in_n:,}</span> 人に 1 人</div>
      <div class="geo-count">= 約 <strong>{japan_count:,}</strong> 人</div>
    </div>
    <div class="geo-stat geo-world">
      <div class="geo-label">🌏 世界</div>
      <div class="geo-main"><span class="geo-n">{world_one_in_n:,}</span> 人に 1 人</div>
      <div class="geo-count">= 約 <strong>{world_count:,}</strong> 人</div>
    </div>
  </div>
  <div class="rarity-context-note">{context_label}</div>

  <div class="rarity-synthesis">{synthesis}</div>

  <div class="rarity-breakdown">
    <div class="rarity-item"><div class="rarity-value">{bt}</div><div class="rarity-label">{bt}型<br><span style="font-size:9px;color:var(--text-muted)">血液型（4種中）</span></div></div>
    <div class="rarity-item"><div class="rarity-value">{animal_ja}</div><div class="rarity-label">{animal_ja}年<br><span style="font-size:9px;color:var(--text-muted)">{eto_tip}（12種中）</span></div></div>
    <div class="rarity-item"><div class="rarity-value">{dm_char}</div><div class="rarity-label">{dm_char}{dm_tip}<br><span style="font-size:9px;color:var(--text-muted)">生日の気質（10種中）</span></div></div>
    <div class="rarity-item"><div class="rarity-value" style="font-size:18px">{sun_symbol}</div><div class="rarity-label">{sun_sign_ja}<br><span style="font-size:9px;color:var(--text-muted)">{sun_tip}（12星座中）</span></div></div>
    {reigou_note}
  </div>

  <!-- 旧: rarity-scale セクションは 2026-04-16 にユーザー判断で削除 (出典不正確・意味不明瞭) -->
  <!-- 代替: Hero の 日本/世界 dual-geo 表示で十分な Aha moment が成立している -->


  <div class="rarity-sources">
    <div class="rarity-sources-title">📊 算出根拠</div>
    <ul>
      <li>血液型分布（日本）: <a href="https://www.jrc.or.jp/donation/about/type/" target="_blank" rel="noopener">日本赤十字社 血液事業本部</a> — A 38.1% / O 30.7% / B 21.8% / AB 9.4%</li>
      <li>血液型分布（世界）: <a href="https://www.redcrossblood.org/donate-blood/blood-types.html" target="_blank" rel="noopener">American Red Cross / Stanford Blood Center</a> — O 46% / A 31% / B 16% / AB 7%</li>
      <li>日本の総人口: <a href="https://www.stat.go.jp/data/jinsui/" target="_blank" rel="noopener">総務省統計局 人口推計</a>（2026年4月概算値 約 1億2,348万人）</li>
      <li>世界の総人口: <a href="https://population.un.org/wpp/" target="_blank" rel="noopener">国連 World Population Prospects 2024</a>（2026年推計 約 81.5億人）</li>
      <li>干支 12種 / 日主 10種 / 太陽星座 12種は、暦上の等分布を仮定</li>
      <li>4 要素は互いに独立と仮定して同時発生確率を算出</li>
    </ul>
  </div>
</div>
'''
    except Exception as e:
        return f'<p style="color:var(--text-muted)">パターン分類の生成に失敗: {e}</p>'

def _cross_analysis(p):
    """Cross Analysis — 強み×運気の掛け合わせ insight boxes."""
    sf_top5 = p.get('strengths_finder', {}).get('top5', [])
    pers = p.get('personality', {})
    ennea = pers.get('enneagram', {})
    hsp = pers.get('hsp', {})
    adhd = pers.get('adhd', {})
    dm = p['four_pillars']['day_master']
    ys = p['nine_star_ki']['year_star']
    west = p['western_astrology']['sun_sign']
    bt = p['blood_type']
    rok = p['rokusei']

    # Build insight boxes from profile data
    boxes = []

    # 1. Empathy × Sensitivity × Enneagram
    if sf_top5 and ennea and hsp:
        etype = ennea.get('type', '')
        hsp_score = hsp.get('score', '')
        sens_label = HSP_LABELS.get(hsp_score, hsp_score)
        boxes.append({
            'title': f'Empathy（共感性）× 繊細さ × エニアグラム{etype}',
            'text': f'強み診断1位の共感性と{sens_label}な感受性、'
                    f'エニアグラムType {etype}の独自性追求が共鳴。'
                    f'「人の感情を深く理解し、独自の視点で表現する力」を形成する。'
                    f'この組み合わせはサービス設計においてユーザーの痛みを自分事として感じられるPMFの源泉。',
        })

    # 2. Intellection × Focus Pattern × Day Master
    if len(sf_top5) >= 2 and adhd:
        focus_label = ADHD_LABELS.get(adhd.get('tendency', ''), '')
        boxes.append({
            'title': f'Intellection（内省）× 集中パターン × {dm["char"]}火（陰火）',
            'text': f'深い思考力（Intellection 2位）× {focus_label}の集中特性 × '
                    f'{dm["char"]}火（ロウソクの炎）。'
                    f'環境を整えれば安定して燃え続けるが、刺激に弱い。'
                    f'自動化で雑務を排除し、思考に没頭できる環境を作ることが最重要。',
        })

    # 3. Deliberative × Blood Type × Western
    q_ja = {'Fixed':'不動宮','Cardinal':'活動宮','Mutable':'柔軟宮'}.get(west['quality'], west['quality'])
    if len(sf_top5) >= 3:
        boxes.append({
            'title': f'Deliberative（慎重さ）× {bt["type"]}型 × {west["sign"]}（{q_ja}）',
            'text': f'慎重さ（3位）× {bt["type"]}型の合理的分析 × '
                    f'{west["sign"]}の{q_ja}。'
                    f'三重の慎重さは深い分析に基づく確実な意思決定を可能にする。'
                    f'一方で「分析麻痺」に陥りやすく、行動が遅れるリスクもある。',
        })

    # 4. Connectedness × Nine Star × Current Year
    cur9 = next((c for c in p['nine_star_ki'].get('nine_year_cycle', []) if c.get('current')), None)
    if len(sf_top5) >= 4 and cur9:
        boxes.append({
            'title': f'Connectedness（運命思考）× {ys["name"]} × {cur9["palace"]}2026',
            'text': f'全てを繋げて見る直感力（4位）× {ys["name"]}の社交力と言葉の力。'
                    f'2026年の{cur9["palace"]}は「{cur9["theme"]}」の年 — '
                    f'点在するプロジェクト群を繋ぎ、エコシステムを設計するのに最適なタイミング。',
        })

    # 5. Maximizer × Systems
    if len(sf_top5) >= 5:
        boxes.append({
            'title': 'Maximizer（最上志向）× 3S原則 × 7つの習慣',
            'text': '「良い→最高」の追求（5位）がOSそのもの。'
                    '3S（Simple, Scalable, Sustainable）でフィルターし、'
                    '第II領域（重要×非緊急）に集中投資する。'
                    '「もっと良くできないか？」が止まらない性質は自動化・最適化の原動力。',
        })

    if not boxes:
        return ''

    # Build HTML
    grid_items = ''
    for b in boxes:
        grid_items += f'''<div class="insight-box">
      <div class="insight-title">{b["title"]}</div>
      <p>{b["text"]}</p>
    </div>'''

    return f'''<section class="section" id="cross">
  {_section_quote('cross')}
  <div class="grid">{grid_items}</div>
</section>'''

def _cross_reference_insight(p):
    """4-5体系の交差点から、単一体系では見えないインサイトを言語化。
    - 強度の一致（複数体系が同じ結論） → 確信度の高い自己像
    - 矛盾点（体系によって違う結論） → あなたの固有性・ユニークな揺らぎ"""
    try:
        dm = p['four_pillars']['day_master']
        dm_char = dm.get('char', '')
        dm_element = dm.get('element', '')
        dm_yy = dm.get('yin_yang', '')
        ns_name = p['nine_star_ki']['year_star'].get('name', '')
        rok_name = p['rokusei']['main_star'].get('name', '')
        reigou = p['rokusei'].get('reigou', False)
        sun_sign = p['western_astrology']['sun_sign'].get('sign', '')
        sun_element = p['western_astrology']['sun_sign'].get('element', '')  # Fire/Earth/Air/Water
        animal = p['four_pillars']['year_pillar']['branch'].get('animal', '')
        animal_ja = {'Rat':'子','Ox':'丑','Tiger':'寅','Rabbit':'卯','Dragon':'辰','Snake':'巳',
                     'Horse':'午','Goat':'未','Monkey':'申','Rooster':'酉','Dog':'戌','Pig':'亥'}.get(animal, animal)
        bt = p.get('blood_type', {}).get('type', '')
        missing = p['four_pillars'].get('missing_elements', [])

        # === 発見1: 多体系が同じ方向を指すポイント（強い合意） ===
        agreements = []

        # 火の要素が重なるか (太陽・情熱・行動)
        fire_count = 0
        if dm_element == 'Fire': fire_count += 1
        if sun_element == 'Fire': fire_count += 1
        if '火' in ns_name or '九紫火星' in ns_name: fire_count += 1
        if rok_name in ['火星人']: fire_count += 1
        if fire_count >= 2:
            agreements.append({
                'title': '火の性質が複数体系で重なる',
                'bodies': f'四柱推命・西洋占星術・九星気学・六星占術のうち <strong>{fire_count} 体系</strong>が「火」要素を共有。',
                'insight': '情熱・発信力・明るさが、あなたの軸となっていらっしゃいます。人前に立つ場面で、自然と光が当たるタイプの方でございます。',
            })

        # 水の要素（思考・内省・流動）
        water_count = 0
        if dm_element == 'Water': water_count += 1
        if sun_element == 'Water': water_count += 1
        if '水' in ns_name: water_count += 1
        if rok_name == '水星人': water_count += 1
        if water_count >= 2:
            agreements.append({
                'title': '水の性質が複数体系で重なる',
                'bodies': f'思考と流動性の「水」が <strong>{water_count} 体系</strong>で共有。',
                'insight': '考える時間の長さと、流れを読む力が、あなたの資質でいらっしゃいます。即断即決よりも熟慮型。静かな環境でこそ、最大のお力を発揮なさるタイプです。',
            })

        # 土の要素（安定・堅実・継続）
        earth_count = 0
        if dm_element == 'Earth': earth_count += 1
        if sun_element == 'Earth': earth_count += 1
        if '土星' in ns_name: earth_count += 1
        if rok_name == '土星人': earth_count += 1
        if earth_count >= 2:
            agreements.append({
                'title': '土の性質が複数体系で重なる',
                'bodies': f'安定と堅実の「土」が <strong>{earth_count} 体系</strong>で共有。',
                'insight': '周囲が揺れても自分は動かない、芯の強さをお持ちです。長距離走型で、急がば回れを自然体で実践なさることができる方でいらっしゃいます。',
            })

        # 風/金の要素（知性・言葉・社交）
        metal_air_count = 0
        if dm_element == 'Metal': metal_air_count += 1
        if sun_element == 'Air': metal_air_count += 1
        if '金星' in ns_name or '六白金星' in ns_name or '七赤金星' in ns_name: metal_air_count += 1
        if rok_name == '金星人': metal_air_count += 1
        if metal_air_count >= 2:
            agreements.append({
                'title': '金/風の性質が複数体系で重なる',
                'bodies': f'知性と社交の「金／風」が <strong>{metal_air_count} 体系</strong>で共有。',
                'insight': '言葉の切れ味と論理構成が、あなたの武器でいらっしゃいます。アイデアを他の方に伝えるフェーズで、最もお輝きになります。',
            })

        # 木（成長・向上・推進）
        wood_count = 0
        if dm_element == 'Wood': wood_count += 1
        if '木星' in ns_name or '三碧木星' in ns_name or '四緑木星' in ns_name: wood_count += 1
        if rok_name == '木星人': wood_count += 1
        if wood_count >= 2:
            agreements.append({
                'title': '木の性質が複数体系で重なる',
                'bodies': f'成長と伸長の「木」が <strong>{wood_count} 体系</strong>で共有。',
                'insight': '止まると不調になりやすく、動きながら整うタイプでいらっしゃいます。チャレンジと拡張が、あなたを健やかに保つ源でございます。',
            })

        # 陰陽のバランス (Yin系/Yang系 の集中)
        yin_count = 0
        yang_count = 0
        if dm_yy == 'Yin': yin_count += 1
        else: yang_count += 1
        if sun_element in ['Water', 'Earth']: yin_count += 1
        else: yang_count += 1
        if bt in ['A', 'AB']: yin_count += 1
        else: yang_count += 1
        if yin_count >= 3:
            agreements.append({
                'title': '陰の性質が 3 体系以上で一致',
                'bodies': '四柱推命・西洋・血液型がすべて「陰」寄り。',
                'insight': '外向的な場面でも、内側では観察・処理・熟考が静かに走っている、二層構造の方でいらっしゃいます。「静かに見える方ほど深く考えていらっしゃる」典型のお人柄です。',
            })
        if yang_count >= 3:
            agreements.append({
                'title': '陽の性質が 3 体系以上で一致',
                'bodies': '四柱推命・西洋・血液型がすべて「陽」寄り。',
                'insight': '外への発信・行動・表現が、あなたにとって自然なお振る舞いでございます。じっとなさっていると調子を崩しやすいので、動いて整えていかれる運用が最適です。',
            })

        # === 発見3: 普遍的な二層構造（誰にでも必ず言える体系交差） ===
        layered = []
        # 本命星 × 日主（社会の顔 × 内面の顔）
        if ns_name and dm_char:
            ns_short = ns_name
            layered.append({
                'title': f'本命星「{ns_short}」× 日主「{dm_char}」の二層構造',
                'bodies': f'九星気学の<strong>{ns_short}</strong>が社会に出る時の顔。四柱推命の<strong>{dm_char}</strong>が内側で動いている本体。',
                'insight': f'外から見えるあなたと、内側で動いているあなたは少し違っていらっしゃいます。この <strong>「外の自分 × 内の自分」のギャップ</strong>を自覚なさることが、疲れにくい生き方への第一歩でございます。',
            })
        # 干支 × 日主（直感キャラ × 本質）
        if animal_ja and dm_char:
            layered.append({
                'title': f'{animal_ja}年（{ETO_GIST.get(animal,"")}）× {dm_char}日主（{DM_GIST.get(dm_char,"日主")}）',
                'bodies': f'干支が示す<strong>生まれ持った気質</strong>と、日主が示す<strong>日々の判断の軸</strong>が重なる場所。',
                'insight': f'周囲に対しては{ETO_GIST.get(animal, "その型")}として振る舞っていらっしゃりながら、重要な判断では{DM_GIST.get(dm_char, "日主の特性")}が働いていらっしゃいます。この使い分けが無意識にできていらっしゃるなら、それはあなたの強みの核と申せましょう。',
            })
        # 血液型 × 欠けている元素（補完すべき方向）
        if bt and missing:
            miss_str = '・'.join(missing)
            miss_action = {
                '木':'挑戦と拡張',
                '火':'情熱と発信',
                '土':'腰を据えた継続',
                '金':'決断と切り捨て',
                '水':'流動性と休息',
            }
            actions = '、'.join(miss_action.get(m, '') for m in missing if m in miss_action)
            layered.append({
                'title': f'{bt}型の基礎 × 欠けている五行（{miss_str}）',
                'bodies': f'{bt}型の<strong>{BT_GIST.get(bt,"")}</strong>をベースに、五行では<strong>{miss_str}</strong>が不足。',
                'insight': f'自然体ではうまく発揮されない「{actions}」を、意識的に予定へお入れになる運用が効果的でございます。欠けた要素は「弱点」ではなく、「意識なさると良い補完ポイント」とお考えください。',
            })
        # 運命星 × 2026年フェーズ（今の時期の読み）
        try:
            cycle12 = p['rokusei'].get('twelve_year_cycle', [])
            cur_phase = next((c for c in cycle12 if c.get('current')), None)
            if cur_phase and rok_name:
                phase_name = cur_phase.get('phase', '')
                phase_energy = cur_phase.get('energy', 0)
                satsukai = cur_phase.get('殺界') or ''
                phase_japanese = {
                    '種子':'種をまく時期','緑生':'芽吹きの時期','立花':'花開く時期',
                    '健弱':'少し踏ん張る時期','達成':'実りの時期','乱気':'揺らぎの時期',
                    '再会':'縁が戻る時期','財成':'財が育つ時期','安定':'落ち着く時期',
                    '陰影':'陰に入る時期','停止':'立ち止まる時期','減退':'力を蓄える時期',
                }
                phase_ja = phase_japanese.get(phase_name, phase_name)
                phase_note = f'（{satsukai}）' if satsukai else ''
                layered.append({
                    'title': f'{rok_name}の 2026 年は「{phase_name}」{phase_note}',
                    'bodies': f'12年周期の六星占術で、あなたは今「{phase_ja}」。エネルギー指数 <strong>{phase_energy}/100</strong>。',
                    'insight': f'<strong>この1年のお立ち位置</strong>を知っておかれますと、無理に頑張られるべき時か、静かに整えていかれる時かが判断しやすくなります。九星気学の今年の運気と合わせて読まれると、さらに立体的にお見えになってまいります。',
                })
        except Exception:
            pass

        # === 発見2: 体系間の矛盾・揺らぎ ===
        tensions = []
        # 内向日主 × 外向血液型
        if dm_yy == 'Yin' and bt in ['B', 'O']:
            tensions.append({
                'title': '内なる繊細さ × 外向きな振る舞い',
                'bodies': f'日主「{dm_char}」（陰）は内省型。血液型「{bt}」（{BT_GIST.get(bt,"")}）は外向型。',
                'insight': '外では明るく社交的でいらっしゃるのに、お一人になると急に静かになる——そんなギャップをお持ちです。周囲には「摑みどころがない」と映るかもしれませんが、ご本人にとっては自然なモードの切り替えなのでございます。',
            })
        if dm_yy == 'Yang' and bt == 'A':
            tensions.append({
                'title': '推進力 × 几帳面さ',
                'bodies': f'日主「{dm_char}」（陽）は勢い。血液型「{bt}」は計画性。',
                'insight': '「走りながら細かい段取りを詰める」という、稀有な矛盾をお持ちです。スピードと精度を同時にお出しになれますが、両立に疲れやすくもありますので、定期的に片方をお休ませになると良いでしょう。',
            })
        # 霊合星人（二重性そのもの）
        if reigou:
            tensions.append({
                'title': '霊合星人という「二つの顔」',
                'bodies': f'六星占術で <strong>{rok_name}</strong> にサブ星を持つ霊合星人（人口15%）。',
                'insight': '状況によって全く違う人格モードが立ち上がるのが、霊合星人のあなたの特徴でいらっしゃいます。周囲は「あの時と印象が違っていた」と感じるかもしれませんが、ご本人にとってはどちらも本物の自分でいらっしゃるのです。使い分けを自覚なさると、場面ごとに最適なご自身をお選びいただけます。',
            })
        # 欠けている元素と重なる軸（自覚すべき盲点）
        if '金' in missing and metal_air_count == 0:
            tensions.append({
                'title': '決断力（金）が全体系で弱い',
                'bodies': '四柱推命で金が欠落、他体系でも「金/風」の補強がない。',
                'insight': '決める・切る・引くといった「止める力」が、構造的に少し不足していらっしゃる傾向があります。意識して期限をお設けになる、あるいは第三者に決定をお委ねになる仕組みをお作りになると、自然に補えるでしょう。',
            })
        if '水' in missing and water_count == 0:
            tensions.append({
                'title': '柔軟性（水）が全体系で弱い',
                'bodies': '四柱推命で水が欠落、他体系でも「水」の補強がない。',
                'insight': '状況の変化をお受け入れになって自分を組み替える力が、構造的に少し不足していらっしゃる傾向があります。急なご予定変更で疲弊しやすいので、「想定外」をあらかじめバッファにお入れになる設計が効いてまいります。',
            })
        if '火' in missing and fire_count == 0:
            tensions.append({
                'title': '情熱（火）が全体系で弱い',
                'bodies': '四柱推命で火が欠落、他体系でも「火」の補強がない。',
                'insight': '自己発火なさるのがやや苦手で、外から刺激をお受けになって着火するタイプでいらっしゃいます。インスピレーション源（人・場・コンテンツ）を意識的に摂取なさる運用が、あなたには向いています。',
            })

        # Render
        agreement_html = ''
        # まず「多体系の元素合意」、次に普遍的な「二層構造」を混ぜる
        combined_insights = agreements + layered
        if combined_insights:
            for a in combined_insights[:4]:  # 最大4件
                agreement_html += f'''
<div class="cross-card cross-agree">
  <div class="cross-card-header">
    <span class="cross-marker-agree">交差点</span>
    <div class="cross-card-title">{a['title']}</div>
  </div>
  <div class="cross-card-body">{a['bodies']}</div>
  <div class="cross-card-insight"><strong>だから、</strong>{a['insight']}</div>
</div>
'''
        else:
            agreement_html = '<p class="cross-empty">強い多数決の軸は見つかりませんでした。あなたは「どの側にも偏らない中道型」で、逆に言えば複数モードを柔軟に使える希少な人です。</p>'

        tension_html = ''
        if tensions:
            for t in tensions[:3]:
                tension_html += f'''
<div class="cross-card cross-tension">
  <div class="cross-card-header">
    <span class="cross-marker-tension">揺らぎ</span>
    <div class="cross-card-title">{t['title']}</div>
  </div>
  <div class="cross-card-body">{t['bodies']}</div>
  <div class="cross-card-insight"><strong>つまり、</strong>{t['insight']}</div>
</div>
'''

        return f'''
<p class="section-intro">単一の占術だけでは見えてこない、<strong>体系を跨いだ共通点と矛盾点</strong>を抽出いたしました。複数の千年単位の体系が同じ方向を指している時、それは偶然ではないと申せましょう。逆に、体系間で結論が割れる軸こそが、あなたならではの<strong>固有の揺らぎ</strong>でございます。</p>

<div class="cross-section">
  <div class="cross-section-label cross-section-label-agree">
    <span class="cross-label-emoji">◇</span>
    複数体系が口を揃えて申し上げること — 高い確信度で見えてくる自己像
  </div>
  <div class="cross-grid">{agreement_html}</div>
</div>

{f'''<div class="cross-section">
  <div class="cross-section-label cross-section-label-tension">
    <span class="cross-label-emoji">⚖</span>
    体系間で揺らぐポイント — あなたの固有性が現れる場所
  </div>
  <div class="cross-grid">{tension_html}</div>
</div>''' if tensions else ''}

<div class="confidence-badge">確度はおよそ 75%（生年月日と血液型ベースの分析）でございます。性格アンケート（Tier 2）にお進みいただくと、あなたの心理的パターンと占術データの交差点がさらに鮮明に浮かび上がってまいります。</div>
'''
    except Exception as e:
        return f'<p style="color:var(--text-muted)">クロスリファレンスの生成に失敗: {e}</p>'
