"""Dashboard section helpers: generated by refactor split."""
import json
from datetime import date as _date

def _this_month_guidance(p):
    """Generate 'This Month's Guidance' — the #1 value section right after Hero."""
    mf = p.get('monthly_fortune', [])
    current_month_num = _date.today().month
    cur_month = next((m for m in mf if m['month'] == current_month_num), None)
    if not cur_month:
        return ''

    interp = p.get('interpretations', {})
    hero = interp.get('hero', {})
    tagline = hero.get('tagline', '')
    dm = p['four_pillars']['day_master']
    ys = p['nine_star_ki']['year_star']
    rok = p['rokusei']
    west = p['western_astrology']['sun_sign']
    sf_top5 = p.get('strengths_finder', {}).get('top5', [])
    ennea = p.get('personality', {}).get('enneagram', {})
    missing = p['four_pillars'].get('missing_elements', [])

    # Determine overall month energy
    domains = cur_month['domains']
    avg_stars = sum(domains.values()) / len(domains)
    nine_energy = cur_month['nine_star']['energy']
    rok_phase = cur_month['rokusei']['phase']
    rok_type = cur_month['rokusei']['type']

    # Month narrative — personalized by connecting traits to fortune
    month_label = f'{current_month_num}月'

    # Build narrative pieces
    if avg_stars >= 4:
        energy_tone = '追い風'
        energy_desc = 'エネルギーが高く、積極的に動ける月'
        energy_icon_bg = 'rgba(34,197,94,0.15)'
        energy_icon_color = 'var(--accent-green-light)'
        energy_icon = '&#9650;'  # up triangle
    elif avg_stars >= 3:
        energy_tone = '安定'
        energy_desc = '地固めと準備に適した月'
        energy_icon_bg = 'rgba(59,130,246,0.15)'
        energy_icon_color = 'var(--accent-blue-light)'
        energy_icon = '&#9654;'  # right triangle
    elif avg_stars >= 2:
        energy_tone = '慎重'
        energy_desc = '守りを固め、無理をしない月'
        energy_icon_bg = 'rgba(234,179,8,0.15)'
        energy_icon_color = '#facc15'
        energy_icon = '&#9660;'  # down triangle
    else:
        energy_tone = '充電'
        energy_desc = '休息と回復を最優先にする月'
        energy_icon_bg = 'rgba(239,68,68,0.15)'
        energy_icon_color = 'var(--accent-red-light)'
        energy_icon = '&#9724;'  # square

    # Generate personalized action items based on profile + fortune
    actions = _generate_monthly_actions(p, cur_month, avg_stars)
    actions_html = ''
    for a in actions:
        actions_html += f'''<div class="guidance-action">
          <div class="guidance-action-icon" style="background:{a['icon_bg']};color:{a['icon_color']}">{a['icon']}</div>
          <div>
            <div class="guidance-action-title">{a['title']}</div>
            <div class="guidance-action-desc">{a['desc']}</div>
          </div>
        </div>'''

    # Watch out
    watch_items = _generate_monthly_watchouts(p, cur_month, avg_stars)
    watch_html = ''
    if watch_items:
        watch_html = '<div class="guidance-watch"><div class="guidance-watch-title">気をつけること</div>'
        for w in watch_items:
            watch_html += f'<div class="guidance-watch-item">{w}</div>'
        watch_html += '</div>'

    # Nine Star + Rokusei + Western tags
    nine_note = cur_month['nine_star']['note']
    pc = _phase_color_py(rok_type)

    # Western horoscope tag for this month
    wa = p.get('western_astrology', {})
    monthly_horo = wa.get('monthly_horoscope', [])
    cur_west = next((h for h in monthly_horo if h['month'] == current_month_num), None)
    west_tag = ''
    if cur_west:
        west_tag = f'<span class="month-tag" style="background:rgba(139,92,246,0.15);color:var(--accent-purple-light);border:1px solid rgba(139,92,246,0.3)">西洋: {cur_west["theme"]}</span>'

    # Mercury retrograde warning
    mercury_retro = wa.get('mercury_retrograde_2026', [])
    retro_badge = _mercury_retro_badge(mercury_retro, current_month_num)

    return f'''<section class="section" id="this-month">
  <div class="pillar-header">
    <div class="pillar-icon" style="background:{energy_icon_bg};color:{energy_icon_color}">{energy_icon}</div>
    <div><h2>{month_label}のあなたへ</h2>
      <div class="pillar-sub">{energy_desc}</div></div>
  </div>
  <div class="guidance-summary">
    <div class="guidance-overview">
      <div class="guidance-energy-badge" style="background:{energy_icon_bg};color:{energy_icon_color};border:1px solid {energy_icon_color}">{energy_tone}</div>
      <div class="guidance-tags">
        <span class="month-tag" style="background:rgba(99,102,241,0.15);color:#a5b4fc">九星: {nine_note}</span>
        <span class="month-tag" style="background:{pc['bg']};color:{pc['color']};border:1px solid {pc['border']}">六星: {rok_phase}</span>
        {west_tag}
        {retro_badge}
      </div>
    </div>
    <div class="guidance-narrative">{_generate_monthly_narrative(p, cur_month, avg_stars, energy_tone)}</div>
    <div class="guidance-actions-grid">
      <div class="guidance-actions-section">
        <div class="guidance-section-label">今月やるべきこと</div>
        {actions_html}
      </div>
      {watch_html}
    </div>
  </div>
</section>'''

PALACE_DESC = {
    '震宮': '行動力が高まり、新しいスタートを切りやすい時期',
    '巽宮': '人脈と信用が拡大する時期。情報が集まりやすい',
    '中宮': '年間で最もエネルギーが集中する中心位置。影響力が最大化',
    '乾宮': '目上の人や権威者からの後押しが得やすい時期',
    '兌宮': '悦びと収穫の時期。社交的なイベントが好結果を生む',
    '艮宮': '変化のタイミング。過去の蓄積を見直し、方向転換に適した時期',
    '離宮': '注目を集めやすい時期。自己表現と発信が効果的',
    '坎宮': '内省と忍耐の時期。表面的には停滞感があるが、内面の成長が進む',
    '坤宮': '受容と準備の時期。土台をしっかり固め、次の飛躍に備える',
}

PHASE_DESC = {
    '安定': '最も安定した運気。大きな決断や長期計画に最適',
    '財成': '財運が充実する時期。投資や資産形成に追い風',
    '達成': '努力が成果として実を結ぶ時期。目標達成に全力を',
    '立花': '才能や魅力が開花する時期。クリエイティブな活動に最適',
    '再会': '過去のつながりが復活する時期。旧友や以前の経験が価値を持つ',
    '種子': '新しい種をまく時期。将来の芽を育てるスタート地点',
    '緑生': '芽が伸び始める成長期。学びと実験に適した時期',
    '陰影': '大殺界の入口。慎重に行動し、新規の大きな契約は避ける',
    '停止': '大殺界の中心。じっと耐え、現状維持を最優先に',
    '減退': '大殺界の出口。少しずつ回復するが、まだ油断は禁物',
    '健弱': '小殺界。体調や気力にムラが出やすい。無理は禁物',
    '乱気': '中殺界。判断力が鈍りやすい。衝動的な決断を避ける',
}

def _generate_monthly_narrative(p, cur_month, avg_stars, energy_tone):
    """Generate a personalized narrative for the current month."""
    dm = p['four_pillars']['day_master']
    sf_top5 = p.get('strengths_finder', {}).get('top5', [])
    missing = p['four_pillars'].get('missing_elements', [])
    ennea = p.get('personality', {}).get('enneagram', {})
    rok_phase = cur_month['rokusei']['phase']
    nine_note = cur_month['nine_star']['note']
    nine_palace = cur_month['nine_star'].get('palace', '')
    month_num = cur_month['month']
    dm_desc = dm.get('description', '')

    # Rotate through top 5 strengths by month
    if sf_top5:
        sf_idx = (month_num - 1) % len(sf_top5)
        top_strength = sf_top5[sf_idx]['name']
    else:
        top_strength = ''
    top_ja = SF_JA.get(top_strength, '')

    # Get western horoscope data for this month
    wa = p.get('western_astrology', {})
    monthly_horo = wa.get('monthly_horoscope', [])
    cur_west = next((h for h in monthly_horo if h['month'] == month_num), None)
    west_theme = cur_west['theme'] if cur_west else ''
    west_focus = cur_west['focus'] if cur_west else ''

    palace_desc = PALACE_DESC.get(nine_palace, '')
    phase_desc = PHASE_DESC.get(rok_phase, '')

    parts = []

    # Opening — connect palace/phase specifics to month energy
    if avg_stars >= 4:
        if nine_palace:
            parts.append(f'{month_num}月、九星気学ではあなたは{nine_palace}へと入られ、{palace_desc}のお時期でございます。')
        parts.append(f'六星占術では「{rok_phase}」——{phase_desc}のお時期でございます。' if phase_desc else f'六星占術では「{rok_phase}」のお時期でございます。')
        if top_strength:
            parts.append(f'この好機の波に乗られ、{top_strength}（{top_ja}）をお持ちのあなたの本領を、今こそ存分に発揮なさる時でございます。')
    elif avg_stars >= 3:
        if nine_palace:
            parts.append(f'{month_num}月は{nine_palace}（{palace_desc}）に位置するお月でございます。')
        parts.append(f'六星占術では「{rok_phase}」——{phase_desc}のお時期でございます。' if phase_desc else '')
        if top_strength:
            parts.append(f'{top_strength}（{top_ja}）という持ち前の資質をお活かしになりながら、着実に一歩ずつお進みになることが肝要でございます。')
    elif avg_stars >= 2:
        parts.append(f'{month_num}月は、守りを固め、内側を静かに満たされるお月でございます。')
        if nine_palace:
            parts.append(f'九星気学では{nine_palace}（{palace_desc}）の位置にあたり、外よりも内へと目を向けるお時期でございます。')
        if phase_desc:
            parts.append(f'六星占術は「{rok_phase}」——{phase_desc}のお時期でございます。')
        if missing:
            missing_str = '・'.join(str(m) for m in missing)
            parts.append(f'五行で欠けておられる「{missing_str}」の気を意識的に補ってみてください——今はとりわけその力が深く根付くお時期でございます。')
    else:
        parts.append(f'{month_num}月は、無理をなさらず、静かに回復の時間を大切になさるべきお月でございます。')
        if nine_palace:
            parts.append(f'九星気学では{nine_palace}（{palace_desc}）の位置でございます。')
        if phase_desc:
            parts.append(f'六星占術は「{rok_phase}」——{phase_desc}のお時期でございます。')
        parts.append('今この時期にお蓄えになった力は、必ず次の好機の季節に花開いてまいります。')
        if ennea:
            stress = ennea.get('stress_direction', '')
            etype = ennea.get('type', '')
            if stress:
                parts.append(f'エニアグラムType {etype}のあなたは、ストレス下でType {stress}の方向へ引き寄せられやすうございます——意識的に心を休める時間をお取りになることを、強くお勧めいたします。')

    # Append western astrology theme when available
    if west_theme and west_focus:
        parts.append(f'西洋占星術では「{west_theme}」のテーマが深まるお月でございます。{west_focus}')

    return ''.join(parts)

def _generate_monthly_actions(p, cur_month, avg_stars):
    """Generate 3 actionable items based on profile + current month fortune."""
    sf_top5 = p.get('strengths_finder', {}).get('top5', [])
    ennea = p.get('personality', {}).get('enneagram', {})
    dm = p['four_pillars']['day_master']
    domains = cur_month['domains']
    rok_phase = cur_month['rokusei']['phase']
    actions = []

    # Best domain — when all scores are equal, use rokusei phase to pick focus
    phase_domain_hint = {
        '財成': 'money', '安定': 'work', '達成': 'work', '立花': 'romance',
        '再会': 'romance', '種子': 'health', '緑生': 'health',
        '陰影': 'health', '停止': 'health', '減退': 'health',
        '健弱': 'health', '乱気': 'health',
    }
    all_equal = len(set(domains.values())) == 1
    if all_equal:
        best_domain = phase_domain_hint.get(rok_phase, 'work')
    else:
        best_domain = max(domains, key=domains.get)

    domain_ja = {'work': '仕事', 'money': 'お金', 'health': '健康', 'romance': '人間関係'}
    domain_icons = {
        'work': ('&#9733;', 'rgba(59,130,246,0.15)', 'var(--accent-blue-light)'),
        'money': ('&#9830;', 'rgba(201,168,76,0.15)', '#c9a84c'),
        'health': ('&#9829;', 'rgba(34,197,94,0.15)', 'var(--accent-green-light)'),
        'romance': ('&#9827;', 'rgba(244,114,182,0.15)', '#f472b6'),
    }

    # Action 1: Leverage best domain
    icon_data = domain_icons.get(best_domain, ('&#9733;', 'rgba(99,102,241,0.15)', '#a5b4fc'))
    if avg_stars >= 3:
        actions.append({
            'title': f'{domain_ja.get(best_domain, best_domain)}に注力する',
            'desc': _domain_action_desc(best_domain, domains[best_domain], True),
            'icon': icon_data[0], 'icon_bg': icon_data[1], 'icon_color': icon_data[2],
        })
    else:
        actions.append({
            'title': f'{domain_ja.get(best_domain, best_domain)}を守る',
            'desc': _domain_action_desc(best_domain, domains[best_domain], False),
            'icon': icon_data[0], 'icon_bg': icon_data[1], 'icon_color': icon_data[2],
        })

    # Action 2: Strength-based action — rotate through top 5 by month
    if sf_top5:
        month_num = cur_month['month']
        sf_idx = (month_num - 1) % len(sf_top5)
        top = sf_top5[sf_idx]
        top_ja = SF_JA.get(top['name'], '')
        if avg_stars >= 3:
            actions.append({
                'title': f'{top["name"]}（{top_ja}）を武器にする',
                'desc': _strength_action(top['name'], True),
                'icon': '&#9733;', 'icon_bg': 'rgba(99,102,241,0.15)', 'icon_color': '#a5b4fc',
            })
        else:
            actions.append({
                'title': f'{top["name"]}（{top_ja}）で自分を守る',
                'desc': _strength_action(top['name'], False),
                'icon': '&#9733;', 'icon_bg': 'rgba(99,102,241,0.15)', 'icon_color': '#a5b4fc',
            })

    # Action 3: Element/spiritual action
    hsp = p.get('personality', {}).get('hsp', {})
    if hsp.get('score') == 'high' or hsp.get('total', 0) >= 18:
        if avg_stars <= 2:
            actions.append({
                'title': '繊細さのケアを最優先に',
                'desc': 'エネルギーが低い月は、繊細な感覚が過敏になりがち。ネガティブな刺激を避け、自然の中で過ごす時間や、一人で内省する時間を意識的に確保する',
                'icon': '&#9826;', 'icon_bg': 'rgba(139,92,246,0.15)', 'icon_color': 'var(--accent-purple-light)',
            })
        else:
            actions.append({
                'title': '繊細さを創造性に変換する',
                'desc': '好調期の繊細さは、美しいものや深い体験から何倍もの充足を引き出す。アート・音楽・深い会話を意識的に取り入れて、感性を栄養にする',
                'icon': '&#9826;', 'icon_bg': 'rgba(139,92,246,0.15)', 'icon_color': 'var(--accent-purple-light)',
            })
    else:
        missing = p['four_pillars'].get('missing_elements', [])
        if missing:
            elem_actions = {
                '金': ('決断力を意識的に鍛える', '考えすぎる前に「小さく試す」を実践。完璧を待たず、70点で動き出す訓練を'),
                '水': ('柔軟性を意識する', '予定通りにいかない時こそ成長のチャンス。「別のルートもある」と自分に言い聞かせる'),
                '木': ('成長のエネルギーを補う', '新しい学びや挑戦を一つ始める。木のように上へ伸びる意識を持つ'),
                '火': ('情熱を燃やす場を作る', '心が躍ることに時間を使う。義務感だけの行動を減らし、ワクワクを優先する'),
                '土': ('安定の基盤を作る', 'ルーティンを一つ定着させる。毎日同じ時間に同じことをする習慣が土の力を補う'),
            }
            first_missing = str(missing[0])
            ea = elem_actions.get(first_missing, ('バランスを整える', '欠けている要素を意識的に生活に取り入れる'))
            actions.append({
                'title': ea[0],
                'desc': ea[1],
                'icon': '&#9670;', 'icon_bg': 'rgba(234,179,8,0.15)', 'icon_color': '#facc15',
            })

    return actions[:3]

def _domain_action_desc(domain, stars, is_offensive):
    """Generate domain-specific action description."""
    if domain == 'work':
        if is_offensive:
            return '仕事運が好調。新しいプロジェクトの提案や、後回しにしていた重要タスクに着手するベストタイミング'
        return '仕事は現状維持がベスト。新規案件は控え、既存の仕事を丁寧に仕上げることに集中する'
    if domain == 'money':
        if is_offensive:
            return '金運が高い月。投資判断や価格交渉に適している。ただし衝動買いには注意'
        return '金運は守り。大きな出費は避け、計画的な支出管理を。固定費の見直しに良いタイミング'
    if domain == 'health':
        if is_offensive:
            return '体調が安定。新しい運動習慣を始めたり、健康投資に踏み切るのに最適'
        return '体調を崩しやすい月。睡眠の質を最優先に。無理なスケジュールは組まない'
    # romance
    if is_offensive:
        return '人間関係が良好。新しい出会いにオープンに、既存の関係も深まるタイミング'
    return '対人関係で誤解が生じやすい。丁寧なコミュニケーションを心がけ、衝突は避ける'

def _strength_action(strength_name, is_offensive):
    """Generate strength-specific action for the month."""
    offensive_map = {
        'Empathy': '共感力を使って、チームメンバーや周囲の人が本当に求めていることを察知し、先回りで動く。サービス設計やフィードバック収集に最適',
        'Intellection': '深い思考に没頭できる時間をブロックする。重要なテーマについて、ノートに書きながら考えを整理する',
        'Deliberative': '重要な意思決定に取り組むベストタイミング。慎重さを武器に、リスクを見極めた上で前進する',
        'Connectedness': '異なるプロジェクトや人脈の「つながり」を意識する。一見無関係なものの間にシナジーを見出す',
        'Maximizer': '既にうまくいっていることを「さらに良く」する。弱みの修正より、強みの極大化に集中する',
    }
    defensive_map = {
        'Empathy': '他者の感情を吸収しすぎないよう、意識的に境界線を引く。「感じ取っても、背負わない」を練習する',
        'Intellection': '考えすぎて動けなくならないよう注意。思考は30分で区切り、小さなアクションに変換する',
        'Deliberative': '慎重さが行動の先延ばしにならないよう意識する。「完璧な答えより、今できる最善」で動く',
        'Connectedness': '全体を見すぎて疲れてしまわないよう、今週やることだけに焦点を絞る',
        'Maximizer': '「もっと良くできる」の追求を一旦止めて、現状の「十分良い」を認める練習をする',
    }
    if is_offensive:
        return offensive_map.get(strength_name, f'{strength_name}を最大限に活用して、新しい挑戦に取り組む')
    return defensive_map.get(strength_name, f'{strength_name}が裏目に出ないよう、バランスを意識する')

def _generate_monthly_watchouts(p, cur_month, avg_stars):
    """Generate watch-out items based on profile weaknesses + fortune."""
    items = []
    missing = p['four_pillars'].get('missing_elements', [])
    ennea = p.get('personality', {}).get('enneagram', {})
    rok_type = cur_month['rokusei']['type']
    sf_top5 = p.get('strengths_finder', {}).get('top5', [])

    # Rokusei danger
    if rok_type in ('danger', 'caution'):
        satsukai = cur_month['rokusei'].get('satsukai')
        if satsukai:
            items.append(f'六星占術で{satsukai}に入っています。大きな契約・転職・引越しなど人生の重大決断は可能な限り避ける')
        else:
            items.append('六星占術で注意期。衝動的な判断は避け、一晩寝かせてから決める')

    # Missing elements warning
    if missing and avg_stars <= 3:
        missing_warnings = {
            '金': '「決断できない」状態に陥りやすい月。迷ったら信頼できる人に相談して背中を押してもらう',
            '水': '柔軟性が低下しやすい月。予定変更にイライラしたら深呼吸。「流れに身を任せる」ことも戦略',
            '土': '地に足がつかない感覚がある月。毎朝のルーティンを崩さないことが安定の鍵',
            '木': '成長が停滞する感覚がある月。小さな学びを一つ始めるだけでエネルギーが回復する',
            '火': 'モチベーションが上がりにくい月。「なぜやるのか」原点に立ち返ると情熱が再点火する',
        }
        for m in missing[:2]:
            warn = missing_warnings.get(str(m))
            if warn:
                items.append(warn)

    # Enneagram stress
    if avg_stars <= 2 and ennea:
        stress = ennea.get('stress_direction')
        stress_msgs = {
            1: '完璧主義に陥りすぎないよう注意。「まあいいか」を意識的に唱える',
            2: '自己犠牲モードに入りやすい。「自分のニーズも大切にしていい」と意識する',
            4: '感情の波に飲まれやすい時期。客観的な視点を保つ工夫を',
            5: '殻にこもりすぎないよう注意。信頼できる人との対話を意識的に入れる',
            7: '楽しいことに逃避しやすい。不快でも向き合うべきことから目をそらさない',
            8: '攻撃的になりやすい。反射的に言葉を返す前に3秒待つ',
        }
        msg = stress_msgs.get(stress)
        if msg:
            items.append(msg)

    return items[:3]

def _action_blueprint(p):
    """Generate actionable takeaways section connecting Core Identity to daily life."""
    sf_top5 = p.get('strengths_finder', {}).get('top5', [])
    ennea = p.get('personality', {}).get('enneagram', {})
    missing = p['four_pillars'].get('missing_elements', [])
    dm = p['four_pillars']['day_master']
    hsp = p.get('personality', {}).get('hsp', {})
    adhd = p.get('personality', {}).get('adhd', {})
    west = p['western_astrology']['sun_sign']

    items = []

    # 1. Energy management based on Day Master + HSP + ADHD
    if hsp.get('score') == 'high' or hsp.get('total', 0) >= 18:
        items.append({
            'label': 'エネルギー管理',
            'title': '繊細さ × 過集中 — 「没頭」と「回復」のリズムを設計する',
            'desc': '繊細な感受性は最大の武器であると同時に、消耗の原因にもなる。90分集中→15分完全回復のサイクルを基本リズムに。ネガティブな環境からは物理的に距離を取る仕組みを作る',
        })
    else:
        items.append({
            'label': 'エネルギー管理',
            'title': f'{dm["char"]}火の炎を安定させる — 環境設計が鍵',
            'desc': f'{dm["char"]}火（ロウソクの炎）は環境次第で安定も不安定もする。集中できる環境を意識的に選び、エネルギーの無駄遣いを避ける仕組みを作る',
        })

    # 2. Weakness compensation
    if missing:
        elem_comp = {
            '金': ('決断力の補完', '「70点で動く」ルールを設定する。完璧な答えを待つのではなく、仮説→実行→修正のサイクルを高速で回す。タイマーで考える時間を制限するのも有効'),
            '水': ('柔軟性の補完', '計画通りにいかない状況を「学びのチャンス」と再定義する。月に一度、いつもと違う行動パターンを試す習慣を作る'),
            '木': ('成長力の補完', '月に一つ新しいスキルや知識を学ぶ習慣。小さくても継続的な成長が、欠けた木の力を補う'),
            '火': ('情熱の補完', '「なぜ自分がこれをやるのか」を定期的に言語化する。目的を明確にすることで内なる火を維持する'),
            '土': ('安定基盤の補完', 'ルーティンを少なくとも3つ持つ。毎日同じ時間に起き、同じ順序で朝の準備をするだけで土の力が補完される'),
        }
        first_missing = str(missing[0])
        comp = elem_comp.get(first_missing, ('バランスの補完', '欠けている要素を意識的に日常に取り入れる'))
        items.append({
            'label': '弱点の構造的カバー',
            'title': comp[0],
            'desc': comp[1],
        })

    # 3. Strength optimization
    if sf_top5:
        top = sf_top5[0]
        top_ja = SF_JA.get(top['name'], '')
        opt_map = {
            'Empathy': ('共感力の最適活用', '共感力は「他者を理解する」だけでなく「他者が何を求めているか先読みする」戦略的スキル。サービス設計・チームマネジメント・交渉において、相手の言葉にならないニーズを読む武器として使う。ただし境界線は必須 — 「感じ取っても、背負わない」を原則に'),
            'Intellection': ('思考力の最適活用', '一人で深く考える時間を「生産的な仕事」として確保する。周囲には「考える時間」の必要性を説明し、カレンダーにブロック。思考の成果はメモや図で言語化し、価値を可視化する'),
            'Deliberative': ('慎重さの最適活用', 'リスク分析力を「守り」だけでなく「攻めの意思決定」に使う。「慎重に分析した結果、今が動くべきタイミング」と判断できれば、それは最も確実な攻め'),
            'Connectedness': ('つながりの力の最適活用', '異なる分野・プロジェクト・人物の間に隠された接点を見つけ出す力を戦略的に使う。月に一度「一見無関係な2つのことを結びつける」思考実験を行う'),
            'Maximizer': ('最上志向の最適活用', '「良い→最高」の追求を、最もインパクトのある領域に集中する。全てを完璧にしようとせず、20%の努力で80%の成果が出る領域を見極める'),
        }
        opt = opt_map.get(top['name'], (f'{top["name"]}の最適活用', f'{top["name"]}（{top_ja}）を日常の意思決定と行動に組み込み、最大限に活用する'))
        items.append({
            'label': '最大の武器',
            'title': opt[0],
            'desc': opt[1],
        })

    if not items:
        return ''

    cards_html = ''
    for item in items:
        cards_html += f'''<div class="blueprint-card">
      <div class="blueprint-label">{item['label']}</div>
      <div class="blueprint-title">{item['title']}</div>
      <div class="blueprint-desc">{item['desc']}</div>
    </div>'''

    return f'''<div class="blueprint-section" id="blueprint">
  <div class="blueprint-grid">{cards_html}</div>
</div>'''

DOMAIN_MSGS = {
    'work': {
        5: '全力投球で成果が出る時期。新プロジェクトの立ち上げに最適',
        4: '順調に進む。チャンスを逃さず着実に成果を積む',
        3: '普通ペース。地道な積み重ねが後に効いてくる',
        2: '停滞感あり。焦らず基礎固めに集中',
        1: '無理は禁物。現状維持を心がけ、回復を優先',
    },
    'money': {
        5: '金運好調。投資・交渉に良い時期。大きな判断も可',
        4: '堅実な収入が見込める。無駄遣いを避ければ蓄積できる',
        3: '収支トントン。計画的な支出管理が重要',
        2: '予想外の出費に注意。大きな買い物は延期が吉',
        1: '金運低迷。守りの姿勢で乗り切る。衝動買い厳禁',
    },
    'health': {
        5: '体調絶好調。新しい運動習慣を始めるチャンス',
        4: '概ね良好。規則正しい生活を維持して好調を保つ',
        3: '可もなく不可もなく。睡眠の質に注意を払う',
        2: '疲れが出やすい。休息を意識的に増やす',
        1: '体調管理に細心の注意。無理なスケジュールは避ける',
    },
    'romance': {
        5: '人間関係が最も輝く時期。新しい出会いも深い絆も',
        4: '良好な関係が築ける。コミュニケーションが円滑',
        3: '平穏な時期。既存の関係を大切にする',
        2: 'すれ違いが起きやすい。丁寧な対話を心がける',
        1: '距離感が大事。一人の時間で自分を充電する',
    },
}

DOMAIN_MSGS_ELDERLY = {
    'work': {
        5: '活動的に外へ出られる好機。趣味・ボランティア・社会参加に最適な時期',
        4: '気力・体力が充実。やりたかったことを一つ実行するのに最適',
        3: '無理のない範囲でペースよく。人との交流が気力を高める',
        2: '体力を温存しながら。好きなことをゆったりと楽しむ日々',
        1: '体を休ませる月。回復を最優先に、焦らないことが大切',
    },
    'romance': {
        5: '大切な人との絆が深まる。家族・旧友への連絡や集まりに最適な時期',
        4: '人との縁が温かく広がる月。感謝の気持ちを伝えたいタイミング',
        3: '穏やかな交流の時期。身近な人との時間を丁寧に過ごす',
        2: 'じっくり内省する時期。無理に動かなくとも、心が繋がっている',
        1: '静かに自分と向き合う月。好きな本や音楽と過ごすのも良い',
    },
}

def _domain_msg(domain, stars, phase, age=0):
    if age >= 70 and domain in DOMAIN_MSGS_ELDERLY:
        return DOMAIN_MSGS_ELDERLY[domain].get(stars, DOMAIN_MSGS.get(domain, {}).get(stars, ''))
    return DOMAIN_MSGS.get(domain, {}).get(stars, '')

def _monthly_advice(p, month_data):
    """Generate personalized advice text for a specific month."""
    domains = month_data['domains']
    avg = sum(domains.values()) / len(domains)
    rok_type = month_data['rokusei']['type']
    rok_phase = month_data['rokusei']['phase']
    nine_note = month_data['nine_star']['note']
    nine_palace = month_data['nine_star'].get('palace', '')
    month_num = month_data['month']
    sf_top5 = p.get('strengths_finder', {}).get('top5', [])
    missing = p['four_pillars'].get('missing_elements', [])
    dm = p['four_pillars']['day_master']
    dm_char = dm.get('char', '')
    dm_elem_ja = {'Fire':'火','Wood':'木','Earth':'土','Metal':'金','Water':'水'}.get(dm.get('element',''), '')

    # Western horoscope for this month
    wa = p.get('western_astrology', {})
    monthly_horo = wa.get('monthly_horoscope', [])
    cur_west = next((h for h in monthly_horo if h['month'] == month_num), None)

    # Rotate through top 5 strengths by month
    if sf_top5:
        sf_idx = (month_num - 1) % len(sf_top5)
        top_strength = sf_top5[sf_idx]['name']
    else:
        top_strength = ''
    top_ja = SF_JA.get(top_strength, '')

    palace_desc = PALACE_DESC.get(nine_palace, '')
    phase_desc = PHASE_DESC.get(rok_phase, '')

    parts = []

    if avg >= 4:
        # Use palace + phase to differentiate same-avg months
        if nine_palace:
            parts.append(f'{nine_palace}（{palace_desc}）に位置する好調月。')
        parts.append(f'六星占術「{rok_phase}」— {phase_desc}。' if phase_desc else '')
        if top_strength:
            parts.append(f'{dm_char}{dm_elem_ja}の本質を持つあなたは、{top_strength}（{top_ja}）を全開にして攻める月。')
    elif avg >= 3:
        if nine_palace:
            parts.append(f'{nine_palace}の影響で{palace_desc}。')
        parts.append(f'六星占術「{rok_phase}」— {phase_desc}。' if phase_desc else '')
        if top_strength:
            parts.append(f'{top_strength}（{top_ja}）を土台に、{dm_char}{dm_elem_ja}らしく着実に進むことが鍵。')
    elif avg >= 2:
        parts.append(f'エネルギーが低下しやすい月。')
        if nine_palace:
            parts.append(f'九星気学では{nine_palace}（{palace_desc}）。')
        if rok_type in ('danger', 'caution'):
            parts.append(f'六星占術で「{rok_phase}」— {phase_desc}。大きな決断は控えるのが賢明。')
        if top_strength:
            parts.append(f'{dm_char}{dm_elem_ja}の炎を守りつつ、{top_strength}（{top_ja}）を防御的に活用して。')
        if missing:
            missing_str = '・'.join(str(m) for m in missing[:2])
            parts.append(f'欠如要素「{missing_str}」の影響が出やすいので意識的にケアを。')
    else:
        parts.append(f'充電を最優先にする月。')
        if nine_palace:
            parts.append(f'{nine_palace}（{palace_desc}）。')
        if phase_desc:
            parts.append(f'六星占術「{rok_phase}」— {phase_desc}。')
        if top_strength:
            parts.append(f'{dm_char}{dm_elem_ja}の炎が弱まる時期。{top_strength}（{top_ja}）に頼りすぎず、静かに回復を。')

    # Add western horoscope theme
    if cur_west:
        parts.append(f'西洋占星術のテーマ「{cur_west["theme"]}」— {cur_west["focus"]}')

    return ''.join(parts) if parts else ''

def _monthly_guidance_data(p, m):
    """Generate guidance data (energy badge, narrative, actions, watchouts) for a month."""
    domains = m['domains']
    avg_stars = sum(domains.values()) / len(domains)
    rok_type = m['rokusei']['type']

    if avg_stars >= 4:
        energy_tone = '追い風'
        energy_desc = 'エネルギーが高く、積極的に動ける月'
        energy_icon_bg = 'rgba(34,197,94,0.15)'
        energy_icon_color = 'var(--accent-green-light)'
    elif avg_stars >= 3:
        energy_tone = '安定'
        energy_desc = '地固めと準備に適した月'
        energy_icon_bg = 'rgba(59,130,246,0.15)'
        energy_icon_color = 'var(--accent-blue-light)'
    elif avg_stars >= 2:
        energy_tone = '慎重'
        energy_desc = '守りを固め、無理をしない月'
        energy_icon_bg = 'rgba(234,179,8,0.15)'
        energy_icon_color = '#facc15'
    else:
        energy_tone = '充電'
        energy_desc = '休息と回復を最優先にする月'
        energy_icon_bg = 'rgba(239,68,68,0.15)'
        energy_icon_color = 'var(--accent-red-light)'

    narrative = _generate_monthly_narrative(p, m, avg_stars, energy_tone)
    actions = _generate_monthly_actions(p, m, avg_stars)
    watchouts = _generate_monthly_watchouts(p, m, avg_stars)

    actions_html = ''
    for a in actions:
        actions_html += (f'<div class="guidance-action">'
                        f'<div class="guidance-action-icon" style="background:{a["icon_bg"]};color:{a["icon_color"]}">{a["icon"]}</div>'
                        f'<div><div class="guidance-action-title">{a["title"]}</div>'
                        f'<div class="guidance-action-desc">{a["desc"]}</div></div></div>')

    watch_html = ''
    if watchouts:
        watch_html = '<div class="guidance-watch"><div class="guidance-watch-title">気をつけること</div>'
        for w in watchouts:
            watch_html += f'<div class="guidance-watch-item">{w}</div>'
        watch_html += '</div>'

    return {
        'energyTone': energy_tone,
        'energyDesc': energy_desc,
        'energyBg': energy_icon_bg,
        'energyColor': energy_icon_color,
        'narrative': narrative,
        'actionsHtml': actions_html,
        'watchHtml': watch_html,
    }

def _monthly(p):
    mf = p.get('monthly_fortune', [])
    if not mf:
        return ''
    current_month = _date.today().month - 1  # 0-based
    _age = p.get('identity', {}).get('age', 0)
    work_label = '生きがい' if _age >= 70 else '仕事'
    romance_label = '家族・絆' if _age >= 70 else '恋愛'

    # Year timeline bar
    timeline_colors = {
        'great': 'rgba(34,197,94,0.5)', 'good': 'rgba(59,130,246,0.4)',
        'caution': 'rgba(234,179,8,0.4)', 'danger': 'rgba(239,68,68,0.45)',
    }
    timeline = ''
    for m in mf:
        bg = timeline_colors.get(m['rokusei']['type'], 'rgba(99,102,241,0.3)')
        timeline += f'<div class="yt-month" data-month="{m["month"]-1}" style="background:{bg}">{m["month"]}</div>'

    # Build guidance data for current month
    cur_month_data = next((m for m in mf if m['month'] == _date.today().month), None)
    guidance_json = 'null'
    if cur_month_data:
        gd = _monthly_guidance_data(p, cur_month_data)
        guidance_json = json.dumps(gd, ensure_ascii=False)

    # Western horoscope data
    wa = p.get('western_astrology', {})
    monthly_horo = wa.get('monthly_horoscope', [])
    mercury_retro = wa.get('mercury_retrograde_2026', [])

    def _get_west_data(month_num):
        hw = next((h for h in monthly_horo if h['month'] == month_num), None)
        retro = _mercury_retro_badge(mercury_retro, month_num)
        return {
            'theme': hw['theme'] if hw else '',
            'energy': hw['energy'] if hw else 0,
            'retroBadge': retro,
        }

    # Month panels with domain messages + personalized advice
    panels_data = json.dumps([{
        'month': f'{m["month"]}月',
        'monthNum': m['month'],
        'nineStarNote': m['nine_star']['note'],
        'nineStarEnergy': m['nine_star']['energy'],
        'rokuseiPhase': m['rokusei']['phase'],
        'rokuseiType': m['rokusei']['type'],
        'westernTheme': _get_west_data(m['month'])['theme'],
        'westernEnergy': _get_west_data(m['month'])['energy'],
        'retroBadge': _get_west_data(m['month'])['retroBadge'],
        'work': m['domains']['work'],
        'money': m['domains']['money'],
        'health': m['domains']['health'],
        'romance': m['domains']['romance'],
        'workMsg': _domain_msg('work', m['domains']['work'], m['rokusei']['phase'], _age),
        'moneyMsg': _domain_msg('money', m['domains']['money'], m['rokusei']['phase'], _age),
        'healthMsg': _domain_msg('health', m['domains']['health'], m['rokusei']['phase'], _age),
        'romanceMsg': _domain_msg('romance', m['domains']['romance'], m['rokusei']['phase'], _age),
        'advice': _monthly_advice(p, m),
    } for m in mf], ensure_ascii=False)

    return f'''<section class="section" id="monthly">
  <div class="year-timeline" id="yearTimeline">{timeline}</div>
  <div class="month-selector" id="monthSelector"></div>
  <div id="monthPanels"></div>
</section>
<script>
const monthlyData={panels_data};
const currentMonth={current_month};
const guidanceData={guidance_json};
function starRating(n){{return'<span style="color:var(--yellow);">'+'★'.repeat(n)+'</span><span style="color:var(--border);">'+'★'.repeat(5-n)+'</span>';}}
function phaseColor(t){{
  if(t==='great')return{{bg:'rgba(34,197,94,0.12)',border:'rgba(34,197,94,0.3)',color:'var(--accent-green-light)'}};
  if(t==='good')return{{bg:'rgba(59,130,246,0.12)',border:'rgba(59,130,246,0.3)',color:'var(--accent-blue-light)'}};
  if(t==='caution')return{{bg:'rgba(234,179,8,0.12)',border:'rgba(234,179,8,0.3)',color:'#facc15'}};
  return{{bg:'rgba(239,68,68,0.12)',border:'rgba(239,68,68,0.3)',color:'var(--accent-red-light)'}};
}}
function buildGuidanceHtml(g){{
  if(!g)return'';
  return`<div class="guidance-summary" style="margin-top:16px">
    <div class="guidance-overview">
      <div class="guidance-energy-badge" style="background:${{g.energyBg}};color:${{g.energyColor}};border:1px solid ${{g.energyColor}}">${{g.energyTone}}</div>
      <div style="font-size:12px;color:var(--text-secondary)">${{g.energyDesc}}</div>
    </div>
    <div class="guidance-narrative">${{g.narrative}}</div>
    <div class="guidance-actions-grid">
      <div class="guidance-actions-section">
        <div class="guidance-section-label">今月やるべきこと</div>
        ${{g.actionsHtml}}
      </div>
      ${{g.watchHtml}}
    </div>
  </div>`;
}}
const selEl=document.getElementById('monthSelector');
const panEl=document.getElementById('monthPanels');
monthlyData.forEach((m,i)=>{{
  const btn=document.createElement('button');
  btn.className='month-btn'+(i===currentMonth?' active current':'');
  btn.textContent=m.month;btn.dataset.month=i;btn.onclick=()=>selectMonth(i);
  selEl.appendChild(btn);
  const pc=phaseColor(m.rokuseiType);
  const isCurrentMonth=(i===currentMonth);
  const panel=document.createElement('div');
  panel.className='month-panel'+(isCurrentMonth?' active':'');
  panel.id='month-'+i;
  panel.innerHTML=`<div class="card">
    <div class="month-card-header">
      <div class="month-label">${{m.month}}</div>
      <div class="month-tags">
        <span class="month-tag" style="background:rgba(99,102,241,0.15);color:#a5b4fc">九星: ${{m.nineStarNote}}</span>
        <span class="month-tag" style="background:${{pc.bg}};color:${{pc.color}};border:1px solid ${{pc.border}}">六星: ${{m.rokuseiPhase}}</span>
        ${{m.westernTheme ? '<span class="month-tag" style="background:rgba(20,184,166,0.15);color:#5eead4;border:1px solid rgba(20,184,166,0.3)">西洋: '+m.westernTheme+'</span>' : ''}}
        ${{m.retroBadge || ''}}
      </div>
    </div>
    ${{m.advice ? '<div class="month-advice">' + m.advice + '</div>' : ''}}
    <div class="domain-grid">
      <div class="domain-card work"><div class="domain-icon-label"><div class="domain-label" style="color:var(--blue)">{work_label}</div><div class="domain-stars">${{starRating(m.work)}}</div></div><div class="domain-msg">${{m.workMsg}}</div></div>
      <div class="domain-card money"><div class="domain-icon-label"><div class="domain-label" style="color:var(--gold)">お金</div><div class="domain-stars">${{starRating(m.money)}}</div></div><div class="domain-msg">${{m.moneyMsg}}</div></div>
      <div class="domain-card health"><div class="domain-icon-label"><div class="domain-label" style="color:var(--green)">健康</div><div class="domain-stars">${{starRating(m.health)}}</div></div><div class="domain-msg">${{m.healthMsg}}</div></div>
      <div class="domain-card romance"><div class="domain-icon-label"><div class="domain-label" style="color:#f472b6">{romance_label}</div><div class="domain-stars">${{starRating(m.romance)}}</div></div><div class="domain-msg">${{m.romanceMsg}}</div></div>
    </div>
    ${{isCurrentMonth ? buildGuidanceHtml(guidanceData) : ''}}
  </div>`;
  panEl.appendChild(panel);
}});
function selectMonth(idx){{
  document.querySelectorAll('.month-btn').forEach(b=>b.classList.remove('active'));
  document.querySelectorAll('.month-panel').forEach(p=>p.classList.remove('active'));
  document.querySelector(`.month-btn[data-month="${{idx}}"]`).classList.add('active');
  document.getElementById('month-'+idx).classList.add('active');
  document.querySelectorAll('.yt-month').forEach(m=>m.style.opacity='0.5');
  document.querySelector(`.yt-month[data-month="${{idx}}"]`).style.opacity='1';
}}
document.querySelectorAll('.yt-month').forEach(el=>{{
  el.addEventListener('click',()=>selectMonth(parseInt(el.dataset.month)));
}});
selectMonth(currentMonth);
</script>'''
