"""Dashboard section helpers: generated by refactor split."""
import json
from datetime import date as _date
import sys as _sys
from pathlib import Path as _Path
_sys.path.insert(0, str(_Path(__file__).resolve().parent.parent.parent))
from lib.renderer import get_nav_html as _get_nav_html

def _gnav():
    nav_html = _get_nav_html(scope="private", current_page="Self-Insight", absolute=True)
    close_js = '<script>document.addEventListener("click",function(e){var m=document.querySelector(".nav-more");if(m&&!m.contains(e.target))m.classList.remove("open");});</script>'
    return nav_html + close_js

def _section_nav(has_personality):
    links = '<a href="#core-identity">Core Identity（自己本質）</a>'
    if has_personality:
        links += '<a href="#personality">Personality（性格特性）</a>'
    links += '<a href="#divination">占術プロファイル</a>'
    links += '<a href="#forecast-2026">2026 運勢</a>'
    links += '<a href="#monthly">月間運勢</a>'
    links += '<a href="#cross">Cross Analysis（クロス分析）</a>'
    return f'<nav class="nav-bar">{links}</nav>'

def _hero(p, tier):
    ident = p['identity']
    rok = p['rokusei']

    # Archetype
    archetype = _get_archetype(p)
    tagline = _get_archetype_tagline(p)

    # Stat card — 2026 score
    cur_comb = next((c for c in rok.get('reigou_combined', []) if c.get('year') == 2026), None)
    stats = ''
    if cur_comb:
        score = cur_comb['score']
        label = cur_comb.get('label', '')
        stats = (f'<div class="stat-card">'
                 f'<div class="label">2026年 運気スコア</div>'
                 f'<div class="value" style="color:{energy_color(score)}">{label} {score}</div>'
                 f'<div class="stat-sub">六星占術 統合スコア（0〜100）</div>'
                 f'</div>')
    else:
        # Fallback: average nine star + rokusei energies
        nsk = p.get('nine_star_ki', {})
        cur9 = next((c for c in nsk.get('nine_year_cycle', []) if c.get('current')), None)
        cur6 = next((c for c in rok.get('twelve_year_cycle', []) if c.get('current')), None)
        if cur9 or cur6:
            e9 = cur9['energy'] if cur9 else 0
            e6 = cur6['energy'] if cur6 else 0
            avg_score = round((e9 + e6) / 2) if (cur9 and cur6) else (e9 or e6)
            phase_label = cur6['phase'] if cur6 else (cur9['palace'] if cur9 else '')
            stats = (f'<div class="stat-card">'
                     f'<div class="label">2026年 運気スコア</div>'
                     f'<div class="value" style="color:{energy_color(avg_score)}">{phase_label} {avg_score}</div>'
                     f'<div class="stat-sub">九星×六星 平均スコア（0〜100）</div>'
                     f'</div>')

    # Hub card summaries
    dm = p['four_pillars']['day_master']
    ys = p['nine_star_ki']['year_star']
    essence_sub = _get_essence_sub(dm, ys)
    mf = p.get('monthly_fortune', [])
    current_month_num = _date.today().month
    cur_month = next((m for m in mf if m['month'] == current_month_num), None)

    # Hub card 1: Core Identity
    _hub1_elem_ja = {'Fire': '火', 'Wood': '木', 'Earth': '土', 'Metal': '金', 'Water': '水'}.get(dm.get('element', ''), '')
    hub1_summary = f'{dm["char"]}{_hub1_elem_ja} × {ys["name"]} — {essence_sub}' if essence_sub else f'{dm["char"]}{_hub1_elem_ja} × {ys["name"]}'

    # Hub card 2: Monthly fortune (九星宮 + 六星フェーズを併記して月間カードと整合)
    hub2_summary = ''
    if cur_month:
        domains = cur_month['domains']
        avg_stars = sum(domains.values()) / len(domains)
        ns_palace = cur_month.get('nine_star', {}).get('palace', '')
        rok_phase = cur_month.get('rokusei', {}).get('phase', '')
        PALACE_TONE = {
            '乾宮':'充実・実り','兌宮':'悦び・収穫','艮宮':'停滞・自己改革',
            '離宮':'注目・離別','坎宮':'厄・試練','坤宮':'変化・準備',
            '震宮':'発展・始動','巽宮':'整備・信用','中宮':'絶頂・転機',
        }
        palace_tone = PALACE_TONE.get(ns_palace, '')
        if ns_palace and rok_phase:
            hub2_summary = f'{current_month_num}月 — {ns_palace}（{palace_tone}）× 六星「{rok_phase}」'
        elif ns_palace:
            hub2_summary = f'{current_month_num}月 — {ns_palace}（{palace_tone}）'
        else:
            # fallback: domain avg
            if avg_stars >= 4:
                hub2_summary = f'{current_month_num}月 — 追い風。積極的に動ける'
            elif avg_stars >= 3:
                hub2_summary = f'{current_month_num}月 — 安定。地固めと準備の月'
            elif avg_stars >= 2:
                hub2_summary = f'{current_month_num}月 — 慎重に。守りを固める'
            else:
                hub2_summary = f'{current_month_num}月 — 充電。回復を優先する'
    else:
        hub2_summary = '月間運気データを読み込み中'

    # Hub card 3: Action
    sf_top5 = p.get('strengths_finder', {}).get('top5', [])
    if sf_top5:
        top_ja = SF_JA.get(sf_top5[0]['name'], sf_top5[0]['name'])
        hub3_summary = f'{sf_top5[0]["name"]}（{top_ja}）を活かす'
    else:
        hub3_summary = '自分の本質を活かす行動指針'

    nickname = ident.get('nickname') or ident.get('display_name') or ident.get('name', '')
    return f'''<section class="hero">
  <div class="hero-particles"></div>
  <div class="hero-content">
    {f'<div class="archetype-en">{archetype["en"]}</div>' if tier >= 2 else ''}
    <h1 class="archetype-name">{archetype["ja"]}</h1>
    <div class="hero-tagline">{tagline}</div>
    <div class="hero-name">{nickname}</div>
    {_rarity_stats_bar(p)}
    <div class="stats">{stats}</div>
    <div class="hub-cards-grid">
      <div class="hub-card-mini" onclick="document.getElementById('core-identity').scrollIntoView({{behavior:'smooth'}});var c=document.querySelector('#core-identity').closest('.hub-card');if(c&&!c.classList.contains('expanded'))c.classList.add('expanded');">
        <div class="hub-card-mini-icon" style="background:rgba(99,102,241,0.15);color:#a5b4fc">&#9733;</div>
        <div><div class="hub-card-mini-title">あなたの本質</div>
        <div class="hub-card-mini-summary">{hub1_summary}</div></div>
      </div>
      <div class="hub-card-mini" onclick="document.getElementById('monthly').scrollIntoView({{behavior:'smooth'}});var c=document.querySelector('#monthly').closest('.hub-card');if(c&&!c.classList.contains('expanded'))c.classList.add('expanded');">
        <div class="hub-card-mini-icon" style="background:rgba(234,179,8,0.15);color:#facc15">&#9670;</div>
        <div><div class="hub-card-mini-title">今月の運気</div>
        <div class="hub-card-mini-summary">{hub2_summary}</div></div>
      </div>
      <div class="hub-card-mini" onclick="document.getElementById('blueprint').scrollIntoView({{behavior:'smooth'}});var c=document.querySelector('#blueprint').closest('.hub-card');if(c&&!c.classList.contains('expanded'))c.classList.add('expanded');">
        <div class="hub-card-mini-icon" style="background:rgba(139,92,246,0.15);color:var(--accent-purple-light)">&#9829;</div>
        <div><div class="hub-card-mini-title">今日のアクション</div>
        <div class="hub-card-mini-summary">{hub3_summary}</div></div>
      </div>
    </div>
  </div>
</section>'''
