"""Dashboard section helpers: generated by refactor split."""

CSS = '''<style>
:root{--bg:#F5F4F0;--surface:#FFFFFF;--surface2:#F1F0EC;--border:#E8E5DE;--border-light:#D9D5CC;
  --accent:#4F46E5;--accent2:#6D28D9;--blue:#1D4ED8;--green:#15803D;--red:#BE334E;--yellow:#B45309;--gold:#A16207;
  --accent-green:#15803D;--accent-green-light:#15803D;--accent-blue:#1D4ED8;--accent-blue-light:#1D4ED8;
  --accent-red:#BE334E;--accent-red-light:#BE334E;
  --accent-purple:#6D28D9;--accent-purple-light:#6D28D9;--accent-purple-dark:#5B21B6;
  --accent-teal:#0F766E;--accent-teal-light:#0F766E;
  --text:#191C22;--text-secondary:#5C6370;--text-muted:#8B909B;
  --font-body:'Inter','Noto Sans JP',sans-serif;--font-mono:'Inter','Noto Sans JP',sans-serif;--font-display:'Inter','Noto Sans JP',sans-serif;--font-heading:'Inter',sans-serif;
  --r-sm:8px;--r-md:12px;--r-lg:18px;--r-xl:18px;--gnav-height:52px;
  --shadow:0 1px 2px rgba(25,28,34,.04),0 8px 24px rgba(25,28,34,.06)}
*,*::before,*::after{margin:0;padding:0;box-sizing:border-box}
html{font-size:16px;scroll-behavior:smooth;scroll-padding-top:60px}
body{font-family:var(--font-body);background:var(--bg);color:var(--text);line-height:1.75;min-height:100vh;-webkit-font-smoothing:antialiased;position:relative}
body::before{content:'';position:fixed;top:0;left:0;width:100%;height:100%;opacity:0;pointer-events:none;z-index:9999;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")}
.container{max-width:1100px;margin:0 auto;padding:24px}
.site-header{display:flex;align-items:center;justify-content:space-between;padding:0 24px;height:52px;background:rgba(245,244,240,0.88);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border-bottom:1px solid var(--border);position:sticky;top:0;z-index:100}
.site-nav{display:flex;gap:4px}
.site-nav a{color:#5C6370;text-decoration:none;font-size:13px;font-weight:500;padding:6px 14px;border-radius:6px;transition:background .15s,color .15s;font-family:var(--font-body)}
.site-nav a:hover,.site-nav a[aria-current=page]{background:rgba(25,28,34,0.05);color:#191C22}
.nav-toggle{display:none}
.nav-toggle-label{display:none;cursor:pointer;width:44px;height:44px;align-items:center;justify-content:center;padding:8px}
.nav-toggle-label span,.nav-toggle-label span::before,.nav-toggle-label span::after{display:block;background:#191C22;height:2px;width:20px;border-radius:2px;position:relative;transition:all .3s}
.nav-toggle-label span::before,.nav-toggle-label span::after{content:'';position:absolute}
.nav-toggle-label span::before{top:-6px}
.nav-toggle-label span::after{top:6px}
.nav-more{position:relative}
.nav-more-btn{color:#5C6370;font-size:18px;font-weight:700;letter-spacing:2px;padding:6px 12px;border-radius:6px;cursor:pointer;background:none;border:none;transition:background .15s,color .15s;line-height:1}
.nav-more-btn:hover{background:rgba(25,28,34,0.05);color:#191C22}
.nav-more-menu{display:none;position:absolute;right:0;top:calc(100% + 8px);background:rgba(255,255,255,0.98);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);border:1px solid var(--border);border-radius:10px;padding:6px;min-width:180px;box-shadow:0 12px 40px rgba(25,28,34,0.12);max-height:calc(100vh - 76px);overflow-y:auto;overscroll-behavior:contain}
.nav-more-menu a{display:block;padding:10px 14px;border-radius:6px;color:#5C6370;text-decoration:none;font-size:13px;font-weight:500;transition:background .15s,color .15s;white-space:nowrap}
.nav-more-menu a:hover,.nav-more-menu a[aria-current=page]{background:#F1F0EC;color:#191C22}
.nav-more.open .nav-more-menu{display:block}
.nav-bar{position:sticky;top:52px;z-index:90;background:rgba(245,244,240,0.92);backdrop-filter:blur(12px);border-bottom:1px solid var(--border);padding:0 24px;display:flex;justify-content:center;gap:4px;overflow-x:auto;scrollbar-width:none}
.nav-bar::-webkit-scrollbar{display:none}
.nav-bar a{color:var(--text-muted);text-decoration:none;font-size:12px;font-weight:500;padding:14px 16px;white-space:nowrap;transition:color .2s,background .2s;border-radius:var(--r-sm)}
.nav-bar a:hover,.nav-bar a.active{color:var(--accent);background:rgba(79,70,229,0.08)}
.hero{background:linear-gradient(135deg,#EEF0FE,#FDFDFB,#E4F2F0);background-size:200% 200%;animation:heroShift 12s ease-in-out infinite;border-radius:var(--r-xl);padding:20px 24px;margin-bottom:20px;border:1px solid var(--border);box-shadow:var(--shadow);overflow:hidden;position:relative;text-align:center}
@keyframes heroShift{0%,100%{background-position:0% 50%}50%{background-position:100% 50%}}
.hero-content{position:relative;z-index:2}
.hero-particles{display:none}
.archetype-en{font-size:12px;font-weight:600;color:rgba(79,70,229,0.65);text-transform:uppercase;letter-spacing:3px;margin-bottom:4px}
.archetype-name{font-size:clamp(20px,3.5vw,26px);font-weight:800;color:#191C22;margin-bottom:4px;text-shadow:none;line-height:1.2}
.hero-tagline{font-size:clamp(13px,1.8vw,14px);font-style:italic;color:#5C6370;margin-bottom:6px;line-height:1.5}
.hero-name{font-size:14px;font-weight:500;color:#8B909B;letter-spacing:2.5px;margin-bottom:12px;text-transform:uppercase}
.hero-name::before,.hero-name::after{content:'';display:inline-block;width:20px;height:1px;background:#D9D5CC;vertical-align:middle;margin:0 8px}
.hub-cards-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:8px;margin-top:12px;text-align:left}
.hub-card-mini{display:flex;align-items:center;gap:12px;background:#FFFFFF;border:1px solid var(--border);border-radius:var(--r-md);padding:14px 16px;cursor:pointer;transition:transform .2s,background .2s;box-shadow:var(--shadow)}
.hub-card-mini:hover{transform:translateY(-2px);background:#FAFAF7}
.hub-card-mini-icon{width:36px;height:36px;border-radius:9px;display:flex;align-items:center;justify-content:center;font-size:16px;flex-shrink:0}
.hub-card-mini-title{font-size:13px;font-weight:700;color:#191C22}
.hub-card-mini-summary{font-size:11px;color:#5C6370;margin-top:2px;line-height:1.4}
.stat-sub{font-size:12px;color:var(--text-secondary);margin-top:2px;font-family:var(--font-mono)}
.hub-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--r-lg);margin-bottom:16px;overflow:hidden;transition:all .3s;box-shadow:var(--shadow)}
.hub-card-preview{display:flex;align-items:center;gap:16px;padding:20px 24px;cursor:pointer;transition:background .2s}
.hub-card-preview:hover{background:rgba(25,28,34,0.02)}
.hub-card-icon{width:40px;height:40px;border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:18px;flex-shrink:0}
.hub-card-title{font-size:16px;font-weight:700}
.hub-card-summary{font-size:13px;color:var(--text-secondary);margin-top:2px}
.hub-card-arrow{width:10px;height:10px;border-right:2px solid var(--text-muted);border-bottom:2px solid var(--text-muted);transform:rotate(45deg);margin-left:auto;transition:transform .3s;flex-shrink:0}
.hub-card.expanded .hub-card-arrow{transform:rotate(-135deg);border-color:var(--accent)}
.hub-card-content{max-height:0;overflow:hidden;transition:max-height .5s ease,padding .3s;padding:0 24px}
.hub-card.expanded .hub-card-content{max-height:none;padding:0 24px 24px}
.chip{font-size:11px;font-weight:600;padding:4px 12px;border-radius:20px;background:#FFFFFF;color:var(--text-secondary);border:1px solid var(--border)}
.chip.hl{background:#EEF0FE;color:#4F46E5;border-color:rgba(79,70,229,0.25)}
.stats{display:flex;gap:24px;flex-wrap:wrap;justify-content:center}
.stat-card{background:rgba(255,255,255,0.75);border:1px solid var(--border);border-radius:var(--r-md);padding:12px 20px;backdrop-filter:blur(10px)}
.stat-card .label{font-size:10px;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.5px}
.stat-card .value{font-size:24px;font-weight:700;font-family:var(--font-display);margin-top:2px;letter-spacing:-0.01em}
.section{margin-bottom:40px;opacity:0;transform:translateY(8px);transition:opacity 0.4s ease,transform 0.4s ease}
.section.visible{opacity:1;transform:translateY(0)}
.hub-card-content .section{margin-bottom:0;opacity:1;transform:none;transition:none}
.section-title{font-size:clamp(16px,2vw,22px);font-weight:800;margin-bottom:20px;padding-left:12px;border-left:3px solid var(--accent)}
.sub-title{font-size:15px;font-weight:700;color:var(--text-secondary);margin:24px 0 12px;padding-top:16px;border-top:1px solid var(--border)}
.pillar-header{display:flex;align-items:center;gap:12px;margin-bottom:24px;padding-bottom:16px;border-bottom:1px solid var(--border)}
.pillar-header .pillar-icon{width:40px;height:40px;border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:20px;flex-shrink:0}
.pillar-header h2{font-size:clamp(16px,2vw,20px);font-weight:800;margin:0}
.pillar-header .pillar-sub{font-size:12px;color:var(--text-muted);margin-top:2px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px}
.grid-3{grid-template-columns:repeat(auto-fit,minmax(200px,1fr))}
.grid-4{grid-template-columns:repeat(auto-fit,minmax(200px,1fr))}
.card{background:var(--surface);border:1px solid var(--border);border-radius:var(--r-lg);padding:20px;transition:transform .2s;box-shadow:var(--shadow)}
.card:hover{transform:translateY(-2px)}
.headline-card{position:relative}
.headline-card .card-pad{padding:20px 22px}
.headline{font-family:var(--font-display,inherit);font-size:16.5px;font-weight:900;line-height:1.6;margin-bottom:10px}
.headline-card .intro{color:var(--text-secondary);font-size:14px;line-height:1.8}
.card-title{font-size:14px;font-weight:700;margin-bottom:12px;display:flex;align-items:center;gap:8px}
.card-title .icon{font-size:18px}
.card-label{font-size:10px;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px}
.card-value{font-size:22px;font-weight:700;font-family:var(--font-mono);letter-spacing:-0.01em}
.card-sub{font-size:12px;color:var(--text-secondary);margin-top:4px}
.tc{text-align:center;padding:16px}
.pillar-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}
.pillar{background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);padding:16px;text-align:center;box-shadow:var(--shadow)}
.pillar.unknown{opacity:0.55;border-style:dashed;box-shadow:none}
.pillar .pillar-label{font-size:10px;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:8px}
.pillar .kanji{font-size:28px;font-weight:700;line-height:1.2}
.pillar .reading{font-size:11px;color:var(--text-secondary);margin-top:4px}
.element-badge{display:inline-block;font-size:10px;font-weight:600;padding:2px 10px;border-radius:12px;margin-top:8px}
.elem-wood{background:#E3F2E7;color:#15803D}
.elem-fire{background:#FCE9EC;color:#B91C1C}
.elem-earth{background:#FBF3E2;color:#A16207}
.elem-metal{background:#ECEEF1;color:#475569}
.elem-water{background:#E3EDFC;color:#1D4ED8}
.element-bar{display:flex;gap:8px;align-items:end;height:100px;margin:16px 0}
.element-col{flex:1;display:flex;flex-direction:column;align-items:center;gap:4px}
.element-fill{width:100%;border-radius:4px 4px 0 0;transition:height .6s ease}
.element-pct{font-size:12px;font-weight:700;font-family:var(--font-mono)}
.element-name{font-size:11px;color:var(--text-muted)}
.domain-bar{margin-bottom:12px}
.domain-header{display:flex;justify-content:space-between;font-size:12px;margin-bottom:4px}
.domain-track{height:8px;background:var(--surface2);border-radius:4px;overflow:hidden}
.domain-fill{height:100%;border-radius:4px;transition:width .6s ease}
.top5-list{list-style:none}
.top5-item{display:flex;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--border)}
.top5-item:last-child{border-bottom:none}
.rank{width:28px;height:28px;display:flex;align-items:center;justify-content:center;border-radius:50%;font-size:12px;font-weight:700;font-family:var(--font-mono);background:#EEF0FE;color:var(--accent);flex-shrink:0}
.sf-name{font-size:14px;font-weight:700}
.sf-domain{font-size:11px;color:var(--text-muted)}
.tag{display:inline-block;font-size:11px;font-weight:600;padding:3px 10px;border-radius:12px;margin:2px}
.tag-rb{background:#E3EDFC;color:#1D4ED8}
.tag-st{background:#E3F2E7;color:#15803D}
.tag-ex{background:#EDEBFA;color:#6D28D9}
.tag-inf{background:#FDEEE6;color:#C2410C}
.typo-cell{background:var(--surface2);border-radius:var(--r-sm);padding:10px}
.typo-label{font-size:10px;color:var(--text-muted);text-transform:uppercase}
.typo-value{font-size:18px;font-weight:700;margin-top:2px}
.typo-sub{font-size:11px;color:var(--text-secondary)}
.typo-desc{font-size:11px;color:var(--text-muted);line-height:1.5;margin-top:6px}
.cycle-table{width:100%;border-collapse:collapse;font-size:13px}
.cycle-table th{text-align:left;padding:8px 10px;color:var(--text-muted);font-weight:600;border-bottom:1px solid var(--border)}
.cycle-table td{padding:8px 10px;border-bottom:1px solid rgba(232,229,222,0.6)}
.cycle-table tr.current{background:#EEF0FE;border:1px solid rgba(79,70,229,0.3)}
.satsukai{font-size:11px;padding:2px 8px;border-radius:10px;font-weight:700}
.dai{background:#FCE9EC;color:var(--red)}
.chu{background:#FBF3E2;color:var(--yellow)}
.sho{background:#FDF6E7;color:var(--yellow)}
.chart-wrap{background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);padding:16px;margin:16px 0;box-shadow:var(--shadow)}
.unlock-banner{background:#FDF1E3;border:1px dashed rgba(180,83,9,0.35);border-radius:var(--r-md);padding:16px 20px;font-size:12px;color:var(--yellow);text-align:center;margin-top:16px}
.insight-box{background:var(--surface);border:1px solid var(--border);border-left:4px solid var(--accent);border-radius:var(--r-md);padding:20px;margin-bottom:16px}
.insight-box .insight-title{font-size:13px;font-weight:700;color:#4F46E5;margin-bottom:8px}
.insight-box p{font-size:13px;color:var(--text-secondary);line-height:1.8}
.badge{display:inline-flex;align-items:center;font-size:10.5px;font-weight:700;letter-spacing:.06em;padding:2.5px 9px;border-radius:999px;line-height:1.6}
.badge-action{background:rgba(79,70,229,0.12);color:var(--accent)}
.badge-warn{background:rgba(180,83,9,0.12);color:var(--yellow)}
.badge-peak{background:rgba(21,128,61,0.12);color:var(--accent-green-light)}
.section-desc{font-size:13px;color:var(--text-muted);margin-bottom:16px}
.trait-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:20px;text-align:left}
@media(max-width:768px){.trait-grid{grid-template-columns:repeat(2,1fr)}}
.trait{background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:14px 14px 12px;box-shadow:var(--shadow);display:flex;flex-direction:column;gap:6px}
.trait-ico{width:30px;height:30px;border-radius:9px;display:flex;align-items:center;justify-content:center;font-size:14px}
.trait-kw{font-size:13.5px;font-weight:800;line-height:1.4;color:#191C22}
.trait-dt{font-size:11.5px;color:var(--text-secondary);line-height:1.6;flex:1}
.trait-src{font-size:10px;font-weight:600;color:var(--text-muted);letter-spacing:.04em}
.year-timeline{display:flex;gap:2px;margin:16px 0}
.yt-month{flex:1;height:24px;border-radius:3px;display:flex;align-items:center;justify-content:center;font-size:9px;font-weight:700;color:rgba(25,28,34,0.72);cursor:pointer;transition:all .2s}
.yt-month:hover{transform:scaleY(1.3)}
.month-selector{display:flex;gap:4px;overflow-x:auto;-webkit-overflow-scrolling:touch;scrollbar-width:none;padding:8px 0;margin-bottom:20px}
.month-selector::-webkit-scrollbar{display:none}
.month-btn{flex-shrink:0;padding:8px 14px;border-radius:999px;background:var(--surface);border:1px solid var(--border);color:var(--text-secondary);font-size:12px;font-weight:600;cursor:pointer;transition:all .2s;white-space:nowrap;font-family:var(--font-body)}
.month-btn:hover{background:#FAFAF7;color:var(--text)}
.month-btn.active{background:#EEF0FE;color:#4F46E5;border-color:rgba(79,70,229,0.35)}
.month-btn.current{box-shadow:0 0 0 1px rgba(79,70,229,0.45)}
.month-panel{display:none}
.month-panel.active{display:block}
.month-card-header{display:flex;align-items:center;gap:12px;margin-bottom:16px;padding-bottom:12px;border-bottom:1px solid var(--border)}
.month-label{font-size:18px;font-weight:800;font-family:var(--font-mono)}
.month-tags{display:flex;gap:6px;flex-wrap:wrap}
.month-tag{font-size:10px;font-weight:600;padding:2px 8px;border-radius:10px}
.domain-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.domain-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);padding:16px;border-left:3px solid var(--accent);box-shadow:var(--shadow)}
.domain-card.work{border-left-color:var(--blue)}
.domain-card.money{border-left-color:var(--gold)}
.domain-card.health{border-left-color:var(--green)}
.domain-card.romance{border-left-color:#BE334E}
.domain-icon-label{display:flex;align-items:center;gap:8px}
.domain-label{font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.5px}
.domain-stars{font-family:var(--font-mono);font-size:13px;letter-spacing:1px}
.domain-msg{font-size:11px;color:var(--text-secondary);line-height:1.6;margin-top:6px}
.chart-legend{display:flex;flex-direction:column;gap:10px;margin-top:12px;padding:16px;background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);box-shadow:var(--shadow)}
.chart-legend-item{display:flex;align-items:flex-start;gap:10px}
.chart-legend-line{display:inline-block;width:24px;height:3px;border-radius:2px;margin-top:7px;flex-shrink:0}
.chart-legend-label{font-size:13px;font-weight:700;margin-right:6px}
.chart-legend-desc{font-size:12px;color:var(--text-secondary)}
.page-footer{text-align:center;padding:32px 0;font-size:11px;color:var(--text-muted);border-top:1px solid var(--border);margin-top:40px}
.guidance-summary{background:var(--surface);border:1px solid var(--border);border-radius:var(--r-lg);padding:24px;margin-bottom:8px;box-shadow:var(--shadow)}
.guidance-overview{display:flex;align-items:center;gap:12px;margin-bottom:16px;flex-wrap:wrap}
.guidance-energy-badge{display:inline-block;font-size:14px;font-weight:700;padding:6px 16px;border-radius:20px}
.guidance-tags{display:flex;gap:6px;flex-wrap:wrap}
.guidance-narrative{font-size:14px;color:var(--text);line-height:1.85;margin-bottom:20px;padding-bottom:16px;border-bottom:1px solid var(--border)}
.guidance-actions-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}
.guidance-actions-section{display:flex;flex-direction:column;gap:12px}
.guidance-section-label{font-size:11px;font-weight:700;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px}
.guidance-action{display:flex;gap:12px;align-items:flex-start}
.guidance-action-icon{width:32px;height:32px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:14px;flex-shrink:0}
.guidance-action-title{font-size:13px;font-weight:700;color:var(--text);margin-bottom:2px}
.guidance-action-desc{font-size:12px;color:var(--text-secondary);line-height:1.7}
.guidance-watch{display:flex;flex-direction:column;gap:8px}
.guidance-watch-title{font-size:11px;font-weight:700;color:var(--yellow);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px}
.guidance-watch-item{font-size:12px;color:var(--text-secondary);line-height:1.7;padding-left:12px;border-left:2px solid rgba(180,83,9,0.35)}
.year-theme-banner{background:var(--surface);border:1px solid var(--border);border-left:4px solid var(--gold);border-radius:var(--r-md);padding:20px 24px;margin-bottom:20px;text-align:left}
.year-theme-label{font-size:11px;font-weight:700;color:var(--text-muted);text-transform:uppercase;letter-spacing:1px;margin-bottom:6px}
.year-theme-text{font-size:clamp(16px,2.5vw,22px);font-weight:800;line-height:1.4}
.blueprint-section{margin-top:24px;margin-bottom:8px}
.blueprint-header{font-size:14px;font-weight:700;color:var(--text-secondary);margin-bottom:12px;padding-left:12px;border-left:3px solid var(--accent2)}
.blueprint-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}
.blueprint-card{background:linear-gradient(135deg,#F5F3FE,#EEF0FE);border:1px solid rgba(109,40,217,0.16);border-radius:var(--r-md);padding:16px 20px}
.blueprint-label{font-size:10px;font-weight:700;color:var(--accent2);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px}
.blueprint-title{font-size:14px;font-weight:700;color:var(--text);margin-bottom:8px;line-height:1.4}
.blueprint-desc{font-size:12px;color:var(--text-secondary);line-height:1.75}
.month-advice{font-size:13px;color:var(--text-secondary);line-height:1.75;padding:12px 16px;background:linear-gradient(135deg,#EEF0FE,#F7F6FE);border:1px solid rgba(79,70,229,0.14);border-radius:var(--r-sm);margin-bottom:16px}
.section-quote{font-size:15px;font-style:italic;color:var(--text-secondary);margin-bottom:20px;padding-left:16px;border-left:2px solid rgba(79,70,229,0.3);line-height:1.7}
.accordion-header{cursor:pointer;display:flex;align-items:center;justify-content:space-between;padding:16px 0;border-top:1px solid var(--border)}
.accordion-header::after{content:'\\25B8';font-size:14px;color:var(--text-muted);transition:transform .3s}
.accordion-header.open::after{transform:rotate(90deg)}
.accordion-body{overflow:hidden;max-height:0;opacity:0;transition:max-height .4s ease,opacity .3s ease}
.accordion-body.open{max-height:5000px;opacity:1}
.rarity-badge{display:inline-flex;align-items:center;gap:6px;font-size:11px;color:var(--accent2);background:#F5F3FE;border:1px solid rgba(109,40,217,0.18);border-radius:20px;padding:4px 12px;margin-top:8px}
.collapse-toggle{display:inline-block;margin-top:10px;padding:6px 16px;font-size:12px;font-weight:600;color:#4F46E5;background:#EEF0FE;border:1px solid rgba(79,70,229,0.25);border-radius:999px;cursor:pointer;font-family:var(--font-body);transition:background .2s}
.collapse-toggle:hover{background:#E2E6FD}
.top5-item[style*=cursor]{transition:background .15s}
.top5-item[style*=cursor]:hover{background:rgba(25,28,34,0.03);border-radius:var(--r-sm)}
@media(max-width:768px){.grid{grid-template-columns:1fr}.pillar-grid{grid-template-columns:repeat(2,1fr)}.domain-grid{grid-template-columns:1fr}.guidance-actions-grid{grid-template-columns:1fr}.blueprint-grid{grid-template-columns:1fr}.hub-cards-grid{grid-template-columns:1fr}}
@media(max-width:640px){
  .nav-toggle-label{display:flex;align-items:center;justify-content:center;min-width:44px;min-height:44px}
  .site-nav{display:none;flex-direction:column;align-items:stretch;gap:0;position:absolute;top:52px;left:0;right:0;z-index:200;background:rgba(245,244,240,0.98);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border-bottom:1px solid var(--border);padding:8px 0;max-height:calc(100vh - 52px);overflow-y:auto;overscroll-behavior:contain}
  .site-nav a{padding:12px 24px;border-radius:0;font-size:14px}
  .nav-toggle:checked~.site-nav{display:flex}
  .nav-toggle:checked~.nav-toggle-label span{background:transparent}
  .nav-toggle:checked~.nav-toggle-label span::before{top:0;transform:rotate(45deg)}
  .nav-toggle:checked~.nav-toggle-label span::after{top:0;transform:rotate(-45deg)}
  .nav-more{display:contents}
  .nav-more-btn{display:none}
  .nav-more-menu{display:contents!important;position:static;background:none;border:none;box-shadow:none;padding:0;min-width:auto}
  .nav-more-menu a{padding:12px 24px;border-radius:0;font-size:14px;color:#5C6370}
  .container{padding:12px}
  .hero{padding:16px 16px;border-radius:var(--r-md)}
  .hub-card-preview{padding:16px}
  .hub-card-content{padding:0 16px}
  .hub-card.expanded .hub-card-content{padding:0 16px 16px}
  .stats{gap:8px}.stat-card{padding:8px 12px}
  .stat-card .value{font-size:18px}
  .pillar .kanji{font-size:22px}
}
.personality-summary{font-size:15px;color:var(--text-secondary);line-height:1.75;margin-bottom:20px;font-style:italic}
.personality-locked{position:relative;min-height:300px;overflow:hidden;border-radius:var(--r-md)}
.locked-skeleton{filter:blur(8px);opacity:0.3;padding:24px}

/* === Tier 1 additions === */
.eto-hero{display:grid;grid-template-columns:auto 1fr auto;gap:16px;align-items:center;background:linear-gradient(135deg,#EEF0FE,#FDFBFF);border:1px solid rgba(79,70,229,0.22);border-radius:var(--r-md);padding:18px 20px;margin-bottom:16px}
.eto-emoji{font-size:48px;line-height:1}
.eto-name .eto-title{font-size:18px;font-weight:800;color:#191C22;margin-bottom:2px}
.eto-name .eto-reading{font-size:12px;color:var(--text-secondary)}
.eto-rarity{text-align:right;padding-left:12px;border-left:1px solid rgba(79,70,229,0.25)}
.eto-rarity-label{font-size:10px;color:var(--text-muted);text-transform:uppercase;letter-spacing:.05em;margin-bottom:2px}
.eto-rarity-value{font-size:15px;font-weight:700;color:#4F46E5;font-family:var(--font-mono)}
.eto-narrative{margin-bottom:14px}
.eto-narrative p{font-size:14px;line-height:1.85;color:#333944;margin-bottom:10px}
.eto-cross{background:#EEF0FE;border-left:3px solid var(--accent,#4F46E5);border-radius:6px;padding:12px 14px;margin-top:10px}
.eto-cross-label{font-size:11px;color:#4F46E5;font-weight:700;letter-spacing:.08em;text-transform:uppercase;margin-bottom:6px}
.eto-cross-body{font-size:14px;line-height:1.8;color:#333944}
.eto-traits-row{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0 14px}
.eto-trait{font-size:12px;background:#EEF0FE;border:1px solid rgba(79,70,229,0.3);color:#4F46E5;padding:4px 10px;border-radius:14px;font-weight:600}
.confidence-badge{font-size:12px;color:var(--text-secondary);background:#EEF0FE;border-left:3px solid rgba(79,70,229,0.4);padding:10px 12px;border-radius:6px;margin-top:14px;line-height:1.7}

@media(max-width:600px){
  .eto-hero{grid-template-columns:auto 1fr;grid-template-rows:auto auto;gap:12px}
  .eto-rarity{grid-column:1/-1;text-align:left;padding-left:0;border-left:none;border-top:1px solid rgba(79,70,229,0.22);padding-top:10px}
}

.axes-stack{display:flex;flex-direction:column;gap:16px;margin:14px 0}
.axis-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);padding:16px 18px;box-shadow:var(--shadow)}
.axis-card-header{display:flex;align-items:center;gap:12px;margin-bottom:10px;flex-wrap:wrap}
.axis-card-name{font-size:16px;font-weight:800;color:#191C22;letter-spacing:.02em}
.verdict-badge{font-size:11px;font-weight:700;padding:4px 10px;border-radius:14px;letter-spacing:.03em}
.verdict-strong{background:#E3E1FB;color:#4F46E5;border:1px solid rgba(79,70,229,0.3)}
.verdict-lean{background:#EEF0FE;color:#6366F1;border:1px solid rgba(99,102,241,0.3)}
.verdict-split{background:#ECEEF1;color:var(--text-secondary);border:1px solid var(--border)}
.axis-card-verdict{font-size:14px;color:#333944;line-height:1.85;margin-bottom:14px;padding:10px 12px;background:#EEF0FE;border-left:3px solid rgba(79,70,229,0.3);border-radius:6px}
.axis-card-verdict strong{color:#4F46E5}
.axis-card-systems{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:10px}
.axis-column{padding:10px 12px;border-radius:8px;background:#FAFAF7;border:1px solid var(--border)}
.axis-column-dominant{background:#EEF0FE;border-color:rgba(79,70,229,0.22)}
.axis-column-minority{background:#FAFAF7;opacity:0.85}
.axis-column-title{font-size:12px;font-weight:700;color:var(--text-secondary);margin-bottom:6px}
.axis-column-dominant .axis-column-title{color:#4F46E5}
.axis-column-chips{display:flex;flex-wrap:wrap;gap:4px}
.sys-chip{font-size:11px;padding:3px 9px;border-radius:12px;white-space:nowrap}
.sys-chip-left,.sys-chip-right{background:#EEF0FE;color:#4F46E5;border:1px solid rgba(79,70,229,0.2)}
.axis-column-dominant .sys-chip{background:#E3E1FB;color:#4F46E5;border-color:rgba(79,70,229,0.25)}
.axis-empty{font-size:11px;color:var(--text-muted);font-style:italic}
.axis-outlier{font-size:13px;color:#333944;padding:10px 12px;background:#EEF0FE;border-left:3px solid rgba(79,70,229,0.4);border-radius:6px;line-height:1.8}
.axis-outlier-label{font-size:10px;font-weight:700;color:#4F46E5;letter-spacing:.08em;text-transform:uppercase;margin-right:6px}
.axis-outlier strong{color:#191C22}
@media(max-width:600px){
  .axis-card-systems{grid-template-columns:1fr}
}
.consensus-box{background:linear-gradient(135deg,#EEF0FE,#F8F8FD);border:1px solid rgba(79,70,229,0.25);border-radius:var(--r-md);padding:16px 18px;margin-top:16px}
.consensus-box.subtle{background:#FAFAF7;border-color:var(--border)}
.consensus-title{font-size:12px;font-weight:700;color:#4F46E5;letter-spacing:.08em;text-transform:uppercase;margin-bottom:8px}
.consensus-box.subtle .consensus-title{color:var(--text-secondary)}
.consensus-box ul{list-style:none;padding:0;margin:0}
.consensus-box li{font-size:14px;line-height:1.9;color:#333944;padding-left:18px;position:relative}
.consensus-box li::before{content:'✓';position:absolute;left:0;color:#4F46E5;font-weight:700}
.consensus-box.subtle p{font-size:14px;line-height:1.8;color:var(--text-secondary);margin:0}
.section-intro{font-size:14px;color:var(--text-secondary);line-height:1.85;margin-bottom:16px}
.section-intro strong{color:#191C22}

@media(max-width:600px){
  .axis-row{grid-template-columns:64px 1fr 64px;row-gap:6px}
  .axis-count{grid-column:1/-1;text-align:center;font-size:11px}
}

/* === Strengths × Shadow (CliftonStrengths Shadow Side 型) === */
.strengths-traps-grid{display:flex;flex-direction:column;gap:14px;margin:14px 0}
.strength-pair{display:grid;grid-template-columns:1fr 32px 1fr;gap:10px;align-items:stretch;background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);overflow:hidden;box-shadow:var(--shadow)}
.strength-side{padding:14px 16px;background:linear-gradient(135deg,#EEF0FE,#FDFDFB);border-right:1px solid var(--border)}
.shadow-side{padding:14px 16px;background:linear-gradient(135deg,#F1F0FC,#FDFDFB)}
.pair-label-pos{font-size:10px;font-weight:700;color:#4F46E5;letter-spacing:.08em;text-transform:uppercase;margin-bottom:6px}
.pair-label-neg{font-size:10px;font-weight:700;color:#6366F1;letter-spacing:.08em;text-transform:uppercase;margin-bottom:6px}
.pair-body{font-size:14px;line-height:1.7;color:#333944}
.pair-connector{display:flex;align-items:center;justify-content:center;font-size:18px;color:var(--text-muted);font-weight:700}
.strength-extra{font-size:13px;line-height:1.8;color:var(--text-secondary);margin-top:12px;padding:10px 12px;background:#EEF0FE;border-left:3px solid rgba(79,70,229,0.3);border-radius:6px}
.strength-extra strong{color:#4F46E5}
@media(max-width:600px){
  .strength-pair{grid-template-columns:1fr;grid-template-rows:auto auto auto}
  .strength-side{border-right:none;border-bottom:1px solid var(--border)}
  .pair-connector{padding:6px 0}
}

/* === 組み合わせパターン（事実ベース・Twin Stats 主役化） === */
.rarity-bar{background:linear-gradient(135deg,#EEF0FE,#FBF3E2);border:1px solid rgba(79,70,229,0.2);border-radius:var(--r-md);padding:20px 22px;margin:20px 0 16px}
.rarity-badge-top{display:inline-block;font-size:10px;font-weight:700;padding:4px 12px;border-radius:16px;border:1px solid rgba(79,70,229,0.25);background:#FFFFFF;color:#4F46E5;letter-spacing:.08em;text-transform:uppercase;margin-bottom:14px}
.rarity-twin-stats{display:grid;grid-template-columns:1fr auto 1.3fr;gap:16px;align-items:center;padding:14px 10px;background:rgba(255,255,255,0.7);border-radius:10px;margin-bottom:14px}
.rarity-single-stat{padding:14px 10px;background:rgba(255,255,255,0.7);border-radius:10px;margin-bottom:14px}
.rarity-dual-geo{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px}
.geo-stat{padding:16px 18px;background:#FFFFFF;border:1px solid var(--border);border-radius:10px;text-align:center}
.geo-jp{background:linear-gradient(135deg,#FBF3E2,#FFFFFF);border-color:rgba(161,98,7,0.25)}
.geo-world{background:linear-gradient(135deg,#EEF0FE,#FFFFFF);border-color:rgba(79,70,229,0.25)}
.geo-label{font-size:12px;font-weight:700;color:var(--text-secondary);letter-spacing:.05em;margin-bottom:8px}
.geo-jp .geo-label{color:#A16207}
.geo-world .geo-label{color:#4F46E5}
.geo-main{font-size:13px;color:var(--text-secondary);margin-bottom:6px}
.geo-n{font-size:26px;font-weight:700;font-family:var(--font-mono);letter-spacing:-0.01em;color:#191C22}
.geo-jp .geo-n{color:#A16207}
.geo-world .geo-n{color:#4F46E5}
.geo-count{font-size:13px;color:#333944}
.geo-count strong{font-size:18px;color:#191C22;font-family:var(--font-mono)}
.rarity-context-note{text-align:left;font-size:12px;color:var(--text-muted);margin-bottom:12px;font-style:italic}
@media(max-width:600px){
  .rarity-dual-geo{grid-template-columns:1fr;gap:10px}
}
.twin-stat{text-align:center}
.twin-stat-hero{background:linear-gradient(135deg,#FBF3E2,#EEF0FE);padding:10px 14px;border-radius:10px;border:1px solid rgba(161,98,7,0.25)}
.twin-stat-value{display:flex;align-items:baseline;justify-content:center;gap:4px}
.twin-big{font-size:32px;font-weight:700;color:#191C22;font-family:var(--font-mono);line-height:1.1;letter-spacing:-0.02em}
.twin-stat-hero .twin-big{font-size:36px;color:#A16207;background:linear-gradient(135deg,#A16207,#4F46E5);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
.twin-unit{font-size:14px;color:var(--text-secondary);font-weight:500}
.twin-stat-label{font-size:12px;color:#4F46E5;margin-top:4px;font-weight:600}
.twin-stat-sub{font-size:10px;color:var(--text-muted);margin-top:2px}
.twin-divider{font-size:24px;color:var(--text-muted);opacity:0.4}
@media(max-width:600px){
  .rarity-twin-stats{grid-template-columns:1fr;gap:10px}
  .twin-divider{display:none}
  .twin-big{font-size:26px}
  .twin-stat-hero .twin-big{font-size:30px}
}
.rarity-breakdown{display:grid;grid-template-columns:repeat(auto-fit,minmax(90px,1fr));gap:8px;padding-top:12px;border-top:1px solid rgba(161,98,7,0.18)}
.rarity-item{text-align:center;padding:10px 6px;background:rgba(255,255,255,0.7);border-radius:8px}
.rarity-item-accent{background:#FBF3E2;border:1px solid rgba(161,98,7,0.25)}
.rarity-value{font-size:20px;font-weight:700;color:#191C22;font-family:var(--font-body);margin-bottom:4px}
.rarity-item-accent .rarity-value{color:#A16207;font-family:var(--font-mono);font-size:16px}
.rarity-label{font-size:10px;color:var(--text-muted);line-height:1.5}
.rarity-note{font-size:10px;color:var(--text-muted);margin-top:10px;padding-top:10px;border-top:1px dashed rgba(25,28,34,0.1);line-height:1.6;font-style:italic}
.rarity-synthesis{font-size:14px;line-height:1.95;color:#333944;padding:14px 16px;margin:14px 0;background:linear-gradient(135deg,#EEF0FE,#FBF3E2);border-left:3px solid #4F46E5;border-radius:8px;text-align:left}
.rarity-synthesis strong{color:var(--gold);font-weight:700}
.rarity-scale{margin-top:14px;padding-top:14px;border-top:1px dashed rgba(25,28,34,0.12)}
.rarity-scale-title{font-size:13px;font-weight:700;color:#4F46E5;margin-bottom:10px}
.rarity-scale-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:8px}
.scale-item{background:#EEF0FE;border:1px solid rgba(79,70,229,0.15);border-radius:8px;padding:10px 12px;text-align:center}
.scale-n{font-size:20px;font-weight:700;color:#4F46E5;font-family:var(--font-mono);letter-spacing:0.02em;margin-bottom:4px}
.scale-ctx{font-size:10px;color:var(--text-muted);line-height:1.5}
.rarity-scale-note{font-size:10px;color:var(--text-muted);margin-top:10px;font-style:italic;line-height:1.6}
.rarity-sources{margin-top:14px;padding:12px 14px;background:rgba(255,255,255,0.7);border:1px dashed rgba(25,28,34,0.12);border-radius:8px;text-align:left}
.rarity-sources-title{font-size:11px;font-weight:700;color:var(--text-secondary);letter-spacing:.05em;margin-bottom:8px}
.rarity-sources ul{list-style:none;padding:0;margin:0}
.rarity-sources li{font-size:11px;color:var(--text-muted);line-height:1.75;padding-left:14px;position:relative;margin-bottom:3px}
.rarity-sources li::before{content:'•';position:absolute;left:0;color:var(--text-muted)}
.rarity-sources a{color:#4F46E5;text-decoration:underline dotted;text-decoration-thickness:1px;text-underline-offset:2px}
.rarity-sources a:hover{color:#4338CA}

/* === 用語ツールチップ === */
abbr.term{text-decoration:none;border-bottom:1px dotted rgba(161,98,7,0.5);cursor:help;color:inherit}
abbr.term:hover,abbr.term:focus{border-bottom-color:#A16207;border-bottom-style:solid;color:#A16207;outline:none}
#gloss-tip{position:fixed;z-index:9999;background:#FFFFFF;color:#191C22;padding:10px 14px;border-radius:8px;font-size:13px;font-weight:400;line-height:1.75;max-width:320px;box-shadow:0 8px 24px rgba(25,28,34,0.15),0 0 0 1px rgba(161,98,7,0.25);pointer-events:none;white-space:normal;text-align:left;font-style:normal;opacity:0;transition:opacity .15s;display:none}

/* === 用語ガイド（折りたたみ） === */
.glossary-details{background:#F0F2FE;border:1px solid rgba(79,70,229,0.2);border-radius:var(--r-md);padding:12px 16px;margin:16px 0}
.glossary-details summary{cursor:pointer;font-size:14px;color:#4F46E5;list-style:none;padding:2px 0;user-select:none}
.glossary-details summary::-webkit-details-marker{display:none}
.glossary-details summary::before{content:'▸ ';color:#4F46E5;margin-right:4px}
.glossary-details[open] summary::before{content:'▾ '}
.glossary-details[open] summary{margin-bottom:12px;padding-bottom:10px;border-bottom:1px solid rgba(79,70,229,0.15)}
.glossary-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:10px}
.glossary-item{padding:10px 12px;background:#FFFFFF;border-radius:8px}
.glossary-term{font-size:14px;font-weight:700;color:#A16207;margin-bottom:4px}
.glossary-expl{font-size:12px;color:var(--text-secondary);line-height:1.75}
.glossary-hint{font-size:11px;color:var(--text-muted);margin-top:10px;padding-top:10px;border-top:1px dashed rgba(79,70,229,0.15);line-height:1.7;font-style:italic}

/* === Cross-Reference Insight === */
.cross-section{margin:18px 0}
.cross-section-label{display:flex;align-items:center;gap:8px;font-size:13px;font-weight:700;letter-spacing:.03em;margin-bottom:12px;padding:8px 14px;border-radius:8px}
.cross-section-label-agree{background:#EEF0FE;color:#4F46E5;border:1px solid rgba(79,70,229,0.25)}
.cross-section-label-tension{background:#F1F0FC;color:#6366F1;border:1px solid rgba(99,102,241,0.3)}
.cross-label-emoji{font-size:16px}
.cross-grid{display:flex;flex-direction:column;gap:12px}
.cross-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);padding:14px 16px;box-shadow:var(--shadow)}
.cross-agree{border-left:3px solid #4F46E5}
.cross-tension{border-left:3px solid #6366F1}
.cross-card-header{display:flex;align-items:center;gap:10px;margin-bottom:8px}
.cross-marker-agree{font-size:10px;font-weight:700;padding:3px 8px;border-radius:10px;background:#E3E1FB;color:#4F46E5;letter-spacing:.08em}
.cross-marker-tension{font-size:10px;font-weight:700;padding:3px 8px;border-radius:10px;background:#F1F0FC;color:#6366F1;letter-spacing:.08em}
.cross-card-title{font-size:15px;font-weight:700;color:#191C22;flex:1}
.cross-card-body{font-size:13px;color:var(--text-secondary);line-height:1.8;margin-bottom:10px}
.cross-card-body strong{color:#4F46E5;font-weight:600}
.cross-card-insight{font-size:14px;color:#333944;line-height:1.85;padding:10px 12px;background:#EEF0FE;border-radius:6px}
.cross-card-insight strong{color:#4F46E5}
.cross-empty{font-size:13px;color:var(--text-secondary);font-style:italic;padding:12px 14px;background:#FAFAF7;border-radius:8px;line-height:1.8}
@media(max-width:600px){
  .rarity-headline{gap:8px}
  .rarity-headline-main{font-size:14px;width:100%}
  .rarity-headline-main strong{font-size:20px}
}
.locked-row{height:16px;background:var(--surface2);border-radius:4px;margin-bottom:12px}
.locked-row.short{width:60%}
.locked-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:20px}
.locked-box{height:80px;background:var(--surface2);border-radius:var(--r-sm)}
.locked-overlay{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:24px}
.locked-icon{font-size:32px;margin-bottom:12px}
.locked-title{font-size:18px;font-weight:700;color:var(--text);margin-bottom:8px}
.locked-desc{font-size:13px;color:var(--text-secondary);line-height:1.6;max-width:360px;margin-bottom:20px}
.locked-cta{display:inline-block;padding:12px 28px;background:var(--accent);color:white;border-radius:var(--r-md);font-size:14px;font-weight:600;text-decoration:none;transition:opacity .2s}
.locked-cta:hover{opacity:0.85}
@media (prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:0.01ms!important;animation-iteration-count:1!important;transition-duration:0.01ms!important}}

/* === Pattern B light theme: overrides for hardcoded inline colors ===
   Content .py files embed dark-theme hex colors inline; they are not editable.
   Same technique as CSS_FEMALE: attribute selectors + !important. */
[style*="color:#a5b4fc"]{color:#4F46E5!important}
[style*="color:#facc15"]{color:#B45309!important}
[style*="color:#fde047"]{color:#A16207!important}
[style*="color:#86efac"]{color:#15803D!important}
[style*="color:#f472b6"]{color:#BE334E!important}
[style*="color:#f9a8d4"]{color:#BE334E!important}
[style*="color:#5eead4"]{color:#0F766E!important}
[style*="color:#fb923c"]{color:#C2410C!important}
[style*="color:#ff8f6b"]{color:#C2410C!important}
[style*="color:#94a3b8"]{color:#475569!important}
[style*="background:rgba(255,255,255,0.05)"]{background:rgba(25,28,34,0.05)!important}
[style*="background:rgba(99,102,241,0.15)"]{background:rgba(79,70,229,0.10)!important}
[style*="background:rgba(139,92,246,0.15)"]{background:rgba(109,40,217,0.10)!important}
[style*="background:rgba(139,92,246,0.06)"]{background:rgba(109,40,217,0.06)!important}
[style*="background:rgba(234,179,8,0.15)"]{background:rgba(161,98,7,0.12)!important}
[style*="background:rgba(234,179,8,0.08)"]{background:rgba(161,98,7,0.08)!important}
[style*="background:rgba(20,184,166,0.15)"]{background:rgba(15,118,110,0.12)!important}
[style*="background:rgba(251,146,60,0.18)"]{background:rgba(194,65,12,0.12)!important}
[style*="border-color:rgba(139,92,246,0.3)"]{border-color:rgba(109,40,217,0.3)!important}
[style*="border-color:rgba(234,179,8,0.3)"]{border-color:rgba(161,98,7,0.3)!important}
[style*="border-color:rgba(99,102,241,0.4)"]{border-color:rgba(79,70,229,0.35)!important}
[style*="border:1px solid rgba(20,184,166"]{border-color:rgba(15,118,110,0.35)!important}
[style*="border:1px solid rgba(251,146,60"]{border-color:rgba(194,65,12,0.4)!important}
[style*="border:1px solid rgba(234,179,8"]{border-color:rgba(161,98,7,0.3)!important}
[style*="border:1px solid rgba(139,92,246"]{border-color:rgba(109,40,217,0.25)!important}
[style*="border-left:3px solid #6366f1"]{border-left-color:#4F46E5!important}
[style*="border-left:3px solid #eab308"]{border-left-color:#A16207!important}
[style*="border-left:3px solid rgba(251,146,60"]{border-left-color:rgba(194,65,12,0.5)!important}
[style*="background:linear-gradient(135deg,rgba(99,102,241,0.12)"]{background:linear-gradient(135deg,#EEF0FE,#F5F3FE)!important}
[style*="background:linear-gradient(135deg,rgba(139,92,246,0.08)"]{background:linear-gradient(135deg,#F5F3FE,#EEF0FE)!important}
[style*="background:linear-gradient(135deg,rgba(234,179,8,0.08)"]{background:linear-gradient(135deg,#FBF3E2,#FDF6E7)!important}
[style*="background:#6366f1"]{background:#4F46E5!important}
[style*="background:#eab308"]{background:#A16207!important}
</style>'''

CSS_FEMALE = '''<style>
/* Female theme — light background, high contrast */
:root{
  --bg:#f5eff2;--surface:#fdf5f7;--surface2:#eedde4;
  --border:#c9a0ae;--border-light:#ddb8c4;
  --accent:#b0445f;--accent2:#9040a0;
  --text:#2c1a20;--text-secondary:#6b3d50;--text-muted:#7a4f5e;
  --yellow:#8c6820;
}
body{background:var(--bg);color:var(--text)}
body::before{opacity:0.01}
/* Nav */
.site-header{background:rgba(245,239,242,0.96)!important;border-bottom:1px solid var(--border)}
.site-nav a{color:#6b3d50}
.site-nav a:hover,.site-nav a[aria-current=page]{background:#eedde3;color:#2c1a20}
.nav-bar{background:rgba(245,239,242,0.97)!important;border-bottom:1px solid var(--border)}
.nav-bar a{color:var(--text-muted)}
.nav-bar a:hover,.nav-bar a.active{color:var(--accent);background:rgba(176,68,95,0.12)}
.nav-toggle-label span,.nav-toggle-label span::before,.nav-toggle-label span::after{background:#6b3d50}
.nav-more-btn{color:#6b3d50}
.nav-more-btn:hover{background:#eedde3;color:#2c1a20}
.nav-more-menu{background:rgba(245,239,242,0.98);border-color:rgba(176,68,95,0.2)}
.nav-more-menu a{color:#6b3d50}
.nav-more-menu a:hover,.nav-more-menu a[aria-current=page]{background:#eedde3;color:#2c1a20}
/* Hero */
.hero{background:linear-gradient(135deg,#f0d0dc,#f8e2ec,#e8d0e0)!important;background-size:200% 200%!important;border:1px solid rgba(176,68,95,0.3)!important}
.hero-particles::before{background:rgba(176,68,95,0.25);box-shadow:180px 40px 0 rgba(176,68,95,0.15),320px -20px 0 rgba(144,64,160,0.12),450px 60px 0 1px rgba(176,68,95,0.1)}
.hero-particles::after{background:rgba(144,64,160,0.2);box-shadow:-200px -30px 0 rgba(176,68,95,0.15),-100px 20px 0 1px rgba(144,64,160,0.1)}
.archetype-en{color:rgba(140,40,70,0.85)}
.archetype-name{color:#3a0f1f;text-shadow:0 0 40px rgba(176,68,95,0.2),0 0 80px rgba(176,68,95,0.1)}
.hero-tagline{color:rgba(44,26,32,0.85)}
.hero-name{color:rgba(44,26,32,0.9)}
.hero-name::before,.hero-name::after{background:rgba(176,68,95,0.4)}
/* Hero hub cards */
.hub-card-mini{background:#fdf5f7!important;border:1px solid #c9a0ae!important}
.hub-card-mini:hover{background:#f5e6ec!important}
.hub-card-mini-title{color:#2c1a20!important}
.hub-card-mini-summary{color:#6b3d50!important}
/* Stat cards */
.stat-card{background:#f8edf1!important;border:1px solid #ddb8c4}
/* Chips */
.chip{background:#eedde3!important;color:#6b3d50!important;border:1px solid #c9a0ae!important}
.chip.hl{background:rgba(176,68,95,0.15)!important;color:#8c2840!important;border-color:rgba(176,68,95,0.35)!important}
/* Cards */
.hub-card-preview:hover{background:#f5e6ec!important}
/* Section items */
.top5-item[style*="cursor"]:hover{background:rgba(0,0,0,0.03)!important;border-radius:var(--r-sm)}
/* Insight boxes */
.insight-box{background:var(--surface)!important;border:1px solid var(--border)!important;border-left:4px solid rgba(176,68,95,0.55)!important}
.insight-box .insight-title{color:#7b3f8a!important}
.insight-box p{color:var(--text-secondary)}
.blueprint-card{background:linear-gradient(135deg,rgba(176,68,95,0.06),rgba(144,64,160,0.04))!important;border:1px solid rgba(176,68,95,0.16)!important}
.month-advice{background:linear-gradient(135deg,rgba(176,68,95,0.06),rgba(144,64,160,0.04))!important;border:1px solid rgba(176,68,95,0.14)!important}
[style*="border-left:3px solid #6366f1"]{border-left-color:#b0445f!important}
/* Collapse toggle */
.collapse-toggle{color:#7b3f8a!important;background:rgba(176,68,95,0.08)!important;border:1px solid rgba(176,68,95,0.2)!important}
.collapse-toggle:hover{background:rgba(176,68,95,0.15)!important}
/* Month timeline */
.yt-month{color:#2c1a20!important}
.month-btn{background:var(--surface)!important;border:1px solid var(--border)!important}
.month-btn:hover{background:var(--surface2)!important}
.month-btn.active{background:rgba(176,68,95,0.12)!important;color:#7b3f8a!important;border-color:rgba(176,68,95,0.35)!important}
.month-btn.current{box-shadow:0 0 0 1px rgba(176,68,95,0.4)!important}
/* Rarity section */
.rarity-synthesis{background:linear-gradient(135deg,rgba(176,68,95,0.06),rgba(144,64,160,0.04))!important;color:#2c1a20!important;border-left:3px solid #b0445f!important}
.rarity-synthesis strong{color:#8c6820!important}
.rarity-scale{border-top:1px dashed rgba(0,0,0,0.1)!important}
.rarity-note{border-top:1px dashed rgba(0,0,0,0.08)!important;color:var(--text-muted)}
.rarity-scale-title{color:#6b3d50!important}
.scale-item{background:rgba(176,68,95,0.04)!important;border:1px solid rgba(176,68,95,0.12)!important}
.scale-n{color:#7b3f8a!important}
.rarity-sources{background:rgba(0,0,0,0.02)!important;border:1px dashed rgba(0,0,0,0.1)!important}
.rarity-sources a{color:#7b3f8a!important}
.rarity-sources a:hover{color:#5a2e6e!important}
/* Glossary */
.glossary-details{background:rgba(176,68,95,0.04)!important;border:1px solid rgba(176,68,95,0.18)!important}
.glossary-details summary{color:#6b3d50!important}
.glossary-details summary::before{color:#b0445f!important}
.glossary-details[open] summary{border-bottom:1px solid rgba(176,68,95,0.15)!important}
.glossary-item{background:rgba(0,0,0,0.02)!important}
.glossary-term{color:#8c6820!important}
/* Abbr tooltips */
abbr.term{border-bottom-color:rgba(176,68,95,0.4)!important}
#gloss-tip{background:#fdf5f7!important;color:#2c1a20!important;box-shadow:0 8px 24px rgba(0,0,0,0.15),0 0 0 1px rgba(176,68,95,0.2)!important}
/* Inline color overrides for dynamic elements */
[style*="color:#a5b4fc"]{color:#7b3f8a!important}
[style*="color:#facc15"]{color:#8c6820!important}
[style*="background:rgba(234,179,8"]{background:rgba(140,104,32,0.12)!important}
[style*="background:rgba(99,102,241,0.12)"]{background:rgba(176,68,95,0.1)!important}
[style*="background:rgba(99,102,241,0.15)"]{background:rgba(176,68,95,0.12)!important}
[style*="border-color:rgba(99,102,241"]{border-color:rgba(176,68,95,0.35)!important}
/* ETO section */
.eto-narrative p{color:#2c1a20!important}
.eto-cross-label{color:#7b3f8a!important}
.eto-trait{color:#8c6820!important;border-color:rgba(140,104,32,0.3)!important}
/* Five elements */
.elem-wood{background:rgba(46,125,50,0.12)!important;color:#2e7d32!important}
.elem-fire{background:rgba(198,40,40,0.12)!important;color:#c62828!important}
.elem-earth{background:rgba(140,104,32,0.12)!important;color:#8c6820!important}
.elem-metal{background:rgba(89,89,89,0.12)!important;color:#555!important}
.elem-water{background:rgba(21,101,192,0.12)!important;color:#1565c0!important}
/* Axis cards */
.verdict-lean{color:#8c6820!important;background:rgba(140,104,32,0.08)!important;border-color:rgba(140,104,32,0.3)!important}
.axis-card-verdict strong{color:#8c6820!important}
.sys-chip-left,.sys-chip-right{color:#7b3f8a!important;background:rgba(123,63,138,0.08)!important}
.axis-outlier-label{color:#8c6820!important}
.axis-column{background:rgba(0,0,0,0.03)!important}
.axis-column-minority{background:rgba(0,0,0,0.02)!important}
/* Strengths */
.strength-extra{background:rgba(176,68,95,0.06)!important;border-left-color:rgba(176,68,95,0.3)!important}
.strength-extra strong{color:#7b3f8a!important}
/* Rarity */
.rarity-badge-top{color:#7b3f8a!important;background:rgba(123,63,138,0.12)!important}
.rarity-item-accent .rarity-value{color:#8c6820!important}
/* Geo rarity */
.geo-jp .geo-label,.geo-jp .geo-n{color:#8c6820!important}
.geo-world .geo-label,.geo-world .geo-n{color:#7b3f8a!important}
/* Twin stat */
.twin-stat-hero .twin-big{color:#8c6820!important;background:linear-gradient(135deg,#8c6820,#b0445f)!important;-webkit-background-clip:text!important;-webkit-text-fill-color:transparent!important}
.twin-stat-label{color:#7b3f8a!important}
/* Cross card */
.cross-card-body strong{color:#7b3f8a!important}
.cross-card-insight strong{color:#8c6820!important}
/* Abbr hover */
abbr.term:hover,abbr.term:focus{color:#8c6820!important}
/* Consensus box */
.consensus-box.subtle{background:rgba(0,0,0,0.02)!important;border-color:rgba(0,0,0,0.1)!important}
/* Tag badges */
.tag-rb{background:rgba(21,101,192,0.12)!important;color:#1565c0!important}
.tag-st{background:rgba(46,125,50,0.12)!important;color:#2e7d32!important}
.tag-ex{background:rgba(90,46,110,0.12)!important;color:#5a2e6e!important}
.tag-inf{background:rgba(176,68,95,0.12)!important;color:#8c2840!important}
/* Missing body text — previously unreadable on cream background */
.twin-big{color:#2c1a20!important}
.rarity-value{color:#2c1a20!important}
.geo-count{color:#6b3d50!important}
.geo-count strong{color:#2c1a20!important}
.eto-cross-body{color:#2c1a20!important}
.axis-card-verdict{color:#2c1a20!important}
.axis-outlier{color:#2c1a20!important}
.axis-outlier strong{color:#2c1a20!important}
.consensus-box li{color:#2c1a20!important}
.consensus-box li::before{color:#2e7d32!important}
.pair-body{color:#2c1a20!important}
[style*="color:#e5e7eb"]{color:#2c1a20!important}
[style*="color:#e4e4e7"]{color:#2c1a20!important}
[style*="color:#c7d2fe"]{color:#6b3d50!important}
[style*="color:var(--accent-amber-pale)"]{color:#8c6820!important}
[style*="color:#86efac"]{color:#2e7d32!important}
[style*="color:#94a3b8"]{color:#555!important}
[style*="color:#f9a8d4"]{color:#b0445f!important}
[style*="color:#d1d5db"]{color:#2c1a20!important}
/* Hardcoded #fff overrides missing from base CSS */
.eto-name .eto-title{color:#2c1a20!important}
.axis-card-name{color:#2c1a20!important}
.section-intro strong{color:#2c1a20!important}
.cross-card-title{color:#2c1a20!important}
</style>'''
