"""Dashboard section helpers: generated by refactor split."""
from datetime import date as _date

SECTION_QUOTES = {
    'core_identity': 'あなたを一言で表すなら—',
    'personality': '才能は、使い方を知ったとき初めて力になる',
    'divination': '2,000年の叡智が、あなたの星を読み解く',
    'forecast': '未来は決まっていない。しかし、流れは見える',
    'monthly': '毎月、あなたの運気は新しい色に染まる',
    'cross': '点と点が、線になる瞬間',
    'money': '流れを読む者が、富を留める',
    'work': '深く掘った穴の分だけ、高く積み上がる',
    'relationships': '深く狭く、選び抜いた縁が最も強い',
    'life_arc': '波は、ひとつの物語の中にある',
}

def _section_quote(key):
    q = SECTION_QUOTES.get(key, '')
    if not q:
        return ''
    return f'<div class="section-quote">"{q}"</div>'

def _footer(tier):
    gen_date = _date.today().isoformat()
    return f'''<footer class="page-footer">
  <div>Self-Insight — Powered by AI × 東洋占術 × 心理学</div>
  <div style="margin-top:4px;font-size:10px">Generated {gen_date}</div>
</footer>'''

def _hub_card(section_id, icon, icon_bg, icon_color, title, summary, content, expanded=True):
    """Wrap a section in a collapsible hub card."""
    exp_cls = ' expanded' if expanded else ''
    return f'''<div class="hub-card{exp_cls}" id="{section_id}-card">
  <div class="hub-card-preview" onclick="this.parentElement.classList.toggle('expanded')">
    <div class="hub-card-icon" style="background:{icon_bg};color:{icon_color}">{icon}</div>
    <div>
      <div class="hub-card-title">{title}</div>
      <div class="hub-card-summary">{summary}</div>
    </div>
    <div class="hub-card-arrow"></div>
  </div>
  <div class="hub-card-content">
    {content}
  </div>
</div>'''
