"""Dashboard section helpers: generated by refactor split."""
import json
from datetime import date as _date
import yaml

def load_yaml(path):
    with open(path, 'r') as f:
        return yaml.safe_load(f)

def star_html(n, mx=5):
    return (f'<span style="color:var(--yellow);">{"★"*int(n)}</span>'
            f'<span style="color:var(--border);">{"★"*(mx-int(n))}</span>')

def energy_color(e):
    if e >= 70: return 'var(--accent-green-light)'
    if e >= 40: return '#facc15'
    return 'var(--accent-red-light)'

def satsukai_html(s):
    if not s: return '—'
    cls = 'dai' if '大' in str(s) else 'chu' if '中' in str(s) else 'sho'
    return f'<span class="satsukai {cls}">{s}</span>'

SF_JA = {
    'Empathy': '共感性', 'Intellection': '内省', 'Deliberative': '慎重さ',
    'Connectedness': '運命思考', 'Maximizer': '最上志向', 'Futuristic': '未来志向',
    'Relator': '親密性', 'Activator': '活発性', 'Individualization': '個別化',
    'Learner': '学習欲', 'Input': '収集心', 'Ideation': '着想',
    'Command': '指令性', 'Context': '原点思考', 'Focus': '目標志向',
    'Developer': '成長促進', 'Achiever': '達成欲', 'Self-Assurance': '自己確信',
    'Arranger': 'アレンジ', 'Analytical': '分析思考', 'Responsibility': '責任感',
    'Consistency': '公平性', 'Positivity': 'ポジティブ', 'Strategic': '戦略性',
    'Adaptability': '適応性', 'Harmony': '調和性', 'Includer': '包含',
    'Communication': 'コミュニケーション', 'Woo': '社交性', 'Restorative': '回復志向',
    'Discipline': '規律性', 'Significance': '自我', 'Competition': '競争性',
    'Belief': '信念',
}

DOMAIN_JA = {
    'Relationship Building': '人間関係構築',
    'Strategic Thinking': '戦略的思考',
    'Executing': '実行力',
    'Influencing': '影響力',
}

ENNEA_NAMES = {1:'完璧主義者',2:'援助者',3:'達成者',4:'個性派',5:'観察者',
               6:'忠実家',7:'楽天家',8:'挑戦者',9:'調停者'}

HSP_LABELS = {'low':'穏やか','medium':'中程度','high':'繊細'}

ADHD_LABELS = {'minimal':'安定型','leaning':'やや多動','significant':'多動型'}
